### ISSUE TITLE
Implement Data Exposure Store in nextJs Prototype and for veda-ui MapBlock component

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#1002]
As a result from spike ticket https://github.com/NASA-IMPACT/veda-ui/issues/978. This is the implementation ticket to implement the data exposure store in the nextJs prototype and showcase the pattern with what it looks like to replace the veda faux modules starting with the MapBlock mdx component.

**Acceptance Criteria:**
- [ ] Implement custom context provider store
- [ ] Get MapBlock component working in nextJs component, we would need static content that uses the MapBlock component (do this first and get it working as is)
- [ ] Update MapBlock component in veda-ui to take in datasets as a prop and remove faux modules as dependency from the component itself, create a wrapper container like done for data-catalog

**Bonus:**
- [ ] Get most if not all MDX components working when rendering custom mdx from mdx files, there seems to be an error with the Block component currently.. This way we can see the prototype rendering content correctly

**Comment by aboydnw** [comment]
Dropping a loom video from @sandrahoang686 here

https://www.loom.com/share/c177d7c437094b828a5cc2efe37b6150?sid=2cd102d8-50e5-4bfe-8eac-c68319899d84
