### ISSUE TITLE
Clicking on a dataset tag does not filter data catalog

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1016]
### Context

URL: https://staging.earth.gov/ghgcenter/

Blocking a release? (y/n): no

Priority: P2

- P1 - Blocking major workflow, pull into sprint and fix now
- P2 - Poor reflection of quality, find a way to fix in the next few sprints
- P3 - Minor annoyance or issue, place in backlog for future consideration

### Reproduction Steps

1. Visit data catalog page
2. Open any dataset
3. Click on any tag/topic at the top the dataset
4. You should be redirected to the data catalog page, filtered for the tag you clicked
5. Notice the URL has some parameters, but it is not correctly filtering

**Comment by hanbyul-here** [comment]
There were more problems related to query paramter generated by data-catalog. Putting those bugs here for the record.

- The Search query parameter is not respected in the Data Catalog page
  - Type 'air' as a search term. The query parameter for 'search' gets manipulated, but when I refresh, it gets wiped out as soon as the page loads.
- Navigating back to Data Catalog through Taxonomy Pills on the overview button does not work. 
  - Click on any taxonomy pill from data overview page. `taxonomy` query paramter gets wiped out as soon as the page loads.

**Comment by hanbyul-here** [comment]
Closed via https://github.com/NASA-IMPACT/veda-ui/pulls?q=is%3Apr+is%3Aclosed
