### ISSUE TITLE
Clicking to explore page from data catalog does not automatically filter for dataset in layer selection modal

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1017]
### Context

URL: https://staging.earth.gov/ghgcenter/

Blocking a release? (y/n): no

Regression issue? (y/n): yes

Priority: P2

- P1 - Blocking major workflow, pull into sprint and fix now
- P2 - Poor reflection of quality, find a way to fix in the next few sprints
- P3 - Minor annoyance or issue, place in backlog for future consideration

### Reproduction Steps

1. Visit data catalog page
2. Open any dataset
3. Click on the button to explore data
4. You should be redirected to the exploration page, with the layer selection modal open and filtered for the dataset that you came from
5. Notice that the layer selection modal is not filtered for the dataset you came from

**Comment by hanbyul-here** [comment]
Closed via https://github.com/NASA-IMPACT/veda-ui/pulls?q=is%3Apr+is%3Aclosed
