### ISSUE TITLE
Change to production data services URLs

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1019]
### Context

Sounds like we need to make these changes in the Earthdata instance and the EIC instance. @anayeaye can provide more info

Slack notification [here](https://developmentseed.slack.com/archives/C03LGTM2SSH/p1718733019913429)

**Comment by sandrahoang686** [comment]
https://github.com/NASA-IMPACT/veda-config-eic/pull/120

**Comment by sandrahoang686** [comment]
https://github.com/NASA-IMPACT/veda-config/pull/414

**Comment by sandrahoang686** [comment]
@hanbyul-here updating these URLs and going through the deploy previews - are there any QA steps or features we should be paying attention too when manually testing/validating? I guess this is the first time we are updating these urls 🤔

**Comment by sandrahoang686** [comment]
It looks like we'd need to test pretty well the E&A feature and the old analysis feature if that is still being used (?). Thats where I can find all the references to these endpoints being updated.
