### ISSUE TITLE
[Bug] Can't view Data Insights on mobile device

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1023]
### Context

URL: https://earth.gov/ghgcenter/stories/emit-and-aviris-3

Blocking a release? (y/n): no

Regression issue? (y/n): seems to be
[If yes, add Regression label]

Priority: P1

### Steps to reproduce the issue

I can replicate this on Safari and Chrome on iOS, but not on my computer at any window size. I can only replicate it on GHGC Portal, not on earthdata or earth.gov which makes me think it has something to do with the latest veda-ui version, but not sure.

1. Visit GHGC Portal on a mobile device (does not seem to replicate on computer with an adjusted window size)
2. Go to any data insight
3. See error page like the one below

![image](https://github.com/NASA-IMPACT/veda-ui/assets/92742765/9453ab4b-a4e4-40fd-a865-125452a7f44c)

**Comment by Jeanne-le-Roux** [comment]
Did this already get fixed? If not - I just want to note that data insights are working fine on my mobile device (not seeing any reference to CDT though, so maybe it's fixed).

**Comment by sandrahoang686** [comment]
Closing because short term solution has been applied https://github.com/US-GHG-Center/veda-config-ghg/pull/422
Long term error handling ticket created https://github.com/NASA-IMPACT/veda-ui/issues/1025
cc @Jeanne-le-Roux
