### ISSUE TITLE
[Bug] Buttons not rescaling on smaller screens

### ISSUE THREAD

**Issue by paridhi-parajuli** [NASA-IMPACT/veda-ui#1033]
### Context
The buttons are not being rescaled as required in smaller screens  ( iphones/androids)
URL: https://staging.earth.gov/ghgcenter

Blocking a release? (y/n): n

Regression issue? (y/n): n
[If yes, add Regression label]

Priority: P3

### Steps to reproduce the issue

1. Go to https://staging.earth.gov/ghgcenter in an iphone or android phone
2. Check to "Browser the data catalog" and "Introduction to the exploration environment" buttons

![image](https://github.com/NASA-IMPACT/veda-ui/assets/46867571/648d1550-a75e-4841-b257-ef5527c028f5)

**Comment by aboydnw** [comment]
Thanks for catching. I'd say we hold off on fixing this but be aware of this when making changes to the homepage

**Comment by aboydnw** [comment]
I was able to replicate this on my phone. In order to replicate on my computer I had to shrink my window and then zoom in past 100%, probably why it wasn't caught in development. @hanbyul-here is this something start that we can address across all buttons?

**Comment by hanbyul-here** [comment]
The style comes from the deprecated library so we can't do the fix for all the buttons, but I pushed the fix for those two buttons ☝️
