### ISSUE TITLE
[Bug] Data layer selection modal not in alphabetical order

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1042]
### Context

URL: https://staging.earth.gov/ghgcenter/exploration?datasets=%5B%5D&taxonomy=%7B%7D

Blocking a release? (y/n): n

Regression issue? (y/n): y
[If yes, add Regression label]

Priority: P3

### Steps to reproduce the issue

1. Go to Exploration page by clicking on top nav
2. Layer selection modal should open automatically, notice the order is not in alphabetical order

**Comment by dzole0311** [comment]
Thanks @aboydnw , yes this is the one and here is the issue I opened: https://github.com/NASA-IMPACT/veda-ui/issues/1038

We merged a fix for this yesterday, so it will go into the next release.

**Comment by aboydnw** [comment]
ah okay, I didn't catch it because it was already closed! I'll close this one and move that other one into the sprint so it's visible
