### ISSUE TITLE
[E & A] Misleading red dates in date picker

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#1079]
Maybe this is just a silly nitpick - I found it a bit misleading that some days were shown in red in the E&A date picker. My immediate reaction was that these were off limits / not available for some reason.

But I guess these are weekends - which is usually irrelevant for earth science data. 😉 

![image](https://github.com/user-attachments/assets/82a7589c-2099-4302-9d23-525090c9b146)

## Acceptance criteria

- [ ] All valid dates have the same color

**Comment by j08lue** [comment]
![image](https://github.com/user-attachments/assets/10d5e8d0-6f45-4c77-b139-4f092a086793)

**Comment by dzole0311** [comment]
Something is odd, this happens on the instance side only and not in the veda-ui repo. Looking into it.
