### ISSUE TITLE
[Bug] `externalLinksInNewTab` in `veda.config.js` isn't respected anymore

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-ui#1095]
### Context

URL: https://earth.gov/ghgcenter/data-catalog/eccodarwin-co2flux-monthgrid-v5

Blocking a release? (y/n): n

Regression issue? (y/n): y
[If yes, add Regression label]

Priority: It feels like a minor annoyance but if it's not too much work,  we would like to get it in for the next release

### Steps to reproduce the issue

1. Go to the URL ☝️ 
2. Click on one of the external links at the bottom of the page
3. It opens the link in the same tab when it should open in a new tab

### Other details
It looks like it was introduced in `veda-config-ghg@v2.0.9` which referenced `veda-ui@v5.3.0`

**Comment by hanbyul-here** [comment]
👋 How important is to keep the configuration variable? Would it be okay to open the external link in a new tab (without any configuration)?
