### ISSUE TITLE
Implement Carousel

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1098]
### Context

For GHGC R3, We have landed on a carousel design that GHG stakeholders agreed with and we feel is relatively accessible. This is intended to be part of R3. Ultimately we need some version of this in production by the end of August, but the earlier we can have something up and running, the faster we can get feedback, configure content, etc. 

It does not need to be a core component right now, although we expect that we'll want to make it a core component in the future.

Design ticket: #1084 

### Acceptance Criteria
- [ ] To the best of our ability, the carousel matches the designs
- [ ] Carousel auto progresses through each panel at a pace of 5 seconds per panel
- [ ] There is a "loading" animation to depict the current panel and progress of the autoprogression
- [ ] There is an animation (TBD) when the panel autoprogresses
- [ ] (ideally) When configuring, we can add more than 1 call to action link at the bottom of the content
- [ ] (ideally) When configuring, we can have 2, 3, or 4 panels

**Comment by slesaad** [comment]
Some new info on the carousel:

> Please go ahead with the new carousel design, we’re good with three features. These will link to:
> 
> 1. Urban landing page
> 2. GRA2PES story page
> 3. NYC story page
> 
> Just to reiterate my gratitude to the team for coming up with an elegant and functional solution here, we really appreciate your patience and ingenuity!
> 
> I will owe you supporting text for the carousel, among other pages, and that’s on my list to do next week. Will need to decide images as well, but if it’s not too much trouble to use some generic ones for now just to have something in staging:
> 
> 1. Busy city sidewalk (maybe one like this, I’d just like to have some sort of human element in one of the images: > https://www.istockphoto.com/photo/crowd-of-people-on-new-york-city-sidewalk-gm896586898-247564664)
> 2. GRA2PES screenshot
> 3. NYC skyline
