### ISSUE TITLE
[E & A] Add range slider for rescaling the min & max range of the color maps

### ISSUE THREAD

**Issue by dzole0311** [NASA-IMPACT/veda-ui#1102]
## Context

This is the second part of the configurable color map options: https://github.com/NASA-IMPACT/veda-ui/issues/994

The goal is to provide users with more control over how data is visualized by allowing them to adjust the range of values that the color map uses

<img width="471" alt="Screenshot 2024-08-13 at 15 32 47" src="https://github.com/user-attachments/assets/ad0e8b32-2109-4c27-bd15-2f7d80d1f82b">

## Acceptance Criteria

- [x] Add a range slider in the color map options
- [x] The slider should allow users to adjust the minimum and maximum values that define the range of the colormap.
- [x] Somehow document functionality of colormap configurability for future reference

## Related Tickets

https://github.com/NASA-IMPACT/veda-ui/issues/994

**Comment by j08lue** [comment]
Btw, this feature will only work for certain endpoints / services (e.g. TiTiler-based).

I guess we currently distinguish between three `layer` `type`s: `raster|vector|zarr`.

https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/frontmatter/layer.md

Will we need some more fine-grained distinction between server capabilities?

https://github.com/NASA-IMPACT/veda-config/blob/1250da71d5c09227938bcd614875ae85e54a1c58/datasets/cmip6-tas.data.mdx?plain=1#L30

**Comment by aboydnw** [comment]
I added an AC for documenting functionality. In particular, I am thinking it would be good to document how we achieve the list of options, as @dzole0311 defined in #1117 

> The precedence of the color maps are as follows:
> - Start with what is configured in the sourceParams of the dataset
> - If it's not defined, check for the dashboard render configuration coming from STAC endpoint
> - If still undefined, check for asset-specific renders using the sourceParams' assets. This is a special edge case for some datasets that have multiple assets (multiple assets under one collection item)
> - If all else fails, default to viridis
