### ISSUE TITLE
Set up Build pipeline for USWDS font size

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#1144]
USWDS builds out different font sizes for typefaces. Link: https://designsystem.digital.gov/utilities/font-size-and-family/ We decided that we don't need this feature. Investigate how we can consolidate the sizes for each type face.

**Comment by dzole0311** [comment]
With @faustoperez and @hanbyul-here we agreed to skip removing the font-normalization for now, until we have a clearer image of the template instance. So I'm closing the related PR, however, we have a reference to it and the necessary working configuration if we decide to implement the feature.
