### ISSUE TITLE
Cookie Consent - Clean up

### ISSUE THREAD

**Issue by snmln** [NASA-IMPACT/veda-ui#1171]
Notes from feedback on original [Cookie Consent Form](https://github.com/NASA-IMPACT/veda-ui/pull/1127) work: 

> - Currently, the scripts that check cookies run every time a new page loads which I am not sure if it is necessary.
> - (might be related to 1.) I feel like Layout component is doing too much of cookie-related works, which should not be a part of layout's job. It might be slightly complicated in real life since it is layout's job to decide whether to render a specific component or not. But maybe there is something in the middle ground.
> - Banner and CookieConsent expects different forms for its content, Banner expects html and CookieConsent expects markdown. I am fine with either of them, but we should consolidate them.

- [x] Consolidate Banner and CookieConsent, wether they both should accept HTML or markdown within config props.
- [x] Extract Cookie consent functionality from the layout component.
- [x] Run Cookie validation scripts only when necessary (this might require further discussion to define upper and lower boundary of when is and is not necessary)

**Comment by aboydnw** [comment]
@hanbyul-here do we have a place to document all current feature flags for instance owners?

I think this could be a good thing to document somewhere, and specifically on the cookie consent form we might want to define:
- When people should use it
- How to turn it on
- It's functionality (like how often users can expect to see this prompt, what the different selections do, etc)

**Comment by hanbyul-here** [comment]
@aboydnw There is this file: https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONFIGURATION.md, which has all the configuration-related documents. These documents are mainly for developers, so they miss some elements, such as when people should use it 🤔 I feel like these elements should be handled separately from dev docs - but not sure where it should go though, do you have an idea about where to put these kinds of docs?
