### ISSUE TITLE
[Design] Map Comparison for Two Datasets

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1178]
### Context

A common use case for stories is to use the slider comparison widget to compare two different datasets. There are some styling issues to consider, such as where to place the legends, and some configurability issues to consider, such as what fields are necessary for admins to configure the map comparison widget.

Related to #1150

**Comment by aboydnw** [comment]
Just sharing an example of map comparison with two datasets in the earthdata instance that could be used both as a reference and for testing when we get to implementation: https://www.earthdata.nasa.gov/dashboard/stories/nc-hogs

**Comment by snmln** [comment]
Attached are the figma designs with documentation for the proposed design changes. https://www.figma.com/design/8VUmPgkpHE4smeb0lPJdKy/veda---two-dataset-comparison?node-id=33-609&t=M6gMzOjtQwS2prLz-1

Within the above changes we address the design portion outlined in the following ticket: https://github.com/orgs/NASA-IMPACT/projects/17/views/6?pane=issue&itemId=53271026&issue=NASA-IMPACT%7Cveda-ui%7C844

As well as a design solution for the bug outline in the following ticket for categorical color maps: https://github.com/NASA-IMPACT/veda-ui/issues/1174
