### ISSUE TITLE
[Design] Template instance wireframes to communicate vision

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1179]
### Context

We want create some low fidelity wireframes to communicate the design and product vision for the dashboard and template instance post-refactor.

The goal is achieve alignment in the team and stakeholders on what we are building.

**Comment by faustoperez** [comment]
## Pod week mental model session

We had a session during Svalbard pod week (October 2024) to achieve alignment in the team about the new VEDA mental model. This is the main takeaways on the vision:

- It will support 4 basic content units / building blocks:
     - Data
     - Widgets
     - Tools
     - Pages
 - The main characteristics of these content units are
     - They can be listed on a catalog page
     - They can be referenced in stories and pages using a card component
     - Users can view them fullscreen in their own URL
     - They can be integrated into stories and pages
     - They should link/relate to one another
 - Instance teams (domain experts) will own the content organization on the instance side
 - VEDA UI team will focus on the data visualization side of the work and leave the infrastructure UI to USWDS components

All this info is captured in a Miro board 👉  https://miro.com/app/board/uXjVLeCk9_c=/?share_link_id=442269753356

![image](https://github.com/user-attachments/assets/14ffde23-6a1c-4d35-9495-a9ef3ad42649)

This is a diagram with the relationship between content units:

<img width="1586" alt="image" src="https://github.com/user-attachments/assets/d69e69b1-7d67-47fc-937a-ebd91853c631">


## Template instance wireframes

We created some preliminary wireframes to guide the conversation and communicate the vision, which will be completed using USWDS tokens during the template instance work. The main touchpoints for the template instance are:

- Homepage
- Static page (about)
- Dataset page
- Widget page
- Tool page
- Story page
- Dataset master catalog
- Widget master catalog
- Tool master catalog
- Story master catalog

<img width="1871" alt="image" src="https://github.com/user-attachments/assets/20395cd4-712f-41ef-9e0e-c63d6f0d64b6">

The template instance work is captured in this Figma file 👉 https://www.figma.com/design/PG7AhRloW6qJd9U00VdQ77/VEDA-Template-Instance?node-id=0-1&t=EyBtGBBj9NfA7Vqe-1
