### ISSUE TITLE
Design Data Catalog page of Template Instance using USWDS

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1193]
### Context

First step of designing template instance, goal is to go step by step through each page needed in the template instance and use the USWDS to design/build the template instance. This would not include actually building the page, but working with design and development to build each respective libraries to make implementation easier.

### Acceptance Criteria

- [ ] Figma wires showing design of data catalog page using USWDS styling

**Comment by faustoperez** [comment]
Figma link 👉 https://www.figma.com/design/PG7AhRloW6qJd9U00VdQ77/VEDA-Template-Instance?node-id=178-2&t=HAlyBRbfjH7jZgHy-1

----

<img width="1200" alt="VEDA Data Catalog" src="https://github.com/user-attachments/assets/f25917d4-0d1b-4159-8866-2202dfc58510">
