### ISSUE TITLE
Optimize USWDS utility and mixin imports for cleaner usage

### ISSUE THREAD

**Issue by dzole0311** [NASA-IMPACT/veda-ui#1196]
## Context

Currently, when using USWDS utilities or mixins in .scss files, we need to manually import them like this:

```
@use "uswds-core/src/styles/functions/utilities" as utils;
@use "uswds-core/src/styles/mixins/utilities" as mixins;
@use "uswds-core/src/styles/mixins/typography" as typography;
```

And then call them in styles like this:

```
.some-class {
    color: utils.color('base-lightest');
}

```

There might be a more efficient way to streamline these imports and simplify the paths so that we have cleaner code. We should see if we can optimize how these utilities are imported and used throughout the project.

## Acceptance Criteria

- [ ] Given when then
- [ ] Given when then

## Related Tickets

[If applicable, link any tickets that are related]

**Comment by sandrahoang686** [comment]
@dzole0311 @aboydnw we can probably close this with the change pattern introduced in [pageheader pr ](https://github.com/NASA-IMPACT/veda-ui/pull/1247/files#diff-ca8a013db093ae0d5125403da3e596788c491fbd906cfcbdd560dc44d6ee3e78) 👍🏼
