### ISSUE TITLE
Design Stories Catalog page of Template Instance using USWDS

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1201]
### Context

First step of designing template instance, goal is to go step by step through each page needed in the template instance and use the USWDS to design/build the template instance. This would not include actually building the page, but working with design and development to build each respective libraries to make implementation easier.

### Acceptance Criteria

- [x] Figma wires showing design of stories catalog page using USWDS styling
- [x] Differences in card component (used in data catalog and stories catalog) defined

**Comment by faustoperez** [comment]
The designs are ready for review on the Figma VEDA Template Instance file here 👉 https://www.figma.com/design/PG7AhRloW6qJd9U00VdQ77/VEDA-Template-Instance?node-id=406-2456&t=jhQIelQdkyxsD1eG-1

These are the VEDA/USWDS components involved:

- Header
- Footer
- Card
- Tag
- Pagination

![Image](https://github.com/user-attachments/assets/732db14f-0b51-4e5b-8f2e-c952671d1beb)
