### ISSUE TITLE
Initial designs for card component

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1209]
### Context

The card component shows up in multiple places across the dashboard and its core features. Known use cases:
- Data catalog to show available datasets
- Layer selection modal to show available layers in E&A
- Stories catalog
- Custom pages like the themes pages or [data toolkit](https://staging.earth.gov/ghgcenter/data-toolkit) that GHG developed
- [earth.gov redesign wireframes ](https://www.figma.com/proto/jlAIqxAG6hrxhCqYEA6ijh/Shareable-Earth.gov-Prototype?node-id=16-4293&starting-point-node-id=16%3A4293)developed by Esther

### Acceptance

- [x] Initial designs are developed in figma to show the different variations of the card component to meet the needs, as we know them now
- [x] Agreement between product, design, and engineering on what the first, most important card types will be

**Comment by aboydnw** [comment]
Related cards for consideration in design: 
- https://github.com/US-GHG-Center/veda-config-ghg/issues/636
- https://github.com/US-GHG-Center/veda-config-ghg/issues/637

**Comment by faustoperez** [comment]
Initial card designs are available on the Figma VEDA/USWDS file here 👉 https://www.figma.com/design/5mclPTReHcRIzKbJm8YA6a/VEDA---USWDS?node-id=317-1041&t=fhkfFZDZyevYUCxo-1

I will keep progressing with this piece of work as we build the rest of the template instance screens, but I think we have a consistent  foundation now.

![Image](https://github.com/user-attachments/assets/a67b4e63-20d3-4419-880f-e48bd87ceab4)
