### ISSUE TITLE
Adjust rescale values for small/large numbers

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1226]
Known Issues: 
1. The UI isn't great if you are trying to edit rescale values for long numbers (small decimals or large numbers)
2. When the rescale values are very small decimals (<0.01) then the UI doesn't function properly

![image](https://github.com/user-attachments/assets/56e3ae6f-cecc-4ebe-82b2-e3da4350cf0b)

### Acceptance Criteria
- [ ] Rescale value range slider still functions for small decimals of <0.01
- [ ] Large or long decimals are easily viewed or edited in the input box

**Comment by snmln** [comment]
Another issue Identified while working through the bug identified here: https://github.com/NASA-IMPACT/veda-ui/pull/1224#issuecomment-2444969653

When the values start to travers large decimal values the representation of the data changes from numeric to exponential:

![Screenshot 2024-10-30 at 10 56 10 AM](https://github.com/user-attachments/assets/07231ae9-b4c8-4887-acc4-d9e2bbbdf6c3)

We should nail down if we want this to be how we present the data value to end users.

**Comment by aboydnw** [comment]
Another thing that Sid caught that might be good to update if it's easy:

> When we change the rescale values (e.g. 50 to 43) should it also get reflected at the bottom? Every time it shows 50 what we have defined in the mdx.

![Image](https://github.com/user-attachments/assets/5aba141f-475d-46c6-b728-e6636e6bcac5)
