### ISSUE TITLE
Make feature carousel available in earth.gov

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1237]
### Context

The number of earth.gov featured centers is growing. The current construct of full page width highlights isn't ideal now that there are 3 centers to highlight. We'd like to repurpose the feature carousel for these highlights. Alex G and Brian can configure content, we just want to make the feature available to them in the same way it is available to GHGC.

### Acceptance Criteria
- [ ] Instance administrators are able to configure a feature carousel in the same way that the GHGC team can

**Comment by hanbyul-here** [comment]
The component from GHG is here:  https://github.com/US-GHG-Center/veda-config-ghg/tree/develop/overrides/home/carousel

In case this helps, this is also the first PR that I made to add the carousel: https://github.com/US-GHG-Center/veda-config-ghg/pull/482/files
