### ISSUE TITLE
Write 'what do we expect from PR' for external contributors

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1239]
### Context

As we scale to more deployments and more people outside of the core Dashboard team become involved in VEDA and its instances, we would like to have some documentation that helps those contributors. One idea is to have a document that describes what we would look for during a PR review. This could include some general guidance on creating a good PR, but we don't need to replicate all the other material out there on the internet. It should also include some guidance that is more VEDA-specific, like the different dependencies or potential effects that contributors should be aware of, or some common issues that we keep an eye out for when reviewing a PR.

Format is open, this could be a google doc or github documentation, or something else. We just want it to be accessible by new contributors as they come to VEDA from the different instance teams.

### Acceptance Criteria
- [ ] A document is easily accessible by new contributors, and IMPACT is aware of it (potentially linked to their onboarding doc)

**Comment by aboydnw** [comment]
@hanbyul-here I think [the doc you started](https://docs.google.com/document/d/1fAcaUgv45ufOZEtMN1wAVO5L3NLn2pRr_8dE_myViIk/edit?tab=t.0#heading=h.2mxdue9q0nut) is good, maybe there are just some additions that are more VEDA-specific? Like specific issues you often see (env variables, mapbox tokens?) or other dependencies you think new contributors should be aware of.

Do you think this ultimately lives in Github or just as a google doc?

**Comment by hanbyul-here** [comment]
I do want to move the docs to github at some points but while mulling over the contents, I would like to keep it in the docs @aboydnw 

I added veda-specific contents which I think can help contributors - the concerns you brought up (env vars, mapbox tokens..) are already in the documentation so this documentation doesn't need to repeat those, but I did point where people can find the dev docs.
