### ISSUE TITLE
Automate instance preview generation process

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1242]
### Context

It takes developer's valuable time to update veda-ui and create previews for testing.  We would like to make this easier for us to do as well as for any instance owners/contributors to conduct these releases. This issue is adjacently related to #1236 

### Acceptance Criteria

- [ ] When a veda-ui release is triggered, PRs for selected instances (GHG, earth.gov, and Earthdata) are created for testing purposes
- [ ] When a veda-ui release is triggered, appropriate team members are tagged on the release PR(s) and/or notified through slack

**Comment by hanbyul-here** [comment]
@aboydnw I edited the ticket so it is more catered towards creation of preview URLs, not the release of instances.
