### ISSUE TITLE
Scrolling on E&A in template instance

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1255]
### Context

Discovered that there is some weird scrolling behavior within the data layer panel on the E&A tool in the template instance
https://github.com/developmentseed/next-veda-ui/pull/4#issuecomment-2471603952

### Acceptance Criteria

- [ ] Able to scroll in the layers panel to view all layers without shifting the whole page

**Comment by dzole0311** [comment]
Fixed in the template instance via https://github.com/developmentseed/next-veda-ui/pull/14
