### ISSUE TITLE
[Refactor][Bugs] Preset AOIs in E&A

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#1259]
### Context
* AOI preselected states are taking a while to load and are erroring

Goal of this ticket to reduce errors and improve load times

**Comment by aboydnw** [comment]
@sandrahoang686 I adjusted this ticket to only be about preselected AOIs since I already had another ticket for https://github.com/NASA-IMPACT/veda-ui/issues/1256
