### ISSUE TITLE
[Design] MDX-generated stories

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1260]
### Context

Updating our stories to use USWDS components and styling, we want to show what each "widget" looks like using USWDS. We can also use this to introduce any other fun ideas for stories that we have been wanting to introduce.

### Acceptance Criteria
- [x] Figma file showing a story and each widget as using USWDS

**Comment by faustoperez** [comment]
Here are the designs for the story page.

Figma link 👉 https://www.figma.com/design/PG7AhRloW6qJd9U00VdQ77/VEDA-Template-Instance?node-id=581-2844&t=juGRrUo41ZVT2DSG-1

They feature these new VEDA/USWDS components which have been added to the library:

- Table
- Widget
- Card
- Alert
- In-page navigation (TBD). For now, we're not using the in-page navigation as it potentially clashes with full-width scrollytelling components or 2 column layouts, until we agree on the interaction of this component.

![Image](https://github.com/user-attachments/assets/30366a56-31de-40ee-9b09-5ee413b8cdc5)
