### ISSUE TITLE
[Design] Widget full page

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1261]
### Context

With a widget now as a defined content type in VEDA, users should be able to see a widget and share a widget with others. Long term, we envision having a widget catalog, and widgets that are shared across multiple stories/datasets. In the shorter term, we likely see just adding the ability for users to expand a widget to full screen mode from a story or dataset overview. 

So, we'd like some designs that are compatible with the long term, and also easy to implement in the short term. Imagine a user clicking an "expand" button on a story, seeing that widget full screen, being able to close it and return back to the story or share directly with somebody else. If somebody opens a link to a widget that has been shared with them, then they'd land on the full screen view and if they close it then ideally they see the story that the widget is on. (proposed workflow)

### Acceptance Criteria
- [x] Figma file outlining full screen view for the widget
- [x] Designs outlining the "expand" (name TBD) action that the user sees in a story/dataset overview page in order to open the full screen view, as well as any commentary on animation between the two

**Comment by faustoperez** [comment]
Here are the designs for the widget and the full-page widget.

Figma link 👉 https://www.figma.com/design/PG7AhRloW6qJd9U00VdQ77/VEDA-Template-Instance?node-id=502-1205&t=juGRrUo41ZVT2DSG-1

The close icon is the same as the browser back. Users can access the full widget page from multiple sources: catalog, story, dataset overview, other widget pages, etc.

They feature these new VEDA/USWDS components which have been added to the library:

- Widget
- Card
- Segmented button
- Icon button

![Image](https://github.com/user-attachments/assets/baa725da-0422-4fd3-8088-01764a389e14)
![Image](https://github.com/user-attachments/assets/db570fe3-075e-4c63-9a73-e9014002e30a)
