### ISSUE TITLE
Preview opening Exploration layers in QGIS

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#1298]
We just finished a feature that enables us to open XYZ tile links in QGIS.

@freitagb would like to demo this at AGU, which starts on Monday.

Could we until then make a preview build that adds a way for users to open XYZ layers in QGIS?

### Suggested approach:

We have this modal in the [Exploration environment](https://earth.gov/ghgcenter/exploration?datasets=%5B%7B%22id%22%3A%22air-sea-co2%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%2C%22colorMap%22%3A%22bwr%22%7D%7D%5D&taxonomy=%7B%7D&search=&date=2022-11-30T23%3A00%3A00.000Z) that has the XYZ links and buttons to copy them to clipboard. Could we add something (avoiding to say “button”) that opens a new tab with the QGIS service link?

![Image](https://github.com/user-attachments/assets/ab2dd6ce-a424-4933-b720-9cb11c49b6c4)

This is how you generate the URLs (see also this [demo script](https://gist.github.com/sunu/06027b5d3f9b86de8027b2be26e45a53#file-index-html-L173)):

```javascript
const generatedUrl = `${jupyterUrl}/qgis/?action=add_xyz_tile_layer&url=${quotedTileUrl}&layer_name=${encodeURIComponent(layerName)}&project_name=${encodeURIComponent(projectName)}`;
```

@sunu will share the `jupyterUrl` shortly.

The `url` parameter would be the XYZ URL.

`layer_name` and `project_name` are arbitrary - could be `layer_name={datasetName} + "at" + {datetime of current timestep}` and `project_name={Site title (e.g. U.S. Greenhouse Gas Center)}`.

## Acceptance criteria

- [ ] A preview build is up where users can with one click open the layer currently shown in Exploration in QGIS via the above mentioned service

**Comment by j08lue** [comment]
@dzole0311 with instructions from @sunu set up a nice preview for using the GHG Center instance:

- https://github.com/US-GHG-Center/veda-config-ghg/pull/688

### How to use this feature:

1. Open Exploration on [this preview build](https://deploy-preview-688--ghg-demo.netlify.app/exploration)
2. Add a layer
3. Open the Layer Options (three dots on the layer card) and select "Load into GIS"
4. Use this button to open in QGIS:
   ![Image](https://github.com/user-attachments/assets/75b73471-bc43-4f0a-adac-7903cf59c2ab)

**Comment by yuvipanda** [comment]
This is excellent! do you know when / how this will be deployed?

**Comment by j08lue** [comment]
Good question. Let's discuss here:

- https://github.com/NASA-IMPACT/veda-ui/issues/1362
