### ISSUE TITLE
Zarr visualization on dashboard

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#166]
This is a placeholder ticket to investigate zarr viz on dashboard. note that our titiler doesn't support zarr format yet. (so it won't follow the pattern of how we display raster data now.) 

helpful links: 
- https://www.youtube.com/watch?v=YnTAuSOAl2c&ab_channel=opengeospatial
- https://www.npmjs.com/package/@carbonplan/maps

**Comment by aboydnw** [comment]
Based on the outcome of this spike: https://github.com/NASA-IMPACT/veda-architecture/issues/57
