### ISSUE TITLE
Discoveries single: structure and style image mosaic component

### ISSUE THREAD

**Issue by ricardoduplos** [NASA-IMPACT/veda-ui#25]
As seen here: https://www.figma.com/proto/SA0u0sVdw5vM7g9ulV5Xgw/Wireframes?page-id=0%3A1&node-id=469%3A2005&viewport=442%2C48%2C0.5&scaling=min-zoom

<img width="842" alt="Screen Shot 2022-02-21 at 15 26 36" src="https://user-images.githubusercontent.com/1016701/154984703-68d7289c-e43a-4968-9245-a241914c1784.png">

**Comment by aboydnw** [comment]
Closing as stale, can reopen if needed
