### ISSUE TITLE
Analysis page feedback

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#318]
Umbrella issue to log feedback received for the analysis page.
Some items are comments/opinions and should be validated with other users to see if they're common pain points.

**Legend:**  
💬 Comments to the feedback received

## Copy

- The tag-line (`Visualize insights from a selected area over a period of time.`) could be more "direct2, feel more actionable.  Something along the lines: `Generate timeseries data for your area of interest` or `Generate custom analysis for datasets in the VEDA catalog`
- `Save` . The text on the button doesn’t really reflect the action I’m taking. Based on the text, I didn’t expect to generate the analysis. This may be different when somebody is "refining" their initial search. In that case, `Cancel` and `Save` feel more natural

## Map

- Expected the map to zoom with the scroll wheel. Ctrl + Scroll to zoom was unexpected
   💬 Without this, the map would block the scroll on smaller screens.
- Is it possible to delete a single node in the polygon?
   💬 Currently it is not possible, even thought the plugin offers that ability
- Area message: `38 K km^2` took me a bit to understand. I think one of the following options would be easier to parse: `38K km^2`, `38 000 km^2`. I don’t have the same issue with 48 M km^2 btw.
   💬 We could not shorten the thousands in the map's case

## Map toolbar
<img width="915" alt="image" src="https://user-images.githubusercontent.com/1090606/201096309-3fcd3d80-27a2-4df8-bf0d-30cad27dbfa4.png">

- It wasn't immediately obvious how to draw an area. I expected to be able to draw immediately on the map.
   💬 This was supposed to be the default behavior. Right @ricardoduplos?
- Hidden Toolbar - I scrolled down to select a date first. When scrolling back up, the tools kept being covered by the Page Hero and/or the tooltip. It was only when I scrolled back up completely, that the tools appeared again. For a first-time user, that doesn’t know the toolbar exists, it might be unclear what to do.
   💬 Perhaps the map message, could include a edit action?

## Date selection

- You allow for dates in the future. I imagine there are no datasets with future observations? Does this always result in no data available?
   💬 There may be. CMIP 6 is a dataset with predicted values, even though it is not yet present in the app.

## Download

- Expected this to download a CSV with data
   💬 Currently we only have image download. CSV is planned https://github.com/NASA-IMPACT/delta-ui/issues/262
- Image: missing title / caption
   💬 Issue created https://github.com/NASA-IMPACT/delta-ui/issues/317

## Chart

- Adjusting the range on one graph affects the other graph as well.
   💬 This is a feature, but was nonetheless considered strange. Gathering feedback about the charts behavior is planned.

## Other / Feature requests

- A way to go back to a previous search I did. Some of this requires trial and error, and going back to a previous search would be great. This doesn’t have to be fancy. Just a list with x last searches would be great already.
- Something that shows 2nd and 3rd quartile could be interesting. In addition to min/mix/mean. Gives a much better sense of distribution & variation of observations.

**Comment by danielfdsilva** [comment]
Round of feedback from meetings with stakeholders.

- All the charts should show the full selected date range even if there's no data.
- It would be good to show where the actual data points are. This is important when timesteps are skipped (example: there's data for January and March but not February)
  💬 It was suggested to show dots instead of lines, and have an option to "connect the dots" for when the users want to perceive trends.
- Unit should be present on the chart
  💬 Units alone are not enough, we need a transformation function. (example: original data is in meters, but we want to show it in miles)
- Extra stats would be nice to have
  💬 (1) median, (2) percentiles (5%, 25%, 75%, 95%), (3) linear fit
- Scientists are used to have quick access to more info about the datasets.
  💬 Whenever a dataset is mentioned (Chart, dataset selection on analysis define), there should be a way to quickly get info about it - info like the sensor, the data interval, the source (there will be different data for different datasets.)

**Comment by aboydnw** [comment]
I believe all of these points are now covered in the linked ticket, so I am going to close this ticket for now.
