### ISSUE TITLE
Modifying the date range from the gray bar of one chart does not modify the size of the bar of the other chart or other charts. 

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-ui#324]
### Description:
When the user selects two or more datasets to view the graphs and shortens the date range from one of the graphs, the gray bar of the date range of the other graph is not modified. But the date view of the other chart is modified.  

**Evidence**: [Video ](https://www.screencast.com/t/EUZNvvhB0)
![foto rango graficas](https://user-images.githubusercontent.com/111894012/201674670-1735eee3-7f65-4656-b0d9-8131316184ae.jpg)

### **Acceptance Criteria:**
When modifying the date range from the gray bar of a chart, the size of the gray bar of the other charts must also be modified.

**Comment by danielfdsilva** [comment]
This is a known bug with the Recharts library. For some reason the brush is not properly syncing. Before spending too much time solving this, we want to [gather feedback](https://github.com/NASA-IMPACT/delta-ui/issues/286) on whether the syncing behavior is something desirable.

**Comment by danielfdsilva** [comment]
@Catalina-Moller This should have been fixed with the new brush. Do you confirm?

**Comment by Catalina-Moller** [comment]
@danielfdsilva With the implementation of the new brush this issue has been solved!
