### ISSUE TITLE
Moving the location of the gray bar on one chart does not change it on another chart

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-ui#325]
### Description:
When the user has selected two or more datasets to view the graphs, moving the whole gray bar in one of the graphs modifies the whole time range of the graph, but nothing happens in the other graph and the dates in the graph view are not modified. 

This causes that when modifying the range of one and not the other, if the user passes the mouse over the first graph, in the information box the dates of each of the graphs do not match. 
We have not been able to reproduce this when the user hovers the mouse over the second graph.

**Evidence:** [Video ](https://www.screencast.com/t/XXGZLtRK)

### Acceptance Criteria:
When the user moves the entire gray bar in one of the graphs and modifies the entire time range of the graph, the time range of the other graph and the place of the gray bar is also modified. 

If the user hovers the mouse over the first graph, the dates on each of the graphs should match in the information box.

**Comment by danielfdsilva** [comment]
@Catalina-Moller This should have been fixed with the new brush. Do you confirm?

**Comment by Catalina-Moller** [comment]
With the implementation of the new brush this issue has been solved! 
Evidednce: [Video](https://www.screencast.com/t/4o67Jv7mXQAx)
