### ISSUE TITLE
It is not possible to see the full date of the second edge of the range bar of a chart

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-ui#327]
### Description:
When the user selects one or more datasets to view the graphs it is not possible to see the full date of the second edge of the range bar of a graph.
 
**Evidence**: [Video](https://www.screencast.com/t/YC8rojHyl8)

### Acceptance Criteria:
When the user selects one or more datasets to view the graphs he should be able to see the full date on the second edge of the range bar of a graph.

**Comment by danielfdsilva** [comment]
This is no longer relevant.
The new brush no longer displays the date.
