### ISSUE TITLE
Recommendation: Delimit the time range that the user can enter to make an analysis.

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-ui#333]
### Description:
It is recommended to delimit the time range that the user can enter to make an analysis. 
For example, it is possible to enter the start date as 12/04/1298 and the end date as 05/07/6890 and it is possible to access the graphs between those dates. 

Please see attached evidence.

**Evidence**: [Video](https://www.screencast.com/t/QIynDw3duGs)

**Comment by danielfdsilva** [comment]
It's a good idea to set some sort of bounds, even if hardcoded.
For now there are no future datasets so 1900 - now should be good

**Comment by aboydnw** [comment]
Assuming we configure CMIP6 data, future dates might be needed soon.
https://github.com/NASA-IMPACT/delta-config/issues/153

**Comment by Catalina-Moller** [comment]
The date range change looks correctly implemented!
Currently the user can choose a date from 1900 to now and the future.
