### ISSUE TITLE
VEDA Dashboard Welcome Page Experience

### ISSUE THREAD

**Issue by michaelgsuttles** [NASA-IMPACT/veda-ui#338]
## Description
As a new user to the site, I want to understand the context of the site I've just arrived at

We've received some feedback from NASA stakeholders on the Dashboard. This falls into two buckets:
1. First time users might need more context
2. We should give credit to all the open-source libraries and tools that made the VEDA Dashboard possible

Acceptance criteria:

- [ ] Given I am visiting the VEDA Dashboard, when I view the top-level Welcome page then I have some context on the VEDA Dashboard (potential text, if needed, is below)
- [ ] Given I am visiting the VEDA Dashboard, when I view the top-level Welcome page then I am able to quickly jump to thematic areas

### General Informational Content
Underneath the title text ("Welcome to VEDA Dashboard"), add the text "The Visualization, Exploration, and Data Analysis (VEDA) Dashboard is an interactive visual interface for storytelling using Earth science data" in a smaller font.

**Comment by j08lue** [comment]
Good call and first step towards more user onboarding, IMO.

Just a thought - I really like pages that tell me what I can do with the tool, rather than its functionality. But maybe that is just me. What I have in mind is something like this:

> Understand the world better - read interactive stories and explore the Earth science data in the Visualization, Exploration, and Data Analysis (VEDA) Dashboard.

**Comment by michaelgsuttles** [comment]
> Good call and first step towards more user onboarding, IMO.
> 
> Just a thought - I really like pages that tell me what I can do with the tool, rather than its functionality. But maybe that is just me. What I have in mind is something like this:
> 
> > Understand the world better - read interactive stories and explore the Earth science data in the Visualization, Exploration, and Data Analysis (VEDA) Dashboard.

This makes sense to me. Manil approved the initial text--maybe we should get his or Brian's sign off on this new text, too.

**Comment by michaelgsuttles** [comment]
No response from Manil or Brian--perhaps we should stick with the original text.

**Comment by aboydnw** [comment]
@ricardoduplos @faustoperez I updated this ticket to be slightly more generic. We can brainstorm on more ideas for what this welcome page can be long term (I can see some fun ideas coming here) but kept the AC simple for now.

**Comment by michaelgsuttles** [comment]
I love the text at the top of the new site! If we're sticking with our short-term solution and long-term solution, and adding the sentence above to the current site is not desirable/too time consuming, we can just change "Welcome to VEDA Dashboard" to "VEDA is NASA's open source earth science platform in the cloud"? Or a slightly shorter version? That way it will be live on the site in time for the conferences that Brian/Alexey are going to... plus it's only a 10 second change :)

**Comment by aboydnw** [comment]
@faustoperez @ricardoduplos we reviewed these wireframes briefly during the sync with IMPACT today. Overall, IMPACT thought it was a big improvement, so their reaction was positive.

Some of the feedback/discussion centered around a few points:
1. Brian likes the idea of a welcome tour. He cited Worldview as a a product that he thinks does this really well. It looks like a solution they've built for themselves. I imagine we would tackle this as a separate work item, at which time we can explore build vs buy decisions for that specific feature. I don't think we need to tackle this right now, just something Brian was flagging to investigate in the potentially near future.
2. Jonas asked if there was also an opportunity to call out some of the Data Services work. This could take the form of highlighting API documentation, including references to their work in the "VEDA serves a wide audience" section, or anything else you would suggest! Something to explore.
3. There was some conversation about how different personas might care about different things and want to jump to different pages from here. In my mind, maybe this is a case for moving the "VEDA serves a wide audience" section higher on the page, but I don't want us to overcomplicate things at this point. In my opinion, we can tackle the "different user groups want to quickly access different features" later.

To @michaelgsuttles 's comment, to the extent we can build this iteratively and release to production, we should. We don't need to worry about this ticket for the conference next week. Let's focus our development and deployment energy on the time-series analysis functionality (cc @danielfdsilva )
There is a conference January 8-12 (AMS) that it would be more important to have a Welcome Page change in place for.

Hopefully this helps. Let me know if you want to discuss further.

**Comment by aboydnw** [comment]
@ricardoduplos @faustoperez Also, some questions to think about more for _thematic area_ home pages, in case you all are thinking of updating those to be similar to these wireframes:
1. If those thematic area home pages also have a top section of content, would that content be configurable? EIS expressed a desire to include figures/media similar to Discoveries. So I could see a group wanting to include images or a video on their home page.
2. Once a user in a thematic area, and now that we are dedicating more development to the Dashboard Welcome Page, would we want the logo in the top left of the nav to return them to the Dashboard Welcome Page instead of the thematic area welcome page?
3. I know we have talked about this in the past, but the convo came up again so I just want to keep the bug in the back of your brain. Do you see a need for a global "explorer" or list of datasets/discoveries? So, if a user didn't know what thematic area they wanted to go into. This probably relates more to #358 . Maybe a different way of asking is, is there any information or feedback that we should keep an eye out for that would indicate to you that we want to explore this type of functionality?

**Comment by michaelgsuttles** [comment]
Posting my thoughts on the redesign here for future reference.

https://docs.google.com/document/d/1-ZBpYO3Or19jC6RZgBOjwUcpOdw8ImtJXWbtu7L3lUQ/edit?usp=sharing

**Comment by aboydnw** [comment]
Suggested content based on https://deploy-preview-408--veda-ui.netlify.app/
@ricardoduplos @danielfdsilva let me know what you think. Brian is out this week, so it may be easiest for us to get content into the site and then get Manil or Jerika's eyes on it before pushing to production.

### Title
Welcome to VEDA Dashboard

### Subtitle/description
The Visualization, Exploration, and Data Analysis (VEDA) program presents NASA's open science platform for Earth Observation data in the cloud.

### Hero image
Maybe the VEDA logo? https://drive.google.com/file/d/1_zeFXO-HBFDKHvv80CYJEvHpcHET7Fcv/view?usp=share_link

### Section currently below featured discoveries
Starting with the header, currently "A scalable and interactive system for science data"
- This can stay as-is for now
- For the Subtitle, currently "VEDA stands for Visualization, Exploration, and Data Analysis." let's try changing to "Storing Earth data in the cloud enables many different ways of interacting with the data"

For text under "Comprehensive, open-source Earth Science data catalog"
- "Explore a wide range of Earth Observation datasets from NASA and other sources."
- Associated image: 
![image](https://user-images.githubusercontent.com/92742765/210454646-7ddb295e-b069-42ff-ae50-e54c37e43122.png)


For text under "Cloud-enabled scientific analysis"
- "Perform quick analysis without having to write code or download data"
- Associated image: 
![image](https://user-images.githubusercontent.com/92742765/210454832-e3a2e805-329d-48d4-bee7-46f53eb6bd82.png)


For text under "Science communication platform"
- "Share your discoveries with others through the VEDA Dashboard. Submit a Feedback form for more information."
- Associated image: 
![image](https://user-images.githubusercontent.com/92742765/210454933-76aeae91-0d2b-4e03-88e1-ae6db6c8a6b6.png)


### User Groups
I think the four user groups should be:
1. Earth Scientists
2. Academic Researchers
3. Policy Makers
4. Earth Observation Enthusiasts
This is different than how we talk about our user groups, but something like this probably makes more sense for an external audience.

Earth Scientists
- Text underneath: "Easily access high quality Earth data from NASA and its associated partners."
- Associated image: https://unsplash.com/photos/1lfI7wkGWZ4

Academic Researchers
- Text underneath: "Support your research efforts with an open source cloud-computing platform backed by NASA data."
- Associated image: https://unsplash.com/photos/a0TrZ9xqSDk

Policy Makers
- Text underneath: "Access and analyze data in real-time to inform decision making."
- Associated image: https://unsplash.com/photos/W_Qj9ycEBjQ

Earth Observation Enthusiasts:
- Text underneath: "Discover the latest work in Earth Observation and how that might impact climate change and other important initiatives."
- Associated image: https://unsplash.com/photos/83PSfuiPoEs

**Comment by michaelgsuttles** [comment]
Looks good. A couple of notes:

- Instead of "Welcome to VEDA Dashboard" we could put either "Welcome to
the VEDA Dashboard" or "Welcome to VEDA". Personally I think the second is
better since the site is less and less a "dashboard" in the traditional
sense, but this is a larger conversation!
- I think "Academic Researchers" is an improvement over "Advanced
Researchers."
- I don't believe Policy Makers were one of our main intended
audiences--they were listed as a secondary audience, IIRC (Correct me if
I'm wrong; I can't locate that slide deck). Can either remove or change to
something else. Same went for journalists, as I recall.
- I liked having a "public" option because it makes it clear that this site
is for everyone, not just "Earth Observation Enthusiasts." The public has
been a clear audience from the beginning. Can get Brian's feedback on this
when he comes back if need be.

**Comment by michaelgsuttles** [comment]
PS no idea why the formatting above got messed up... Sorry!

**Comment by michaelgsuttles** [comment]
One more thought--is the VEDA logo @aboydnw mentioned above the "official" logo for VEDA? Might the book icon be a bit confusing for a site focused on earth observation data? I suppose one could explain it as being the "data catalog"--but that is only one section of the site. Just some thoughts before we think about putting it on the site publicly. I seem to remember mention of the Hindu Vedas at some point and we want to steer far clear of religion on a USG site ;)

cc: @ricardoduplos @faustoperez @danielfdsilva

**Comment by aboydnw** [comment]
All of the official VEDA logos can be found here: https://drive.google.com/drive/folders/10I7VcxY16OKW-Bp5MxC2etsM0Tdv-r4x?usp=sharing

TBD if we include in the hero

**Comment by michaelgsuttles** [comment]
Thanks, @aboydnw. Those look like different sizes of the same logo, along with a LGBT pride version of it. Definitely think we should think carefully about putting it on our site for the reasons I outlined above. Certainly no rush--easy to add a logo later when we have more than two days before a mandatory push to prod! :)

**Comment by ricardoduplos** [comment]
Thank you all for the feedback! I guess we are still missing some paragraphs here:

<img width="925" alt="Screenshot 2023-01-05 at 15 17 06" src="https://user-images.githubusercontent.com/1016701/210815652-933f3f83-9e45-4866-8e1f-b0ae4d320741.png">

@aboydnw is this still something you can look into? Thanks!

**Comment by michaelgsuttles** [comment]
@ricardoduplos @danielfdsilva I spoke to Manil and he asked us to remove the "Policy Makers" part. He is thinking about the best language to use for "Earth Observation Enthusiasts." (cross post from slack) :)

**Comment by michaelgsuttles** [comment]
> For text under "Comprehensive, open-source Earth Science data catalog"
> 
> * "Explore a wide range of Earth Observation datasets from NASA and other sources."



> Thank you all for the feedback! I guess we are still missing some paragraphs here:
> 
> <img alt="Screenshot 2023-01-05 at 15 17 06" width="925" src="https://user-images.githubusercontent.com/1016701/210815652-933f3f83-9e45-4866-8e1f-b0ae4d320741.png">
> 
> @aboydnw is this still something you can look into? Thanks!

Hey @ricardoduplos -- it looks like @aboydnw already included the text above. Example:

> "For text under "Comprehensive, open-source Earth Science data catalog"
> 
> "Explore a wide range of Earth Observation datasets from NASA and other sources."

**Comment by aboydnw** [comment]
@ricardoduplos @michaelgsuttles I updated the comment above to remove Policy Makers.

**Comment by michaelgsuttles** [comment]
@aboydnw  I see you replaced "Policy Makers" with "Students." I have as our core user groups those listed below, which does not include students. Is there another place where students are indicated as a core audience?

<img width="993" alt="image" src="https://user-images.githubusercontent.com/7217855/210842109-050dc2cb-d3b3-47d6-8d66-065c02cf5e5c.png">

cc: @ricardoduplos @danielfdsilva 

-------------------

Also, wanted to list out things that still need to be done on the site. I know you're aware of this but figured it helps to have it all in one place.

- "Welcome to VEDA UI" should be "Welcome to VEDA"
- "VEDA UI is NASA's open-source Earth Science platform in the cloud" should remove "UI". @danielfdsilva  also mentioned moving the abbreviation to this section, so perhaps "VEDA (Visualization, Exploration, and Data Analysis) is NASA's open-source Earth Science platform in the cloud."
- Thematic areas missing, and there is still "Void area"
- Featured discoveries missing text. @aboydnw are you coming up with this text or is it from somewhere else?
- Remove "VEDA stands for Visualization, Exploration, and Data Analysis."
- The following 3 sections should have a link to the associated page--but maybe this is not possible?

Since we'd like to give NASA as much time as possible to review the completed page, perhaps @nerik or @hanbyul-here can help, as well? I leave it up to you guys to coordinate!

**Comment by aboydnw** [comment]
> "Welcome to VEDA UI" should be "Welcome to VEDA"

- this will change automatically when it gets deployed. see Daniel's comment [here](https://developmentseed.slack.com/archives/C0136FF156X/p1672831128004249?thread_ts=1672772691.351499&cid=C0136FF156X)

> "VEDA UI is NASA's open-source Earth Science platform in the cloud" should remove "UI". @danielfdsilva also mentioned moving the abbreviation to this section, so perhaps "VEDA (Visualization, Exploration, and Data Analysis) is NASA's open-source Earth Science platform in the cloud."
- this is covered in my comment about content above

> Thematic areas missing, and there is still "Void area"
- this will change automatically when it gets deployed

> Featured discoveries missing text. @aboydnw are you coming up with this text or is it from somewhere else?
- this will change automatically when it gets deployed

> Remove "VEDA stands for Visualization, Exploration, and Data Analysis."
- this is covered in my content comment above

> The following 3 sections should have a link to the associated page--but maybe this is not possible?
- Not exactly sure which 3 sections you are referencing here, but I don't think this is the goal of this ticket

**Comment by michaelgsuttles** [comment]
Thanks, @aboydnw. Some of the text I referenced above just changed so it's not dependent on being deployed.

Based on the new and improved site that @danielfdsilva just sent--looking great! Just a few small things:

- Change "Welcome to VEDA Dashboard" to "Welcome to the VEDA Dashboard". We can have a longer discussion later about whether to call it a dashboard--now is not the time. :)
- "VEDA Dashboard is NASA's open-source Earth Science platform in the cloud." should be ""VEDA (Visualization, Exploration, and Data Analysis) is NASA's open-source Earth Science platform in the cloud."
- Sounds like the thematic areas will be added in production, so this is good?
- Featured discoveries will be automatically pulled in when deployed?
- Remove "VEDA stands for Visualization, Exploration, and Data Analysis."
- The following 3 sections should have a link to the associated page--but maybe this is not possible? For example, "Share your discoveries with others through the VEDA Dashboard. Submit a Feedback form for more information." can have a link to the feedback form.

**Comment by michaelgsuttles** [comment]
@danielfdsilva @ricardoduplos
From Manil just now: please change "climate change" to "environmental change" at the bottom of the page.

Also, while the jury is still out on "Earth Observation Enthusiasts", should we change the capitalization to "Earth Observation enthusiasts" to match the other two?

**Comment by michaelgsuttles** [comment]
@danielfdsilva Per Brian, we should change "Earth Observation enthusiasts" to "Science enthusiasts" in our next push to production.

**Comment by danielfdsilva** [comment]
@aboydnw @michaelgsuttles Can we consider this completed, and any other needed changes will be addressed in #420?
