### ISSUE TITLE
Visualizing the VEDA vision

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#357]
## Description

Following up on the recent vision conversations, we would like to visualize a potential long-term vision of VEDA. This can take the shape of wireframes, miro boards, benchmarks from other tools, or other assets. 
Relevant vision docs:

- [FY23 Direction & Goals in Almanac](https://almanac.io/handbook/veda-product-development-documentation-I3UwKo/fy23-direction-goals-maNozOfxZ6jzBxwUClhYNzLQVbCJqQZx)
- [Vision exercise from PI planning in miro](https://miro.com/app/board/uXjVPRe30Hk=/?share_link_id=444427768932)
- [Spectrum exercise in miro](https://miro.com/app/board/uXjVPOsHc9o=/?share_link_id=86692999829)

**Comment by michaelgsuttles** [comment]
Look forward to making progress on the VEDA Vision! Still a few brainstorming sessions left to nail down the roadmap.

**Comment by aboydnw** [comment]
Marking as complete, as the v2 designs from Fausto and Ricardo accomplished this goal for the next 6-12 months of the Dashboard. We can revisit longer term visualizations as needed.
