### ISSUE TITLE
Propose ideas to encourage using multiple features

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#358]
## Description

Relating to [PI Objective #3](https://github.com/NASA-IMPACT/veda-architecture/issues/126), and in particular [Release 2.1](https://almanac.io/handbook/veda-product-development-documentation-I3UwKo/2-0-increased-scientist-capabilities-rs19WEKQfwBkh2ZCzxCtWhLWgihh83f9), the goal of this ticket is to propose some design solutions to the dashboard to encourage users to interact with data available through VEDA in more than one modality. Currently available:
1. Discoveries/stories
2. Dataset exploration
3. Time-series analysis
4. Analytics Platform
5. (stretch) VEDA APIs

Feel free to propose multiple options, of varying levels of effort. Then, as a team & stakeholder group, we can decide on the best path forward.

**Comment by aboydnw** [comment]
Related ticket: https://github.com/NASA-IMPACT/veda-ui/issues/321

**Comment by faustoperez** [comment]
Also related ticket: #116
