### ISSUE TITLE
Open-Source Acknowledgements

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#369]
## Description
After the NASA HQ demo in October, there was feedback that open-source is a big part of VEDA. They are hoping we can make this more prominent in the dashboard. The original idea was to put this information on the About page, but we have some flexibility if there is a better way.

Acceptance criteria:

- [x] Given I am visiting the VEDA Dashboard, when I view the overall About page then I can see very clearly that VEDA is an open source tool and can see which other open source tools are used

**Comment by danielfdsilva** [comment]
I propose we add something like the following after the current text on the [about page](https://visex.netlify.app/about).


## Commitment to Open Source

The NASA open-source science initiative believes commitment to open source is an important aspect of creating and maintaining high-quality software. Open source allows for collaboration and transparency, which can lead to better solutions and more robust code.
The different repositories of the VEDA project, from the [web application](https://github.com/NASA-IMPACT/veda-ui), to the [content storage](https://github.com/NASA-IMPACT/veda-config) and even the [data pipelines](https://github.com/NASA-IMPACT/veda-data-pipelines), are all open and can be freely browsed. Furthermore this project would not be possible without many other openly maintained projects.


@aboydnw @michaelgsuttles Perhaps some phrasing improvements, if you have ideas?

**Comment by michaelgsuttles** [comment]
Looks great to me! When I see "many other openly maintained projects" I can almost guarantee NASA is going to ask "which ones?" Should we name a few?

**Comment by danielfdsilva** [comment]
@michaelgsuttles ...many other openly maintained projects like [React](https://github.com/facebook/react), [MapboxGl](https://github.com/mapbox/mapbox-gl-js), [Parcel](https://github.com/parcel-bundler/parcel), [STAC](https://github.com/radiantearth/stac-api-spec), and [TiTiler](https://github.com/developmentseed/titiler) to name a few.

**Comment by michaelgsuttles** [comment]
Love it! :)

**Comment by aboydnw** [comment]
Looks good. Two minor notes:
- After "The different repositories of the VEDA project," I would simply list out the repos. Maybe even use bullets.
- Might also be worth being a little more direct about people going to the repos for more info. Something like, "For more information, join the conversation in our openly maintained repositories."

**Comment by danielfdsilva** [comment]
@aboydnw Thank you for the improvements :) Feel free to suggest additional changes directly in the PR https://github.com/NASA-IMPACT/veda-config/pull/163
