### ISSUE TITLE
Caldor Fire dataset fails to load

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#390]
## Description
Attempting to explore the caldor fire dataset in the EIS thematic area, both layers give me the following error message
![image](https://user-images.githubusercontent.com/92742765/207993175-61920092-c78e-45f1-baa9-7b97319d71b7.png)

**Comment by vincentsarago** [comment]
Oh no I broke something 😭 

we deployed a new version earlier today https://github.com/NASA-IMPACT/veda-features-api/releases/tag/v0.2.4

@aboydnw can you tell me what is the query and the error message ?

**Comment by aboydnw** [comment]
This is what I see in the console logs when I try to load one of these layers, just a simple "Aborted" 😬 
![image](https://user-images.githubusercontent.com/92742765/207994603-05ca86c8-9c96-45a4-8cf5-db8ea93e4a65.png)

**Comment by aboydnw** [comment]
Search id: ee1f6d1ee05f124a549eb00f50e1dbbe
If that helps!

![image](https://user-images.githubusercontent.com/92742765/207994833-8181a2bd-47cb-412f-b9a2-7083d7430cb3.png)

**Comment by vincentsarago** [comment]
😅 `raster` ... so it's not related to my deploy this morning 

I do see the same error message but the data loads 🤷 
<img width="1495" alt="Screen Shot 2022-12-16 at 1 30 14 AM" src="https://user-images.githubusercontent.com/10407788/207994848-5b77a9bf-6a38-4051-a21b-938d6e58aa4b.png">

**Comment by aboydnw** [comment]
Ahhh interesting! It does load for me too, if I zoom in a bit. At that zoom level it still wants to just be a marker. I just assumed something was wrong because when I load the dataset it automatically zooms me in on the marker so I assumed it would go far enough to show the data! 

However, another interesting thing is even after I zoom in and get the data to load, the error message still pops up for me! Even after I refresh at the correct zoom level, so I don't think it's just the error message sticking around. Weird...
![image](https://user-images.githubusercontent.com/92742765/207996313-fff3ac93-3571-4dc0-89ee-8d5fe94568eb.png)

**Comment by aboydnw** [comment]
Anyways, doesn't seem like you broke anything @vincentsarago  😅 especially since I've only been able to reproduce this for this dataset.

**Comment by aboydnw** [comment]
Closing in favor of #389
