### ISSUE TITLE
An analysis graph is generated by selecting a part of the map that does not have a layer, after selecting one that does have a layer. 

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-ui#396]
### Description:
When the user generates an analysis and then modifies the area of the map by selecting an area that is not covered by a layer, he gets the graph he saw before making the modification. 

**Steps to reproduce it:** 
1. The user selects a part of the map that has a covering layer, a date range and a layer. 
2. Presses the "Generate" button.
3. The analysis graph is generated. 
4. Presses the "Refine" button.
5. The edit page is displayed and the user selects a part of the map that does not have a layer covering it.
6. Click the "Generate" button.
7. The same graph of the analysis that the user saw previously (point 3.) is generated.  

### Acceptance criteria:
When the user selects a portion of the map that is not covered by any layers, the user should not be able to see a generated graph. 
The user should either see an appropriate error message or simply not be able to select a layer in a portion of space that does not have any. 

To generate the evidence we used the Analysis section of the Agriculture area and generated the graphs with the "GEOGLAM Crop Conditions" dataset.

EVIDENCE: [Video ](https://www.screencast.com/t/uN5DbC6BLY)

**Comment by danielfdsilva** [comment]
This is a data api problem. The api returns the dataset when making a request in the analysis define page, but it shouldn't.
Assuming this will be addressed once the [collection search endpoint](https://github.com/NASA-IMPACT/veda-backend/issues/131) is implemented.

cc @j08lue @anayeaye

**Comment by j08lue** [comment]
Valid UX improvement opportunity for the current Analysis feature. This was also touched upon in the context of this ticket:

- https://github.com/NASA-IMPACT/veda-ui/issues/658

But this flow is going away in the new E&A user flow, where the user selects datasets/collections first and can see on map and time line whether the collection has data in their time range / area of interest.

So I guess we can close this - generously as completed.
