### ISSUE TITLE
When a chart has only one date with data, the points are shown on one axis. 

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-ui#400]
Description: 
When a chart has only one date with data, the points are displayed on one axis and make it difficult to view the data. 

It is recommended to leave a space or find a way to make them more clearly visible. 

![image](https://user-images.githubusercontent.com/111894012/208931788-fdf4a71b-7b8a-4a83-8792-833aebdfdf49.png)

**Comment by danielfdsilva** [comment]
When there's only 1 data point it should be shown in the middle

**Comment by nerik** [comment]
@Catalina-Moller I'm not exactly sure how to approach this as the position of the points depends on how the brush (the gray UI element below) is positioned. Also, the points should be visible on the brush, in your screenshot they are not and I'm not able to reproduce.
Would you mind giving me more context on how you got this result? (the URL of the dashboard would be useful). Thanks :)
