### ISSUE TITLE
Not all avaliable datasets for a given AOI and date are shown on the analysis definition page

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-ui#403]
### Description: 
The OMI_trno2 Annual and Sulfur Dioxide layers of the Air Quality area have an unexpected behavior when choosing the dates to generate the graphs in the analysis page. 

When choosing as end date of the analysis a date with month 01 or 02 (in some cases) the option to choose the OMI_trno2 Annual and Sulfur Dioxide layers to generate the analysis is shown. 
But when entering a date that does not have the month 01 or 02 (in some cases) does not show the option to choose the layers OMI_trno2 Annual and Sulfur Dioxide to generate the analysis, knowing that between the dates entered there are layers that cover the map. 
These two layers are annual, to keep in mind. 

I attach a [VIDEO ](https://www.screencast.com/t/JXIRKRcQ2)with the evidence to better understand the issue. 

### Acceptance criteria: 
When the user enters an start date and an end date the user must be able to choose all the layers that cover the portion of the map between the selected dates.

**Comment by danielfdsilva** [comment]
This is happening because of how requests are implemented due to a lack of api support.
See https://github.com/NASA-IMPACT/veda-backend/issues/131#issuecomment-1326475187

**Comment by j08lue** [comment]
Addressed in #534 - perhaps still only workaround, but closing this here as duplicate.
