### ISSUE TITLE
AoI Selection via Custom-defined polygons 

### ISSUE THREAD

**Issue by nerik** [NASA-IMPACT/veda-ui#404]
Adds support for upload of a custom AoI polygon. Currently limited to single polygon shapefile or geojson files.

**Comment by Catalina-Moller** [comment]
Hi @nerik, I'm not quite clear on what I should be testing in this task. Could you help me with a bit more context? Thanks!

**Comment by danielfdsilva** [comment]
Basic behavior:
- Possibility to upload a geojson or shapefile to define an AOI
- If the given file is invalid display and error message
- If the given file has more than 1 polygon, use the first one and warn the user
- If the uploaded polygon is very complex, simplify it and warn the user

The uploaded polygon should be displayed on the map.
The [test-files.zip](https://github.com/NASA-IMPACT/veda-ui/files/10449345/test-files.zip) contains some files that can be used to test the behavior. https://geojson.io can be used to generate additional test data.

cc @Catalina-Moller

**Comment by Catalina-Moller** [comment]
[descargar (7).zip](https://github.com/NASA-IMPACT/veda-ui/files/10457915/descargar.7.zip)
This is the zip with the Shapefile format that I used for the first observation, maybe it can be useful for you :)
