### ISSUE TITLE
AoI via predefined generic boundaries

### ISSUE THREAD

**Issue by nerik** [NASA-IMPACT/veda-ui#405]
## Description
Allowing users to easily select preset values that make sense based on the geographic region they are interested in (aka states in US vs provinces in Canada)

Relevant feedback from #456 : 

> A list of predefined AOIs would be useful (natural earth polygons was given as example, but not all scientists rely on political boundaries)

This sounds similar to #442 

More discussion on political boundaries:
Not being flooded with a list of all potential political boundaries or other presets (aka if we gave every state or even every country in the world as a preset)

Some potential types that I see referenced above:

- US state, county, or municipality
- Country/national boundaries
- Continent and/or ocean
- Fire management districts

Alexey raised a good concern of political boundaries in potentially contentious areas (Western Sahara, as an example). At this point, I don't think we should worry too much about this, and just select some standard set of political boundaries out there.

## Acceptance Criteria
1. Users can select pre-defined AOIs within the analysis page workflow instead of manually creating an AOI

**Comment by aboydnw** [comment]
We are going to wait on this ticket since we have the shapefile upload which allows users to define boundaries. This might improve that workflow, but we want to wait for feedback and usage on the shapefile upload first before tackling this problem.

**Comment by aboydnw** [comment]
@ricardoduplos @nerik is this significantly different than "reference layers" that we have been discussing in #359 ? Or is there some overlap between a reference layer and these generic predefined bounds?

**Comment by nerik** [comment]
@aboydnw @ricardoduplos We could definitely use the same data. A layer of say, countries' boundaries, could serve both as:
- a reference layer visible in the explore section's map
- a layer from which to pick polygon(s) to define an AoI
