### ISSUE TITLE
AoIs for Dataset-specific boundaries

### ISSUE THREAD

**Issue by nerik** [NASA-IMPACT/veda-ui#406]
## Description
Dataset-specific boundaries such as [NIFC Predictive Service Areas](https://data-nifc.opendata.arcgis.com/maps/e580f3fd4d644366b121676714d69c2d) or [Air Quality Management Districts](https://ww2.arb.ca.gov/california-map-local-air-district-websites)

Split from #212 

The intent of this ticket would be to only show users options for pre-defined boundaries based on the dataset(s) they are analyzing, to shorten the list of potential AOIs

**Comment by aboydnw** [comment]
Would require a redesign of the analysis workflow, putting off for now, depending on larger redesign of the dashboard
