### ISSUE TITLE
Show dots only on hover

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#413]
Dots are great when the data is sparse, but they are not helpful when dense. (and possibly make the chart slow.) 
Maybe we can render the dots depending on the density of the data? 

<img width="631" alt="Screen Shot 2023-01-05 at 1 43 55 PM" src="https://user-images.githubusercontent.com/4583806/210857140-096e35e2-c81a-4193-a67a-72f072a6bc4f.png">

**Comment by hanbyul-here** [comment]
🤔 But then.. the dots are very useful for seeing the gap in the data.  (like Mean CO2 example below) 

![Screen Shot 2023-01-19 at 2 00 10 PM](https://user-images.githubusercontent.com/4583806/213535719-82b6f560-a7cf-465f-b686-0ff5e74e4918.png)

Can I get other wise people's insights on this? @faustoperez @ricardoduplos ? 

1. Should we render dots at all? 
2. If so, should we always render dots?
3. If not, when to render dots vs. not?  

*Things to concern: dot - is one more SVG to render, so when there are 500 data points (and x4 data attributes), there are 2000 more svgs to render for a document. You can see Brush works more smoothly with fewer attributes through the interactive legend on this page - it works even more smoothly with no dots at all (https://www.earthdata.nasa.gov/dashboard/air-quality/analysis/results?start=2019-09-10T00%3A00%3A00.000Z&end=2023-01-01T00%3A00%3A00.000Z&datasetsLayers=no2-monthly%7Cco2-mean&aoi=frslU_rvzG_%7BllBb~%7DAoihC%60t_c%40ngf%7D%40vvh%7C%40).

**Comment by michaelgsuttles** [comment]
@hanbyul-here @faustoperez @ricardoduplos Would it be helpful to get additional feedback from scientists? If so, we can ask them async in the #eis-veda channel since there are a few of them there.

**Comment by faustoperez** [comment]
Hi Hanbyul, Ricardo and I had a chat about the dots, here are the action points:

- Make the dots solid and smaller (3x3 px maybe?), like [this chart](https://ourworldindata.org/explorers/global-food?tab=chart&facet=none&hideControls=true&Food=Total&Metric=Food+available+for+consumption&Per+Capita=false&Unit=Kilocalories+per+day&country=OWID_WRL~South+America~North+America~Europe~Africa~Asia)
- Remove the dots at the highest zoom level but keep showing them on hover
- Conditionally render the dots: maybe have a rule to select when/if to show them depending on the density and the chart zoom level -- this will need some thinking, we can discuss this afternoon during one of out multiple meetings :)

Hope this helps!

**Comment by hanbyul-here** [comment]
I changed the ticket title to capture the amount of work that can be done without further discussion. I opened the new one to keep the conversation going: veda-ui #441
