### ISSUE TITLE
Weird menu behaviour when viewport width > 1216px and <= 1230px 

### ISSUE THREAD

**Issue by nerik** [NASA-IMPACT/veda-ui#416]
In every page, menu doesn't open and a gray gradient is appearing:

![Screenshot 2023-01-06 at 11 59 52](https://user-images.githubusercontent.com/1583415/210999498-f51cd057-a6d0-4722-ad89-1549fc4096b4.png)

**Comment by danielfdsilva** [comment]
@nerik This sometimes happens when you're changing the viewport width (and with the live reload it seems?!). If you enter the page at these sizes it shows up well.
Is there a way to consistently get this?

**Comment by nerik** [comment]
Indeed, it doesn't happen in the build. I'd say not worth investigating. Closing.
