### ISSUE TITLE
Reorder dashboard welcome page

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#417]
We got some feedback from Brian and Suresh that the thematic area slider might be better served after some of the explanatory text on the dashboard welcome page. We'd like to explore this option as a followup to the recent push to production.

[Brian's Slack thread](https://developmentseed.slack.com/archives/C02FMLEV8ET/p1673029062056339?thread_ts=1673021104.783619&cid=C02FMLEV8ET)

**Comment by aboydnw** [comment]
@ricardoduplos @hanbyul-here @danielfdsilva  I made this ticket for us to followup on next week. Brian agreed this feedback should not stop the push to production this week.

**Comment by aboydnw** [comment]
An additional thought, feel free to push back on this feedback if there is a design reason for doing so. From my side, I think there is more important work we could be doing so if it's a hassle to do and/or doesn't make good design sense then I'd vote we hold off for now.

**Comment by danielfdsilva** [comment]
@aboydnw This was simple to do, and was done in the https://github.com/NASA-IMPACT/veda-ui/pull/420 PR. You can use the preview and see how it looks like. Being a temporary solution I'd say it's ok

**Comment by Catalina-Moller** [comment]
In the Deploy Preview of the PR discussed in the previous message it is possible to see correctly the slider of the thematic areas after the explanatory text on the dashboard welcome page!
