### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#425]
## Description

I pulled up the [quickstart guide](https://developers.google.com/tag-platform/tag-manager/web) for google tag manager. Comparing to the original site tag in #209  , it LOOKS different. If so, I'd love to install google tag manager as well. it would allow us to get much more granular with our analytics. So we can understand specific actions users are taking. Right now we are stuck at just “page view” and that level of specificity.

**Comment by aboydnw** [comment]
@hanbyul-here I moved this from slack to github. Curious to get your thoughts as a potential ticket for upcoming sprints.

**Comment by hanbyul-here** [comment]
Hi! I've never heard about Tag Manager. Do you know what kind of value this will bring to the product? Also, do you have specific things you want to discover through Google products? The installation looks easy, but I would like to know what values it brings and if the same thing can be achieved through GA.

**Comment by aboydnw** [comment]
My understanding is that, once it is setup, it allows us to track specific events, like button clicks, without needing a developer to tag each specific item. That I could monitor these events all through GTM without coding. GTM would then send these events to GA where I could make reports. 

So right now, I can generate a report on the number of page views. With GTM, I could generate a report on the number of page views, what those people did on the screen, which button they clicked, and to which page they went next.
