### ISSUE TITLE
Multiple Polygons - Polygon selection

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#426]
Split from #423 to address selecting polygons from an uploaded file.

## Description

As a user I want to select multiple polygons for analysis so that I can conduct the most accurate analysis possible

Currently, you can only select one polygon in the analysis page. This came up during user research in a couple different ways.

1. Analyzing islands (this feels like the most straightforward use case)
2. Uploading a shapefile that contains all the watersheds in North America. This feels like a slightly different use case, because I would assume that scientists then want to narrow down their selection to 1 or 2 watersheds. They just have a shapefile that contains all of them, because that's the format that USDA (or similar agency) publishes

There are probably other use cases, but those two came up during user research this week.

## Acceptance Criteria

- [ ] Given I am creating a search on the analysis page, when I upload a shapefile with multiple polygons then those polygons are represented on the map and can be selected/removed

**Comment by j08lue** [comment]
I think this has been implemented a while ago:


![Image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/25240a08-41c1-4dee-b22c-0bfc7e8d5ee6)
