### ISSUE TITLE
Analysis page missing the 'from date'

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#431]
I see this bug only when 'from date' is 1st Jan (whichever year).

ex. https://www.earthdata.nasa.gov/dashboard/air-quality/analysis/results?start=2020-01-01T00%3A00%3A00.000Z&end=2020-01-08T00%3A00%3A00.000Z&datasetsLayers=co2-mean&aoi=k%60%60Wgl~sAw%7CxeAwf%7BtAsp_uBxwvgBv%7CxeAbapeB

![Screen Shot 2023-01-19 at 10 53 51 AM](https://user-images.githubusercontent.com/4583806/213490363-c14c3d2d-22c9-4460-b3d5-f38d269fd174.png)

![Screen Shot 2023-01-19 at 10 56 48 AM](https://user-images.githubusercontent.com/4583806/213490489-dca15d60-ef55-4427-9e46-2aec9be3cbef.png)

**Comment by danielfdsilva** [comment]
The date format is different depending on the date range. When in the same month it will show the days with a dash. In this case `Jan 01-08, 2019`.

The different formats are:
- `Jan 01-08, 2019` - Same month
- `Jan 01 - Feb 08, 2019` - Same year
- `Jan 01, 2019 to Jan 01, 2020` - Different years

@hanbyul-here perhaps the "from" word is misleading.

**Comment by hanbyul-here** [comment]
Oh I see. I mistook how the format works. I wonder it will be better to just consolidate from - to - ?  Anyway, it is not a bug so  I will close the ticket.
