### ISSUE TITLE
In the analysis page when the shape boundary is removed the drawing mode is deactivated and it has to be selected again

### ISSUE THREAD

**Issue by karitotp** [NASA-IMPACT/veda-ui#439]
**Description:**

From a feedback of Danny. Browser: Brave 1.47.171 , Chromium: 109.0.5414.87 arm64
Drawing a selection on the map, when you double click on the same location of the first or second node of the shape, or when removing the drawn area, the edition mode is deactivated and it says “No area defined”.

**Steps to reproduce:**
- Click on the map to set the first shape boundary location
- Immediately click on the same location, which removes the shape
or
- Click on the map and draw a shape
- Click the trash icon to delete the shape

**Evidence:**

https://user-images.githubusercontent.com/11504548/214412239-015404e0-41b4-4caf-9838-0e21de9a9c11.mp4

**Expected:** 
When the shape boundary is removed, it should change back to the drawing tool.

**Comment by danielfdsilva** [comment]
This is no longer an issue with the multipolygon AOI
