### ISSUE TITLE
Add support for reference information on map (coastlines, place labels)

### ISSUE THREAD

**Issue by michaelgsuttles** [NASA-IMPACT/veda-ui#442]

**Comment by danielfdsilva** [comment]
To implement this we need:

- [ ] Add the needed data to the style (via mapbox studio)
- [ ] Create the data selector control for the map (Use projection selector for inspiration)

**Comment by nerik** [comment]
I figure this should be added to the map in the dataset exploration section, alongside other map controls:

<img width="559" alt="Screenshot 2023-02-06 at 11 01 57" src="https://user-images.githubusercontent.com/1583415/216942546-00cfb72d-d976-479a-9299-7d60b6ee7662.png">

Overall design questions:
- [ ] Is there a risk of confusion with the projection selector button? This planet icon pretty much already looks like a "basemap selector" icon, but maybe that's just me
- [ ] What are the context layers we want to add?
  - [ ] Place labels:
    - [ ] Should the layer mentioned above appear on top of the raster layer(s) (I'm guessing yes, same as the existing boundaries)
    - [ ] Labels will require some styling in Mapbox Studio. Who's owning that? (I can, but we'd get better results from a designer :)
  - [ ] Do we want to add administrative boundaries beyond countries/adm0? (I reckon adm1 would be useful at the very least for US States)
  - [ ] Add a graticules layer? (would also need design in MB Studio)
  - [ ] Any use for a basic topography + bathymetry basemap?
    - [ ] For UI considerations: take into account that this would _replace_ the satellite basemap, while the labels or graticules would be _added on top_ of the satellite basemap.
- [ ] Should we also add this to the Analysis AoI selection map?
<img width="291" alt="Screenshot 2023-02-06 at 11 14 28" src="https://user-images.githubusercontent.com/1583415/216945291-b2f79404-08ba-46b4-929e-eadeddd0a836.png">

As usual, I suggest we gather to define what's a good MVP for a first iteration and start building.

**Comment by ricardoduplos** [comment]
Capturing the solution @nerik and I discussed for the MVP:

- The previous "Projections" action will become "Map Options", keeping the Globe icon for the button, but its scroll-able dropdown will be redesigned to harbor three groups of map-related options:
  - Style (exclusive option selection list):
    - Default light
    - Default dark
    - Satellite
  - Details (On/off togglable options list):
    - Labels
    - Boundaries
    - ...
  - Projection (exclusive option selection list)
    - Albers
    - Mercator
    - Globe
    - ...
- Labels will be slightly styled to match the app typeface family ("Open Sans");
- We can add graticules layer togglable option under "Details" at a future point;
- It would be nice to include these Map Options on the analysis map as well, yes.

---

Some wireframes to illustrate this direction can be seen here:

- https://www.figma.com/file/SA0u0sVdw5vM7g9ulV5Xgw/Wireframes?node-id=2992%3A42725&t=qjVLwwVjQDUMFiYF-1

**Comment by aboydnw** [comment]
Is this related to #405 ?

**Comment by nerik** [comment]
@aboydnw Same data, different feature (this one's only for reference, not for creating AoIs)

**Comment by danielfdsilva** [comment]
@nerik With #458 merged, should we consider this done? Is there some other things we want to track from here that merit a new issue?

**Comment by nerik** [comment]
@danielfdsilva Nope, marking this as done. Thanks for flagging.
