### ISSUE TITLE
Issues when using multipolygons in the analysis section

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-ui#444]
1. When a user clicks on the selected shape a trash button appears to delete it, if the user moves the shape or scrolls down the trash button remains in place and continues to be seen outside the shape. 

Video evidence: https://app.screencast.com/qbuKM4FBHyu2w

2. When a user selects an area of the map with a shape it updates the message of how many square kilometers are being covered by the shape. 
But when the user selects two or more shapes that overlap or overlap in one part, the message of how many square kilometers are being covered by all the shapes adds the area covered by each shape but does not subtract the overlapping spaces.  

Video evidence: https://app.screencast.com/AJy2mFNMxTrQj

**Comment by danielfdsilva** [comment]
This was completed in #438
