### ISSUE TITLE
Improve/rethink geometry simplification

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#448]
From https://github.com/NASA-IMPACT/veda-ui/pull/438

> Geometry simplification is not easy, maybe we should think about different approaches like using bboxes for complicated polygons. I don't think that detailed polygons are necessary for this type of analysis as the data may not even have the needed resolution, but this is something that we should confirm.

[mapshaper](https://github.com/mbloch/mapshaper) could be an option to simplify geometries, but seems to be a CLI tool. Not sure about browser support.

**Comment by danielfdsilva** [comment]
To research:

- [ ] What level of geometry detail do users need
- [ ] What options are available for geometry simplification

**Comment by aboydnw** [comment]
Outdated with updates made to E&A
