### ISSUE TITLE
can't use markdown footnote on mdx

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#449]
MDX seems to offer its wrapper for the footnote, which breaks the container style of the page.
The code  below
```mdx
...
    [Explore How COVID-19 Is Affecting Earth's Climate](/covid19/discoveries/climate/climate-change-and-covid "Explore How COVID-19 Is Affecting Earth's Climate")[^1]
  </Prose>
</Block>


<Block type="wide">
  <Prose>
  [^1]: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus nisi, eleifend quis blandit sed, efficitur id sem. Nullam a orci odio. In vel nulla sit amet dolor egestas tempor. Nullam viverra, purus vel egestas cursus, risus turpis condimentum risus, sed consequat nisl lectus non arcu. Phasellus eu purus non augue faucibus dapibus eget vitae nisi. Sed quam ipsum, malesuada ut porta ac, sagittis rhoncus sem. Maecenas scelerisque auctor nisl eget lobortis. Etiam orci felis, euismod quis mattis non, pulvinar at nulla. Fusce at purus vel ex condimentum porta. Sed tem
  </Prose>
</Block>
```
will result in a stretched container like the one below. 

![Screen Shot 2023-02-01 at 2 33 36 PM](https://user-images.githubusercontent.com/4583806/216144995-f57c5ba0-94e6-4e4b-8b5b-3287ffceec15.png)

**Comment by stephenkilbourn** [comment]
This may have been resolved somewhere else. The overflow is no longer occurring if I try to reproduce:
<img width="1790" alt="Screenshot 2023-12-26 at 12 31 31 PM" src="https://github.com/NASA-IMPACT/veda-ui/assets/7388976/08aa7242-7adb-4c14-9a87-7e45f1b542d2">

vs without the footnote:
<img width="1791" alt="Screenshot 2023-12-26 at 12 35 09 PM" src="https://github.com/NASA-IMPACT/veda-ui/assets/7388976/4affd369-97a3-498a-a404-f598a20a121b">

**Comment by aboydnw** [comment]
I'm going to close assuming it was completed. Thanks @stephenkilbourn
