### ISSUE TITLE
Revise Notebook connect

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#450]
The initial solution developed as part of https://github.com/NASA-IMPACT/veda-ui/pull/446 does not clearly address the problem. While the PR was merged with the initial approach we should continue to iterate.

Original issue: https://github.com/NASA-IMPACT/veda-architecture/issues/174

From PR https://github.com/NASA-IMPACT/veda-ui/pull/446:

We are looking to have a consistent language for this feature so that it can be present throughout the application and can then be easily included in the [updated dashboard vision](https://docs.google.com/document/d/1UT1bK7wTivPvSsTGP5073PISwYjbSsSTrhg6NizmnLM/edit) (Dashboard V1).

So far we've identified essentially 3 different contexts where this notebook connect widget would appear:
- Dataset overview and explore
- Long form content (e.g. Discoveries) in the form of a callout
- Long form media content (charts, maps, figures)

The way the feature presents itself should be fairly similar as to be recognisable by the user. The current approach relied on having a trigger button that displays a modal, however this button is not visible or prominent enough being confused with map controls.

Some points from a discussion on this:
- Moving the list of links to the side panel leads to a solution that does not scale, nor works for the Dashboard V1.
- Having the button on top of the media content (charts, maps, etc) has the same issue of lack of clarity.
- Simply changing the color of the button can clash with the visual language of the dashboard.

A global cohesive solution has us going back to the drawing board.

**Comment by aboydnw** [comment]
I think this ticket is stale now, can reopen later if needed
