### ISSUE TITLE
Error displaying past analysis thumbnails

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#455]
From https://github.com/NASA-IMPACT/veda-config/pull/192#issuecomment-1416102928

> The thumbnail image for the past analyses does not load in all the cases; according to what I tested, happens when it is a complex geometry, or when there are a lot of polygons in different areas 
![Screenshot from 2023-02-03 11-16-27](https://user-images.githubusercontent.com/11504548/216653352-64ca815b-bb0c-4e5d-a3fe-6a78d29f1138.png)

The thumbnails are generated using the [mapbox static image api](https://docs.mapbox.com/api/maps/static-images/) which has a maximum url length of 8192 characters. Complex polygons exceed this, and the request fails.

We could create a non interactive map for each thumbnail, but we'd need to evaluate the performance impact of this.

**Comment by nerik** [comment]
@danielfdsilva We could also consider:
- not showing the polygon at all, considering showing the boundaries of the viewport already arguably provides most of the value
- re-symplifying the polygon
