### ISSUE TITLE
Fix COVID-19 Dashboard preview on iOS

### ISSUE THREAD

**Issue by michaelgsuttles** [NASA-IMPACT/veda-ui#461]
In iMessage, the preview image still reads "COVID-19 Dashboard"

![Image](https://user-images.githubusercontent.com/7217855/220158682-9ff28db4-7750-478b-a800-ab314ef3e009.png)

**Comment by slesaad** [comment]
Looks like [this image](https://github.com/NASA-IMPACT/veda-ui/blob/main/app/graphics/meta/default-meta-image.png) needs to be updated
