### ISSUE TITLE
Make 'redirection' to jupyterhub more predictable

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#466]
There have been requests to open a new tab when users click on 'VEDA 2i2c JupyterHub'. A design can help set a proper expectation for users that this button will redirect the page to the hub.

**Comment by faustoperez** [comment]
I propose reviewing the modal and incorporating big buttons with the two possible actions, and mentioning that the jupyterhub options opens in a new modal.

I am not sure if these card/button elements exist in the UI library, if not happy to add them or swapping them with a similar existing solution.

[Link to Figma](https://www.figma.com/file/SA0u0sVdw5vM7g9ulV5Xgw/Wireframes?node-id=3136%3A43447&t=5dDujfVDIEhY4bt5-1)

![Design proposal](https://user-images.githubusercontent.com/12268629/223720128-b57a0d72-2d87-4968-b477-313e39c11a52.png)

**Comment by faustoperez** [comment]
Some food for thought about linking to a new tab via @ricardoduplos  https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187

**Comment by danielfdsilva** [comment]
Completed via #491
