### ISSUE TITLE
Configure first draft of Phases II Discoveries - February 2023

### ISSUE THREAD

**Issue by michaelgsuttles** [NASA-IMPACT/veda-ui#467]
## Description
We have a long queue of discoveries to configure. Not all of the data needed for these discoveries is ingested to VEDA, so screenshots or blank spaces might be needed for these drafts. The idea is to have a preview on a branch or in staging that IMPACT and scientists can react to before we go to production.

## Acceptance Criteria
- [ ] Drafts of the discoveries listed below are created and able to be reviewed by IMPACT
- [ ] We have a list of datasets needed for this group of discoveries that we can pass along to the Data Services team and IMPACT to figure out how best to ingest or show the data in the discoveries

<google-sheets-html-origin><style type="text/css"></style>

Indicator | Status | Content | VEDA Link
-- | -- | -- | --
BioMass | 4 - Dev Seed Review | https://docs.google.com/document/d/1XAFo2IbUHOdpTeAaXpDZd7FYVoOJzI7l/edit | https://github.com/NASA-IMPACT/veda-config/pull/199
Air Quality | 4 - Dev Seed Review | https://docs.google.com/document/d/1ihNGt_5JTts-ge6ROnBGixtil39KEiGN/edit |  
Air Quality | 4 - Dev Seed Review | https://docs.google.com/document/d/1DF9D8frhOgu2BFhsrn_ZgF5-vEx9yyjG/edit |  
Cryosphere | 4 - Dev Seed Review | https://docs.google.com/document/d/1Ka0UavQbLPTzWIB8di5XEcSr1ceZZb8L/edit |  https://github.com/NASA-IMPACT/veda-config/pull/206
Cryosphere | 4 - Dev Seed Review | https://docs.google.com/document/d/17iuz4gFY8vIl7rG2Z7iOXcjrGDno7TNJ/edit |  
Air Quality | 5 - In Development | https://docs.google.com/document/d/1UL00th3HIPn4pCKdN_0LLQ2gs6XdFbVW/edit | https://github.com/NASA-IMPACT/veda-config/pull/172

More information here: https://docs.google.com/spreadsheets/d/1QF0BPooGhMFjvEsZwf-vxiirIGyVeYDVqDMvDfzBbfM/edit#gid=0

**Comment by michaelgsuttles** [comment]
@hanbyul-here would it help to assign these to folks (@nerik @aboydnw @danielfdsilva @slesaad and you) or let folks volunteer? I don't know how this is usually done. Defer to the team!

**Comment by hanbyul-here** [comment]
We hope to use these discoveries to train the students planning to contribute to Veda in the future actively. 

I copied the discoveries that need to be configured for our convenience.  

thematics | Author  | Dataset Needed | Dataset Ingestion status |
-- | -- | -- | --
Environmental Justice | Udaysankar Nair | ? | ? |
Environmental Justice | Y. Luna-Cruz |  ?  | ? |
Environmental Justice | Y. Luna-Cruz |  ?  | ? |
Superglacial Lakes | Lilly Thomas |  ?  | ? |


@aboydnw Do you have an estimation of how each discovery will be shaped? If there is a relatively short one with fewer interactive components, that might be a good candidate for students to start their first configuration. + Do you know what kind of datasets each discovery needs/ and is ingested already?

**Comment by michaelgsuttles** [comment]
@hanbyul-here I mentioned in our meeting that I had accidentally pasted the wrong stories in the ticket. Here are the correct ones to configure:

<google-sheets-html-origin><style type="text/css"></style>

BioMass | Ralph O. Dubayah | dubayah@umd.edu | 4 - Dev Seed Review
-- | -- | -- | --
Air Quality | Barry Lefer |   | 4 - Dev Seed Review
Air Quality | Barry Lefer |   | 4 - Dev Seed Review
Cryosphere | Kaitlin Harbeck |   | 4 - Dev Seed Review
Cryosphere | Kaitlin Harbeck |   | 4 - Dev Seed Review

**Comment by hanbyul-here** [comment]
There are five?

**Comment by aboydnw** [comment]
By my count, there are 6. I'll update the original comment with this table.


Indicator | Status | Content | VEDA Link
-- | -- | -- | --
BioMass | 4 - Dev Seed Review | https://docs.google.com/document/d/1XAFo2IbUHOdpTeAaXpDZd7FYVoOJzI7l/edit | https://github.com/NASA-IMPACT/veda-config/pull/199
Air Quality | 4 - Dev Seed Review | https://docs.google.com/document/d/1ihNGt_5JTts-ge6ROnBGixtil39KEiGN/edit |  
Air Quality | 4 - Dev Seed Review | https://docs.google.com/document/d/1DF9D8frhOgu2BFhsrn_ZgF5-vEx9yyjG/edit |  
Cryosphere | 4 - Dev Seed Review | https://docs.google.com/document/d/1Ka0UavQbLPTzWIB8di5XEcSr1ceZZb8L/edit |  
Cryosphere | 4 - Dev Seed Review | https://docs.google.com/document/d/17iuz4gFY8vIl7rG2Z7iOXcjrGDno7TNJ/edit |  
Air Quality | 5 - In Development | https://docs.google.com/document/d/1UL00th3HIPn4pCKdN_0LLQ2gs6XdFbVW/edit | https://github.com/NASA-IMPACT/veda-config/pull/172

**Comment by aboydnw** [comment]
@WeathermanTrent @acblackford You can see in my last comment above that two of the discoveries already have branches created. We still have work to do on those, because they don't have the maps, charts, and figures all configured like we talked about today. But, I would suggest starting fresh to get a sense of the full process, and we can come back to the other two that have been started already. 

Here are my suggestions for which discoveries to start with.

Trent - [Measuring Methane Emission Levels](https://docs.google.com/document/d/1DF9D8frhOgu2BFhsrn_ZgF5-vEx9yyjG/edit)
Andrew - [Pine Islands & Thwaites Glacier](https://docs.google.com/document/d/17iuz4gFY8vIl7rG2Z7iOXcjrGDno7TNJ/edit)

**Comment by aboydnw** [comment]
@WeathermanTrent @acblackford how is this going? Need any support from myself, @danielfdsilva or @slesaad ?

**Comment by danielfdsilva** [comment]
Considering this complete. Smaller issues can be created as needed.
