### ISSUE TITLE
Rethinking Featured Discoveries

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#470]
## Description

Creating this ticket to track ideas that have been voiced during various meetings.

1. It could be cool when a new discovery is published to have a section that says "new discovery here!"
2. Could also just have a running feed of recent stories
3. then featured discoveries becomes a "here's our most popular stories" (could this be automated?)

**Comment by danielfdsilva** [comment]
Included in the new data catalog and discoveries page design.
