### ISSUE TITLE
Download Selected Polygon as geojson

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#471]
## Description

As a scientist I want to download my defined polygon as a geojson so that I can use in future analyses, record as part of my research, or share the polygon with others

## Acceptance Criteria

- [ ] Given I have identified a custom polygon in the analysis page on the Dashboard, when I view results I am able to download the polygon as a geojson (should this happen when viewing results, when entering search criteria, or both?)
- [ ] Given I have selected a standard AOI in the analysis page on the Dashboard, then I am able to download the polygon as a geojson (should users be able to download standard AOIs?)

**Comment by j08lue** [comment]
This is related to the concept of offering users ways to continue their analysis started in the Dashboard in a different environment. 

I think that downloading hand-drawn geometries is less of a priority (an existing workaround is to draw the polygon elsewhere, e.g. on geojson.io, and upload a file), than downloading the extracted points. Closing for now, but keeping in mind when we consider supporting data and/or code snippet export from analysis.
