### ISSUE TITLE
Improvements to Analysis Loading State

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#473]
## Description

As a scientist I want to feel that the analysis results are loading quickly and efficiently so that I decide to stay and wait for the page to load

Relevant feedback:

> - Warn the user if they're trying to leave the analysis page while the analysis is loading (loaded data may be lost)
> - Cache analysis results so that an accidental refresh does not require all the data to be re-fetched.
> - When calculating analysis: add a cancel button, potentially a progress bar too.

## Acceptance Criteria

- [ ] Balancing LOE, UX, and value, the appropriate feedback is addressed from above

**Comment by j08lue** [comment]
Fixed in E&A
