### ISSUE TITLE
Improvements to Polygon Upload for Analysis

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#474]
## Description

As a scientist I want to correctly upload a polygon within the constraints of the system so that I can successfully generate time-series analysis within the VEDA Dashboard without trial and error

Relevant feedback:

> - When a user uploads a polygon it would be good to be able to select what features to import.
> - Add a warning when a user tries to upload a too complex/too large file.

## Acceptance Criteria

- [ ] Balancing LOE, UX, and value, the appropriate feedback from above is addressed

**Comment by nerik** [comment]
@danielfdsilva We should be mindful that the URL length is the first bottleneck we seem to hit, but how likely is it that the next one is the backend erroring/timing out on complex shapes? 

> When a user uploads a polygon it would be good to be able to select what features to import.

Does this mean that the user can see the features on a map and pick them up individually? Or just a text dropdown where we try to guess an appropriate label for each feature? (label then fallback on id then fallback on whatever property is available?)

**Comment by aboydnw** [comment]
Closing as stale
