### ISSUE TITLE
Detailed design of data catalog & discoveries page

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#484]
## PI Objective

[Implement dataset and discovery search](https://github.com/NASA-IMPACT/veda-architecture/issues/229)

## Description
We have a prototype that shows rough sketches of the direction of the Dashboard under v2. The first area we would like to develop is the data catalog. Our proposed process to get from current state to a new data catalog in production is:
1. Add a list view of all datasets currently on the dashboard, regardless of thematic area. This can look and behave the same as our current Dataset page under each thematic area, and can almost act as it's own thematic area, an "All" thematic area. This will eventually become our data catalog (maybe we just call it data catalog from the beginning?)
2. Link this view to the home page for users to jump right into it from the first page (and maybe top nav on the home page?
3. Repeat steps 1 & 2 for Discoveries
4. Layer on search, filter, and other capabilities that we want with this new data catalog view as well as the new discoveries search view
5. Deprecate current thematic area pages [this likely requires some change management from Product]

The goal of this ticket is to start designing step #4 above, so that when development gets through steps 1-3 we have these designs ready for implementation.

## Acceptance Criteria
- [ ] Detailed designs of the data catalog and discovery search views, whether represented as hi-def mockups or other assets
- [ ] Description of how our users will want search to function
- [ ] Description of different ways our users want to filter content in the data catalog and discovery view

**Comment by aboydnw** [comment]
@ricardoduplos I tried to capture here what we discussed earlier today. check if you agree with the details on this ticket ahead of sprint planning please.

Also flagging for the rest of the team @nerik @danielfdsilva @hanbyul-here @faustoperez @anayeaye @ividito @j08lue as this could have cross-functional implications

**Comment by danielfdsilva** [comment]
Wireframes: https://www.figma.com/proto/Tie1qnq4uZ9DS5IVjhgUGI/Dashboard-V2-Mockups?page-id=1%3A47&node-id=3-1436&viewport=-2538%2C-437%2C0.9&scaling=min-zoom&starting-point-node-id=3%3A1436
