### ISSUE TITLE
Map thumbnail fail to load when polygon crosses the antimeridian

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#505]
The mapbox static image api does not support polygons that cross the antimeridian, which can easily happen if the analysis  is done over the pacific ocean.

A possible option would be to split the polygon and make sure it wraps correctly.
The [geojson-antimeridian-cut](https://www.npmjs.com/package/geojson-antimeridian-cut) seems to be the library for this situation, but I wasn't able to get it to work.

Perhaps a simpler approach is desirable.

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/1090606/230392271-1818047a-4e15-4c6e-b959-702823c04741.png">

cc @nerik

**Comment by aboydnw** [comment]
I can confirm I was able to create a time series chart with a similar AOI to the example in the new E&A interface
