### ISSUE TITLE
[E & A] - Navigation helpers / wizard to assist the user

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#519]
> 🙋 This issue is part of the larger [Exploration/Analysis merge component breakdown](https://github.com/NASA-IMPACT/veda-ui/issues/513). The goal is to have a discussion about this specific component and come up with implementation details/next steps.  
Check out the parent issue for a list of all components to consider.

---

## Description

The exploration / analysis page is a complex piece, both in terms of interface and available actions. While we should strive to have the most intuitive interface possible, it is important to consider ways in which we can help the users achieve their goals.

The ways in which we offer assistance can be as simple as an info tooltip, a guided tour of the interface, or a full wizard that takes the user through a series of steps.

## Acceptance Criteria

- [ ] The interface's complex workflows are analyzed and the best ways to provide navigational help for each workflow are identified and evaluated.
- [ ] The solution is reviewed and tested to ensure that it meets the user's needs and effectively addresses the interface's complexity.

**Comment by j08lue** [comment]
Done here: https://github.com/NASA-IMPACT/veda-ui/pull/737
