### ISSUE TITLE
[E & A] - Displaying selected datasets

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#521]
> 🙋 This issue is part of the larger [Exploration/Analysis merge component breakdown](https://github.com/NASA-IMPACT/veda-ui/issues/513). The goal is to have a discussion about this specific component and come up with implementation details/next steps.  
Check out the parent issue for a list of all components to consider.

---

## Description
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1090606/235170967-4f9813e4-e8cd-456e-86e1-97a401c0b7e9.png">

Viewing datasets is the core action of the exploration page, and the user should be able to add multiple datasets and control things like their stacking order, their opacity and other dataset specific settings (e.g. band combination)
For each added dataset, 2 interface elements are needed: a legend and a timeline.

It could be valuable to ponder a bit about the existence of two lists of related data. Having a single list may prove challenging given the amount of information that has to be displayed, but on the other side two lists may lead to a disconnect between the information.

## Acceptance Criteria
- [ ] The pros and cons of each option are evaluated and the best one is selected
- [ ] The workflow for dataset selection and management is designed

**Comment by ricardoduplos** [comment]
Covered in #524.
