### ISSUE TITLE
[E & A] - Date selector and timeline

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#522]
> 🙋 This issue is part of the larger [Exploration/Analysis merge component breakdown](https://github.com/NASA-IMPACT/veda-ui/issues/513). The goal is to have a discussion about this specific component and come up with implementation details/next steps.  
Check out the parent issue for a list of all components to consider.

---

## Description

For each dataset the user needs to be able to select the date that they want to explore. Each dataset may have a different temporal extent and a different time density (day, month, year).

Questions for discussion:
- Should it be possible to select a different date for each dataset? If so
   - How is that information conveyed to the user
- Should there be a single date picker for all selected datasets? If so
   - How is this selector/timeline presented?
   - What happens if there's no data on the selected timestep?
   - What happens if each selected dataset has a different time density? (As an example: Worldview seems to allow day selection but show the same images within a given time density - showing the same image for all days of a month on a month dataset.)
- How could a playback animation feature be included?
   - How would this work with an individual date for each dataset?

## Acceptance Criteria
- [ ] The best approach is devised taking into account the different pros/cons and the needs of the majority of users.

**Comment by ricardoduplos** [comment]
- A single date control is used to control all datasets;
- Each dataset's temporal extension can be visualized on the timeline and its time density is represented as bar segments;
- When there's no data for the selected date (playhead position on the timeline), nothing is shown on the map.

_Vide_ #524 for more information.
