### ISSUE TITLE
[E & A] - Structure of the Analysis/Exploration page

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#524]
> 🙋 This issue is part of the larger [Exploration/Analysis merge component breakdown](https://github.com/NASA-IMPACT/veda-ui/issues/513). The goal is to have a discussion about this specific component and come up with implementation details/next steps.  
Check out the parent issue for a list of all components to consider.

---

## Description

There's a lot of information the display on this page and a lot of actions that users can take. With the goal of merging the current Analysis and Dataset exploration, at a pretty complex page. The way the page is structured will influence very much how it is used and how easily users can achieve their goals. Perhaps not all information needs to be visible at once and the page can take advantage of tabs, view modes and modals to achieve the desired outcome.

This page was often compared to a video/midi editor, making use of a unified timeline and different views with different options. A change in paradigm could be worth exploring.

## Acceptance Criteria
- [ ] A list of options and their pros/cons was created and the best option selected
- [ ] An ADR is created with the result of the decision and the reasoning

**Comment by ricardoduplos** [comment]
From **[NASA VEDA Dashboard V2: Ideation and Design](https://docs.google.com/document/d/1RtlMXie_DX2HCfvZO1OpW8pDpdDryb-KIyLDkGiA2Y0/edit)** document:

> ### Single timeline/master panel approach
> 
> After brainstorming and researching, we decided to pursue an approach inspired by [DAWs](https://en.wikipedia.org/wiki/Digital_audio_workstation) and video editing software.
> 
> The advantages to this approach include:
> 
> 
> 
> * Declutter UI, by merging the dataset list with the respective timeline entries;
> * See at a glance the temporal resolution of all datasets;
> * Include playback functionality;
> * Integrated comparison mode in the same UI;
> * Include analysis capabilities seamlessly.
> 
> In this paradigm, at the bottom of the interface lies a panel resembling a sequencer. Here the information is organized around a master timeline: a list of datasets, displayed vertically, where each entry defines a track. For each track, or dataset entry, there’s a visualized temporal extension. A playhead vertical line is placed along the timeline to determine what’s visualized on the map.
> 
> Scrolling vertically on the master panel reveals more tracks. Scrolling horizontally shows more or less of the temporal extension. It is also possible to zoom in/out on the timeline to reach temporal granularity; this allows for yearly, monthly, weekly or daily selection of time.
> 
> It is possible to add more datasets to the sequencer at any moment.
