### ISSUE TITLE
[E & A] - Analysis worflow

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#526]
> 🙋 This issue is part of the larger [Exploration/Analysis merge component breakdown](https://github.com/NASA-IMPACT/veda-ui/issues/513). The goal is to have a discussion about this specific component and come up with implementation details/next steps.  
Check out the parent issue for a list of all components to consider.

---

## Description
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1090606/235190447-47dbc466-6664-4d14-84db-43fad2d397eb.png">
<img width="935" alt="image" src="https://user-images.githubusercontent.com/1090606/235190513-ba49f1c1-0aee-4b0c-ace4-a46e8780eb1d.png">

The analysis workflow is to be merged with the exploration page so that the users can have additional context while running an analysis.
There are 3 elements necessary for an analysis:
- Spacial definition
- Temporal range
- Datasets to analyze (already selected)

**Temporal range**  
While the dataset exploration requires a single time step, the analysis requires a date range over which the data is analyzed. This date range selector should take into account how the [dataset exploration date is selected](https://github.com/NASA-IMPACT/veda-ui/issues/522) (e.g. single picker vs one picker per dataset)

**Spatial definition**  
To define a spatial area for the analysis, users should be able to:
- Draw an area of interest (https://github.com/NASA-IMPACT/veda-ui/issues/388)
- Upload their own file
   - How can users select what features they want from an uploaded file? (https://github.com/NASA-IMPACT/veda-ui/issues/426, related: https://github.com/NASA-IMPACT/veda-ui/issues/474)
- Select from a list (https://github.com/NASA-IMPACT/veda-ui/issues/405)
   - [Mapbox boundaries](https://demos.mapbox.com/boundaries-explorer/) could be used for geopolitical borders
   - Does selecting from a list add the polygon to the map, or are the polygons visible and the user has to select one?

## Acceptance Criteria
- [ ] The date range selector is designed taking into account how the dataset exploration date is chosen (https://github.com/NASA-IMPACT/veda-ui/issues/522)
- [ ] The workflow for drawing an AOI is defined including the possible shapes, controls and possible actions over drawn shapes
- [ ] The user upload workflow is designed
- [ ] The list selection workflow is designed

**Comment by ricardoduplos** [comment]
From **[NASA VEDA Dashboard V2: Ideation and Design](https://docs.google.com/document/d/1RtlMXie_DX2HCfvZO1OpW8pDpdDryb-KIyLDkGiA2Y0/edit)** document:

> ### Analysis workflow
> 
> Users can analyze the timeseries of different variables (min/max, average, etc) from multiple datasets based on a given Area of Interest and a date range.
> 
> AOI tools are present on the screen from the get-go. These tools allow the user to add shapes to the map that will then be used for the analysis.
> 
> Shapes can be added through:
> 
> * List of presets (countries, states, watershed…);
> * Free drawing;
> * Upload of geojson/shapefile.
> 
> After adding shapes to the map the user will have to select what shapes to run the analysis on. A info box will track how many shapes are selected (eg: 3 shapes selected) and provide a button to start the analysis.
> 
> Once the button is clicked the analysis starts. L and R range markers (by default used for playback capabilities) show the current date range.
> 
> The user will then be able to change the parameters (AOI and date range). This action causes the results to become outdated. A message prompts the user to refresh the analysis. An option will be provided to exit the analysis mode at any time.
