### ISSUE TITLE
Surface changelog in the app

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#533]
We're currently using github released on veda-config to host each version's changelog.

We need to investigate a way to make this more visible in app. Possible approaches:
- Include the changelog in app
- Make link to release page more prominent
- Create a "What's new section" with a curated description of the updates

**Comment by aboydnw** [comment]
This has been open and stale for a while now, so I'm closing. We can reopen if needed.

**Comment by faustoperez** [comment]
> We could expand the version tag(s) in the footer to link to release notes.

Alternatively, we could show a GitHub icon and link the version number with the repository

**Comment by aboydnw** [comment]
> 1. As a program manager considering to use VEDA for my own project, I would like to know what open-source software it consists of and how it is evolving, so I can judge the maturity and suitability of the software to my needs.
> 2. As an owner of a VEDA instance, I would like to easily find information about the version of the software components and what they mean.

I think these are both good user stories to have, but I think they are different than this ticket. I don't know that surfacing the changelog in the app is the best way to accomplish either one of these (it might be, but I'm not sure)

For example, as a program manager considering VEDA, maybe I would prefer to be sent to VEDA docs? Or some more comprehensive page than the veda-ui changelog? Eventually they should be able to find the changelog from there, but it might not be the best place to start.
