### ISSUE TITLE
Switch to a registry from git submodules

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#537]
As the GHG work advances and new `veda-config` instances are created which should consider whether it is worth it to manage the `veda-ui` dependency as a package or to continue to use it as a submodule.

- What are the pros/cons of moving to a package? What do we gain from it?
- How do we manage the development workflow when using it as a package instead of a submodule?
- What's the LOE of this task?

**Comment by danielfdsilva** [comment]
I've been giving some thought to this issue and trying some things.

Advantages of having a package:
- Easier to track versions
- Developer familiarity with packages / no need to mix contexts (git/packages)
- Support for yarn link
  - When multiple projects depend on the same package it is possible to link all of them to a local folder. This makes development easier since all projects use the same local version and parallel development is easier. This is not possible with git.

Disadvantages:
- Need to publish the package. Although it is possible to install directly from github, so that could be an option.

Given the advantages/disadvantages it seems a no-brainer to make the change, but the LEO is pretty high because of how packages dependencies work. I'll do my best to explain the issue.

Veda-ui is setup to run independently from any config instance. This makes development easier as we can have mock data within veda-ui and not be worry that it ends up in production.
Because of this the core code that builds the app is stored and run from veda-ui.

When the `yarn serve` command is executed it loads the mock data and mock config.

When we're running this from a config instance, the command still runs from within the veda-ui submodule. But, this time, since our base directory is the veda config, it knows to load the correct config and data.

Picture it this way (simplified):
- We run the command that's inside the module (`.veda/ui`)
- And load the config from the current directory (`./`)

This idea would work whether we're in `veda-ui` or an instance config.

---

When I tried to convert veda-ui into a npm package I ran into some issues.
Package dependencies are installed at the parent level, so all the dependencies of `veda-ui` are installed in the instance config's `node_module` folder. If we try to execute something from within `veda-ui` it will fail because the needed modules are not found there.

Running the commands from the instance and pointing to a config (`.parcelrc` and `gulpfile.js`) within the `veda-ui` package could be a possibility, but this fails because with parcel (or gulp for that matter), when you specify a path for the config (`.parcelrc` and `gulpfile.js`) that folder becomes the working directory and the needed libraries are not found there because they're installed at higher level.

I think the solution would be to rewrite the the whole command orchestration script, but I still don't have a straightforward idea of how we'd keep the config in one place and the libraries in another.

All in all the LOE here seems pretty high, so unless this becomes high priority (or we have some free cycles) I'd postpone it.
If anyone has other ideas on how to approach the problem let me know.

**Comment by danielfdsilva** [comment]
I've been giving some thought to this issue and trying some things.

Advantages of having a package:
- Easier to track versions
- Developer familiarity with packages / no need to mix contexts (git/packages)
- Support for yarn link
  - When multiple projects depend on the same package it is possible to link all of them to a local folder. This makes development easier since all projects use the same local version and parallel development is easier. This is not possible with git.

Disadvantages:
- Need to publish the package. Although it is possible to install directly from github, so that could be an option.

Given the advantages/disadvantages it seems a no-brainer to make the change, but the LEO is pretty high because of how packages dependencies work. I'll do my best to explain the issue.

Veda-ui is setup to run independently from any config instance. This makes development easier as we can have mock data within veda-ui and not be worry that it ends up in production.
Because of this the core code that builds the app is stored and run from veda-ui.

When the `yarn serve` command is executed it loads the mock data and mock config.

When we're running this from a config instance, the command still runs from within the veda-ui submodule. But, this time, since our base directory is the veda config, it knows to load the correct config and data.

Picture it this way (simplified):
- We run the command that's inside the module (`.veda/ui`)
- And load the config from the current directory (`./`)

This idea would work whether we're in `veda-ui` or an instance config.

---

When I tried to convert veda-ui into a npm package I ran into some issues.
Package dependencies are installed at the parent level, so all the dependencies of `veda-ui` are installed in the instance config's `node_module` folder. If we try to execute something from within `veda-ui` it will fail because the needed modules are not found there.

Running the commands from the instance and pointing to a config (`.parcelrc` and `gulpfile.js`) within the `veda-ui` package could be a possibility, but this fails because with parcel (or gulp for that matter), when you specify a path for the config (`.parcelrc` and `gulpfile.js`) that folder becomes the working directory and the needed libraries are not found there because they're installed at higher level.

I think the solution would be to rewrite the the whole command orchestration script, but I still don't have a straightforward idea of how we'd keep the config in one place and the libraries in another.

All in all the LOE here seems pretty high, so unless this becomes high priority (or we have some free cycles) I'd postpone it.
If anyone has other ideas on how to approach the problem let me know. 

cc @nerik @hanbyul-here

**Comment by danielfdsilva** [comment]
@nerik I don't think it is an absolute requirement. I like to have dev data with the dev env, but I'm open to other ways of doing it.

Your idea of having a module for mock data is interesting. How do you envision that working? Wouldn't another module also need to be tracked and comitted? 🤔 

Not sure about the monorepo. With the separation of context that is going on (and the wish to have different branding on the repos), I don't think that bringing everything under the same roof is a good idea. Specially since different things will be maintained by different people.

**Comment by nerik** [comment]
>  I like to have dev data with the dev env, but I'm open to other ways of doing it.

My personal preference is to work with real data whenever possible, the risk being that we build a tool that works well with dev data, but will lag in spotting issues with real data.

> Your idea of having a module for mock data is interesting. How do you envision that working? Wouldn't another module also need to be tracked and comitted? 🤔

Yes, we'd have something like a `veda-config-mock` repo. Its content would rarely change I guess. Maybe a bit convoluted but also cleaner than having _data_ that lives in _library_ code.

> Not sure about the monorepo. With the separation of context that is going on (and the wish to have different branding on the repos), I don't think that bringing everything under the same roof is a good idea.

If branding of the repos is an explicit and an absolute requirement then it's a showstopper. I would double-check though, the benefits of a monorepo in terms of developer experience could easily outweigh branding arguments. 

> Specially since different things will be maintained by different people.

Plenty of big repos out there that are maintained by different people and even different sets of people, so it's only a matter of setting up the repo properly (tagging system on PRs and issues, etc).

@j08lue Thoughts on having Veda and GHG living under the same repo?

**Comment by j08lue** [comment]
> Thoughts on having Veda and GHG living under the same repo?

To me, there are several arguments to keep instance config and UI separate, and to keep the different instances separate:

1. To me, our goal is to eventually have different teams manage different instances on their own, where `veda-ui` is the common dependency. That both instances are managed by one team (us) is good while the application evolves fast, but as soon as the application is in a state where it stably supports two or more instances, we should try to hand off instance maintenance, IMO.
2. I could also see a not-too-distant future where we ship / promote `veda-ui` as a "plug-and-play" UI app to combine with an eoAPI deployment. Having the UI separate from configs would help for that.
3. GHG is a separate project from VEDA and we need to be explicit about partner equality.

For all of this, keeping `veda-ui` independent of the different instances is important - which speaks against the monorepo.

Are there other ways in which we can improve developer experience? We could still move out the mock data into its own project `veda-config-mock`, I guess - up to you. Happy for us to keep improving dev experience.

**Comment by nerik** [comment]
> I could also see a not-too-distant future where we ship / promote veda-ui as a "plug-and-play" UI app to combine with an eoAPI deployment. Having the UI separate from configs would help for that.

Just wanted to point out that this is not in contradiction with having a monorepo. Ie, several libraries can live under the same repo, but be published as independent npm packages. In fact, it's common practice, this is what [react](https://github.com/facebook/react/tree/main/packages) is doing for example.

Other than that, the non-technical arguments against monorepo make perfect sense, thank you for the clarification.

I'd strongly advocate for a package-based approach. Benefits largely outhweighs the weirdness of finding a place for mock data IMHO.

**Comment by j08lue** [comment]
Happening in the context of
- https://github.com/NASA-IMPACT/veda-ui/issues/799
