### ISSUE TITLE
Discussion: New name for "Discoveries"

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#550]
The name "Discoveries" is very much associated with novelty (something that was discovered), which may not suit the use case of all veda-config instances.

Ideally we could find a term that can work across all instances.  
Another option is to allow this to be configurable, taking into account that it shows up in multiple places, and a different route path (other than `/discoveries`) also needs to be specified. (Developers: An internal default name is needed)

**Comment by j08lue** [comment]
First quick brainstorm for possible generic term:
* story / stories
* note / notes
* insight / insights

**Comment by j08lue** [comment]
For the record, in a tag-up with EIS leads, we agreed that `Data Stories` is the best term we have come up with so far that can work for both instances of the Dashboard, GHGC and VEDA/EIS.

Next step is to check this with NASA project leads.

**Comment by j08lue** [comment]
I checked [during last VEDA Internal](https://docs.google.com/document/d/1tVVphJOkGY75u1r0w8uXX8mjQd3gIXP_OBlhJYykd8o/edit) and the conclusion was that GHG Center should go first with a different name and VEDA might follow.

@danielfdsilva, could we perhaps change the name to "Data Stories" in a `veda-ui` branch that the GHG Center Dashboard is based on for now, so we can demo that? That would help me move that discussion forward.

I am aware that a permanent solution where the two Dashboards use different names would require a larger change. My goal is to find out whether they can agree on something and if not, permanently, we can consider how to properly accommodate that.

**Comment by danielfdsilva** [comment]
Decision:

We'll rename the Discoveries to "Data stories". This change well be done at `veda-ui` level and applied to all instances.

After a experimental period, if stakeholders are ok with it, we'll make code changes to get rid of "discoveries" references (urls, file names, etc.)

**Comment by j08lue** [comment]
Continued in https://github.com/NASA-IMPACT/veda-ui/issues/574
