### ISSUE TITLE
Discussion: Latest dataset vs Featured dataset

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#552]
## Context

From GHG:
> Instead of Featured Datasets, we would like to show the “Latest dataset”  (based on when it is ingested). The content/images will be sliding from right to left

## Behavior
The app currently shows a list of featured datasets based on a flag set by the user. This allows a piece of content to be featured even if it is not the most recent, but because it is important.

Switching to a "latest" approach would change this to showing a single dataset without user control.
⚠️ Since we don't have access to an "ingested" date, this would need to be set by the user in the `mdx` file.

## Action items

- [ ] Figure out what approach works for the majority of cases.

**Comment by j08lue** [comment]
I have a few clarifying questions, @siddharth0248:

What is meant by "Latest dataset"?
1. "most recently added to the Dashboard" (could be old data),
2. "most recently updated with data" (could still be old data, say an annual average from 2022), or
3. "dataset with the most recent observations - or latest predictions"

Why do you want to prioritize datasets this way - why do you think users are most interested in those datasets?

**Comment by siddharth0248** [comment]
We want to display the most recent data that has been ingested in the system to be displayed first. Motivation is that next time the user visits he/she knows that some new data has been ingested

**Comment by j08lue** [comment]
> most recent data that has been ingested in the system

I understand.

A challenge with that is that the frontend currently does not know when data gets ingested (into STAC), only when configuration changes. The frontend only queries STAC once you selected a dataset and started exploring it.

We have a vision of changing that in the future.

For now, a quick solution could be that we added a `lastUpdated` property or so to the Dataset config (I see Discoveries already have `pubDate`). When we only add STAC items, we would have to remember to also update the config.

Cases where we frequently add new data to STAC for an existing Dataset are rare until now, so I think that solution would be fine for now.

Perhaps instances could configure whether they want to use "Latest (Updated?) Dataset" or "Featured Dataset", @danielfdsilva? Or should I ask whether VEDA also wants to change to Latest?

**Comment by danielfdsilva** [comment]
> Motivation is that next time the user visits he/she knows that some new data has been ingested

Showing "latest something" is always tricky and can quickly become strange if there are no frequent updates. If the latest data is 3 months old, it is still the latest, but doesn't look so nice as a showcase.
Should we disable this "latest" if it's older than X?

> we would have to remember to also update the config.

This is way easier said than done, and if we move forward with this option we should consider it transitory and plan for a more dynamic update.

> Perhaps instances could configure whether they want to use "Latest (Updated?) Dataset" or "Featured Dataset"

Easily doable! :)

**Comment by j08lue** [comment]
Actually, @deborahUAH and @siddharth0248 last week decided that this feature (be it featured or latest dataset) does not have high priority and they would simply omit it from the GHG home page. Considering that it adds complexity to the config and app, let us table it for now and revisit this thread if/when the need comes up again.

> if we move forward with this option we should consider it transitory and plan for a more dynamic update

Just for the record - I fully agree that a dynamic update is to be preferred if we pick this up again in the future.
