### ISSUE TITLE
[Feature Request] Allow users to launch into exploration page from discovery

### ISSUE THREAD

**Issue by freitagb** [NASA-IMPACT/veda-ui#557]
Currently embedded interactive maps in the discoveries do not have a link to launch the dataset visualization in the map view. As I've gone through the discoveries, I've found myself looking for a button to open a new browser window with the same view in the dataset exploration view.

Requirements:
- [ ] design some icon/button on the interactive map in the discovery to prompt the users to click if desired
- [ ] upon clicking the icon/button a new browser window opens up the dataset exploration view with the same central lat/lon and zoom level.

**Comment by aboydnw** [comment]
Covered by https://github.com/NASA-IMPACT/veda-ui/issues/844
