### ISSUE TITLE
[Design] Sketch preliminary wireframes for content configuration tool

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#561]
After the research phase regarding content configuration for the VEDA Dashboard, we are ready to start sketching some preliminary ideas about what the tool could look like to be presented to the team for further refinement and to inform the next PI planning.

[Link to Research Miro board](https://miro.com/app/board/uXjVMWpGpcw=/)

**Comment by aboydnw** [comment]
Superseded by CMS integration work with Strappi and others
