### ISSUE TITLE
Rename Discoveries as Data Stories

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#574]
Following the decision in #550, we will prepare renaming the "Discoveries" to "Data Stories". 

This change will be done at `veda-ui` level and applied to all instances.

After a experimental period, if stakeholders are ok with it, we'll make code changes to get rid of "discoveries" references (urls, file names, etc.)

## Acceptance criteria

- [x] Change the name superficially for VEDA GHG Center
- [x] Show to stakeholders
- [ ] Implement fully in code and URLs (`/stories`)
- [ ] Deploy to VEDA NASA and VEDA GHG

**Comment by j08lue** [comment]
I got some good feedback from EIS regarding renaming "Discoveries" to "Data Stories" on their instance. @dfelikson argued against it that EIS wants to tell about science with these stories ("Science Stories"), while the GHG Center to our current understanding wants to use this feature of the Dasboard to tell about features in the GHG data ("Data Stories").

Could a solution be that we refer to this feature as `stories` everywhere in code and URLs but make the title / display name configurable, such that EIS can call them "Science Stories" or keep "Discoveries" and GHG Center can go with "Data Stories" or something else they may want later?

@danielfdsilva and @ricardoduplos  - how do you see this?

**Comment by slesaad** [comment]
@danielfdsilva any chance this can be done before the friday ghg demo?

**Comment by danielfdsilva** [comment]
From https://github.com/NASA-IMPACT/veda-ui/pull/577#pullrequestreview-1524007033

> The title "Data Stories" is
> * Right for GHG Center as far as we know
> * Ok, although not ideal for NASA/EIS
> 
> Next steps after merging this (AFAIK):
> 1. Deploy for GHG
> 2. Deploy for NASA/EIS
> 3. Consider making the title configurable (see https://github.com/NASA-IMPACT/veda-ui/issues/574#issuecomment-1627197508)
> 4. Implement renaming in code/urls to use `stories`, if possible.
