### ISSUE TITLE
Diagnose Application Error on Netlify previews accessed from behind NASA firewall

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#578]
People with NASA VPN and badge report that they consistently get an Application Error shown in their browser when accessing Netlify previews:

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/cb41428d-fbfb-4f76-9cc5-67ad307f4b5d)

The site otherwise seems to work fine, so it is mostly cosmetics?

## Acceptance criteria

- [ ] We diagnosed this error and figured out whether there is something we can do to resolve the issue (dev or NASA firewall config)

**Comment by hanbyul-here** [comment]
Would it be possible to get the actual error message from the console? That would help figure out what is going on.

**Comment by j08lue** [comment]
You do not have NASA Badge/VPN, I take it, @hanbyul-here? Me neither - perhaps we can ping `veda-dev` for someone to reproduce and post all the logs?

**Comment by hanbyul-here** [comment]
I checked in with several developers about this error. Nobody can reproduce the errors anymore. but some logs did show some failures on Netlify side such as 
```
xhr.js:210     GET https://app.netlify.com/access-control/bb-api/api/v1/cdp/deploys/64b01cf8511b7e0008f114a2 401
xhr.js:210     GET https://app.netlify.com/access-control/bb-api/api/v1/developmentseed/members/64b6caae8f700a0a0d983f80 404
``` 
So my guess is Netlify changed how to handle these errors, and I feel like this is not worth debugging anymore.

**Comment by danielfdsilva** [comment]
Seems that it got solved on netlify's side. Considering it complete
