### ISSUE TITLE
[E & A] Prototype and validate analysis workflow

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#579]
The analysis as part of the E&A merge introduces new ways of [interacting with the areas of interest](https://github.com/NASA-IMPACT/veda-ui/issues/526). How the different methods of adding shapes to the map are used need to be tested to understand the optimal flow. Selecting shapes, running an analysis, updating the parameters and refreshing the analysis is a complex flow that is hard to fully test with static designs.

We need to prototype the part of the analysis related to the aoi selection and how an outdated analysis is displayed (result of changing parameters). This issue is not concerned about how the analysis results are displayed.

<img width="1445" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/1090606/d30d0ab4-60ce-4403-af78-fdc8c424fc4a">

**Comment by j08lue** [comment]
NB: Review this old issue and verify that the unexpected behavior does not occur in the new implementation
- https://github.com/NASA-IMPACT/veda-ui/issues/388
