### ISSUE TITLE
Can we add pre-defined AOIs to current Analysis?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#587]
We have in the past been discussing to offer a curated set of preselected AOIs (administrative boundaries down to some level, hydrological basins, etc) for users to choose from to run their zonal statistics in Analysis.

We need this sooner than we thought - it has been requested as a feature for the GHG Center instance.

Perhaps this is part of the design for the new combined Analysis + Exploration (E&A) view. Can it also be back-ported (pre-ported) to the current Analysis view, so we can get it out to users (of the GHG instance) even before the new E&A view is released?

Implementing this for the old Analysis view would NOT be duplicated effort, IMO: the definition of the areas could be directly transferred to the new design, I guess.

## Acceptance criteria

- [x] Answered whether this is part of the upcoming E&A (for context)
- [ ] Answered whether it is feasible to implement this for the current (old) Analysis view
- [ ] Opened a ticket to design and implement (if decided)

**Comment by nerik** [comment]
Previously discussed here:
https://github.com/NASA-IMPACT/veda-ui/issues/405
https://github.com/NASA-IMPACT/veda-ui/issues/442

**Comment by danielfdsilva** [comment]
Although not yet fully designed, having these presets was discussed a lot in the context of E&A and it is a planned feature.

To build this preset selector it would be good to understand a bit better:
- real examples of AOIs we should we be expecting (geopolitical, scientific, etc)
- where/how are these stored (complex AOIs can be heavy - they may require download prior to use and we need the UI/UX for it)

We currently have support for presets in the analysis page, but those AOIs are bundled with the app, so anything we add will increase the bundle size and consequently load times.  
This could be addressed by loading the data asynchronously but this simple dropdown won't scale to support hundreds of admin areas.

![Image](https://github.com/NASA-IMPACT/veda-ui/assets/1090606/c9c7adcd-9cdc-4297-91d2-2a55316d980d)

@j08lue Is there a small set of these AOIs that are a priority and can be used with the current implementation? If not, or if it is not worth it to find them, let's get some real examples and define an implementation plan.

**Comment by nerik** [comment]
> where/how are these stored (complex AOIs can be heavy - they may require download prior to use and we need the UI/UX for it)

Could we explore [Mapbox Boundaries](https://docs.mapbox.com/data/boundaries/guides/) as an option ?

**Comment by danielfdsilva** [comment]
@nerik I think that's definitely an option and something we should work with, but that only solves the geopolitical boundaries part. We still need to factor in the other boundaries (which I imagine to be of equal importance to scientists - @j08lue do you confirm?)

**Comment by j08lue** [comment]
> which I imagine to be of equal importance to scientists

Thanks, yes, I reached out to the science team to name the geometries they would like to make available to the users.

Administrative boundaries are definitely needed, in particular for the GHG Center where accounting on administrative levels seems to be a thing. Loading them from Mapbox sounds like a great approach, IMO, but the approach probably depends on what other sources we need to integrate.

**Comment by Jeanne-le-Roux** [comment]
For GHG Center it may be difficult to get timely input on exactly which options to include. Since the Center is U.S. focused but also has several global datasets, I'd recommend having the option to select by country and also by the U.S. states. Then we can scale up from there based on feedback. @siddharth0248 what do you think?
