### ISSUE TITLE
Can we find a way to enhance plume dataset exploration?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#588]
Exploring emission plumes datasets requires interactions that are currently not possible with the VEDA Dashboard exploration view.

In particular, we would like to provide information about each plume, such as total emission quantity, in a similar way as [Carbon Mapper](https://data.carbonmapper.org/#13.51/29.64677/6.95502) and the [EMIT Open Data Portal](https://earth.jpl.nasa.gov/emit/data/data-portal/coverage-and-forecasts/) are doing:

![Image](https://user-images.githubusercontent.com/3404817/255681649-f4b0e705-9fd0-4b6f-9eaf-d6cea91e1afa.png)

![Image](https://user-images.githubusercontent.com/3404817/255682004-036cc9a6-e3a1-400d-b41f-54737c809bcf.png)

This ticket is to outline and compare possible ways to provide similar functionality in the VEDA Dashboard within the GHG Center release time frame.

## Acceptance criteria

- [ ] Described one or more possible ways to provide plume context functionality and their feasibility

**Comment by siddharth0248** [comment]
@danielfdsilva can we have an option where we can switch on/off the layer. The purpose is to visualize the base layer and identify the potential source of emission.
e.g. Turn off the plume layer and locate the nearby landfill visually

Let me know if we need a separate ticket for this

**Comment by aboydnw** [comment]
@siddharth0248 the ability to turn layers on and off feels like a separate issue. They both help provide context for users, but the information they are wanting seems different. One is more information on the data itself and the other is contextual information about what they are looking at.

**Comment by aboydnw** [comment]
Additional information can be found in https://github.com/NASA-IMPACT/veda-config-ghg/issues/35

**Comment by danielfdsilva** [comment]
Supporting custom use cases within the dashboard is not a trivial task. As a tool that aims to be generic and usable with different datasets, it becomes challenging to cater to very specific situations.
That being said we’re looking to find a way to [include such custom visualizations/interactions](https://github.com/NASA-IMPACT/veda-ui/issues/603). One short-term step we’ve taken in that direction is using embed blocks, which let users include other tools.

One such example can be viewed in the [Recent fires story](https://visex.netlify.app/stories/recent-fires). 

I is likely we won't have time to develop the "Long Term" plan in time for the release, but could building something outside of the app that fits your use case and embedding it in a story be a solution for the time being?
