### ISSUE TITLE
Publication tool: Implement scrollytelling block

### ISSUE THREAD

**Issue by nerik** [NASA-IMPACT/veda-ui#589]
Documentation: https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/MDX_BLOCKS.md#scrollytelling

Implement the `Scrollytelling` block:
- Add a selector on adding a new block along with `Block`
- Figure out how this interacts with the editor flow. Probably use a floating editor rather than in-block.
- Figure out error handling UI

**Comment by aboydnw** [comment]
Superseded by CMS integration work with Strappi and others
