### ISSUE TITLE
Publication tool: Dashboard integration

### ISSUE THREAD

**Issue by nerik** [NASA-IMPACT/veda-ui#590]
Add a proper publication tool section in the dashboard:
- Only in dev like the Sandbox
- Use existing Dashboard navigational elements for now
- Try to integrate as much elements from @faustoperez wireframes as possible https://www.figma.com/file/3IT5sPbKe4gpCUvMeEcwK0/Publication-tool-V1-Wirefames?type=design&node-id=1238-2571&mode=design&t=ml3Z0e3XBzfJ3tXa-0

**Comment by aboydnw** [comment]
Superseded by CMS integration work with Strappi and others
