### ISSUE TITLE
Publication tool: Block-level editing à la notebooks

### ISSUE THREAD

**Issue by nerik** [NASA-IMPACT/veda-ui#591]
Goal: demo the potential of editing content by individual blocks.

Deliverable: a UI on top of the live editor MVP which divides code editing into smaller cells

- Simple UI to:
  - add a new cell at the bottom of the document
  - delete a cell
  - change cell order
- Live preview should happen just above or below each individual cell editor
- Stretch goal: allow users to select predefined code templates/snippets from a list to prepopulate the cell's code.

**Comment by aboydnw** [comment]
Superseded by CMS integration work with Strappi and others
