### ISSUE TITLE
Publication tool: local version of data stories table view

### ISSUE THREAD

**Issue by nerik** [NASA-IMPACT/veda-ui#592]
Wireframes: https://www.figma.com/file/3IT5sPbKe4gpCUvMeEcwK0/Publication-tool-V1-Wirefames?type=design&node-id=1238-2571&mode=design&t=ml3Z0e3XBzfJ3tXa-0

Goal: Implement a table view of a user's data stories without a backend solution yet, only relying on the user browser's local storage

- Implement saving and reading on local storage for multiple drafts
- Add React context or similar state management for drafts
- Create a table view
- Integrate into existing navigation

**Comment by aboydnw** [comment]
Superseded by CMS integration work with Strappi and others
