### ISSUE TITLE
Publication tool: Metadata, preview, and export views

### ISSUE THREAD

**Issue by nerik** [NASA-IMPACT/veda-ui#593]
Wireframes: https://www.figma.com/file/3IT5sPbKe4gpCUvMeEcwK0/Publication-tool-V1-Wirefames?type=design&node-id=1238-2571&mode=design&t=ml3Z0e3XBzfJ3tXa-0

- Allow editing frontmatter for data stories drafts. 
- Allow previewing the whole document without the editing UI
- Allow exporting MDX code

**Comment by aboydnw** [comment]
Superseded by CMS integration work with Strappi and others
