### ISSUE TITLE
Surface tiler links for dataset layers

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#594]
We would like to enable users of VEDA to load the same layer they are seeing in the VEDA Dashboard into their GIS software, for example QGIS or ArcGIS.

[Previously](https://github.com/NASA-IMPACT/veda-architecture/issues/293), we have been focusing on including copy-pasteable tiler URLs in STAC.

Actually, this might be much better suited to be a feature implemented in `veda-ui` - the information about the tiler being used and in particular the styling is actually coming together in the Dashboard, rather than STAC.

Could we imagine adding another "bridge" button or something to the dataset Exploration page that basically lets a user copy a tiler WMTS or XYZ link (which ever we are actually using) for the view they are currently looking at?

## Acceptance criteria

- [ ] Documented discussion and decision on whether and how we could address the user need for getting copy-pasteable tiler URLs from Exploration

**Comment by danielfdsilva** [comment]
Looking for:
- Quick implementation on the current dataset explore page
- Better, cleaner integration for the E&A tool (considering that a dataset might have more than 1 layer. e.g. vector + raster base)

**Comment by hanbyul-here** [comment]
Making a note of a loosely-related issue: https://github.com/NASA-IMPACT/veda-docs/issues/88 (@anayeaye did this demo because of the request, which makes me wonder if we need to provide both wtms /xyz tile?

**Comment by Jeanne-le-Roux** [comment]
Is there a related ticket for the UI component of how a GIS link is presented to the user? Asking for GHG Center specifically.
