### ISSUE TITLE
Alignment of label in Units (Legend)

### ISSUE THREAD

**Issue by siddharth0248** [NASA-IMPACT/veda-ui#599]
Currently, units in the legend section are left aligned and a lot of times it gets broken into multiple lines.

![Screen Shot 2023-08-03 at 10 20 16 AM](https://github.com/NASA-IMPACT/veda-ui/assets/118487103/234e3066-d854-44db-a93a-b829d8bf55a8)

We want to center-align the units in the legend section so that it is more clear and doesn't overlap with the numbers.

**Comment by aboydnw** [comment]
@danielfdsilva heads up I dropped this into next sprint so it will come up in sprint planning on Monday. Essentially, we just want to adjust the legend so the units are displayed more clearly. Sid's suggestion here is to center-align the units but if the team has another suggestion, please suggest it here.

**Comment by deborahUAH** [comment]
Best would be to have 2 lines under the color bar.  The first has the numbers min, max and some middle values for better determining the value when looking at the map.  The second row would be the unit, centered under the bar and values.
