### ISSUE TITLE
Display lat/lon on Explore basemap

### ISSUE THREAD

**Issue by jerikac** [NASA-IMPACT/veda-ui#612]
High priority ask from EMIT team. The ask is to implement the ability to see the lat/lon coordinates at any given location on the basemap that the cursor hovers/clicks over. Open to discussion on how this is displayed to the user (hover window vs at the bottom of the map, etc.). This is not specific to a dataset. 

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/118487103/8d08b0a7-3021-424a-843d-bdbe2447d359)

**Comment by aboydnw** [comment]
@jerikac @deborahUAH @Jeanne-le-Roux can you add this to the [Release 1 Schedule](https://docs.google.com/spreadsheets/d/1u5eYDI_EmL3sSttYkTm91_lEeK2tFsgXH3D22wczmrA/edit#gid=88759098) spreadsheet, add a priority and rank appropriately? That will help us prioritize against all the other issues

**Comment by aboydnw** [comment]
We should also take this into consideration for the updates exploration view @ricardoduplos @danielfdsilva

**Comment by hanbyul-here** [comment]
Can I ask what the value is? I am unfamiliar with the scientist's workflow and would like to know how the coordinate of hovered spot can be used.

**Comment by Jeanne-le-Roux** [comment]
Most scientists will want to know the precise lat/long location of a feature they are looking at on a map for any dataset. In the case of EMIT data, scientists want to be able to pinpoint the exact source of the methane plume and understand the environment around it. Getting a quick lat/long is easier than zooming in/out to understand where they are on the map. Even if they have context of where they are on the globe, they will still want to be able to get precise coordinates.

**Comment by aboydnw** [comment]
Thanks @Jeanne-le-Roux I think the question still remains of "what next" which is a good go-to question to ask for these sorts of requests. What do scientists need this information for and what do they plan to do with it? There have been many requests for "contextual information" from the EMIT team and figuring out which ones to implement and how to implement them will likely depend on this "what next" question.

**Comment by Jeanne-le-Roux** [comment]
I see what you're saying. For EMIT and similar data, one next step could be plugging the lat/long into Google Earth to toggle through the high-resolution basemap layers over time to better understand the source of the methane emission and determine whether it's a false positive. I could also see a next step being using the coordinate information to do some sort of analysis in a notebook environment involving one or multiple layers of data. If a user is already in the middle of doing a data analysis in a GIS environment, and is looking at the GHG Center for supplemental information, I could see the user using the coordinates to precisely navigate to the same location in their GIS environment, so they could look at both sources of information at the same time.

**Comment by aboydnw** [comment]
Sounds good, thanks Jeanne. This helps us develop a solution where people can copy and paste and not have to worry about the lat/lon coordinates changing when they move their mouse. Daniel has a fix coming.

**Comment by j08lue** [comment]
@danielfdsilva and @aboydnw, I take it you have been discussing the pros and cons of 

1. pointer lat/lon - user cannot copy values because moving the cursor changes the position, probably more touch-friendly?
2. map center lat/lon - perhaps less intuitive for GIS software users, harder to point to the location

On the current implementation (map center), we got the feedback that for GHG use case 3 (plume exploration - where is the plume, how large is it, etc), map center coordinates are less relevant than mouse cursor location.

We can consider this for a future revision and also a possible custom UI for plume exploration.

We can keep the feature as it is for the first GHG Center release.
