### ISSUE TITLE
Add scale bar to explore page map

### ISSUE THREAD

**Issue by jerikac** [NASA-IMPACT/veda-ui#614]
Mid-priority ask, _not specific to a dataset_. Add a scale bar to the top or corner of the Explore page's map to indicate the zoom extent/scale of the map for users. See example in image below.
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/98853455/61d25a7b-22d4-4367-a856-72f27cabe55a)

**Comment by aboydnw** [comment]
@jerikac @deborahUAH @Jeanne-le-Roux can you add this to the [Release 1 Schedule](https://docs.google.com/spreadsheets/d/1u5eYDI_EmL3sSttYkTm91_lEeK2tFsgXH3D22wczmrA/edit#gid=88759098) spreadsheet, add a priority and rank appropriately? That will help us prioritize against all the other issues

**Comment by aboydnw** [comment]
We should also take this into consideration for the updates exploration view @ricardoduplos @danielfdsilva

**Comment by Jeanne-le-Roux** [comment]
@aboydnw I'm working today to assess the priority of the new tickets. I view this as a very useful feature and probably something we'll be asked to add if it's missing.
