### ISSUE TITLE
Coastlines not being drawn

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#621]
@danielfdsilva @hanbyul-here It was noticed today on the CEOS datasets that the coastlines are not being drawn properly. When zooming in and out, state and country boundaries are being drawn properly but something is causing the coastlines to not be drawn properly. 

It was noticed on the CEOS datasets but it looks like it might be happening in others. Also sounds like it might have something to do with how the dataset is gridded, @siddharth0248 can you add some details about this? 

![image](https://github.com/NASA-IMPACT/veda-ui/assets/92742765/32b46495-21fe-46c0-99ed-44eaa761fb60)

**Comment by hanbyul-here** [comment]
If this ticket means that the dataset layer is hiding the coastline, setting up a general rule for the order of layers is challenging. If we are sure that the ocean should always cover the dataset (for all the datasets), I can look into it. This also means that the basemap can look a bit interesting(?) since there will be an ocean vector layer on top of satellite imagery.

**Comment by danielfdsilva** [comment]
The current base layer does not have "coastlines".

<img width="434" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/1090606/01648aec-644b-4bd6-ac24-7ae615ac3f20">

This is a setting of the basemap from mapbox. I'll check if they can me enabled and/or added

**Comment by danielfdsilva** [comment]
Mapbox admin boundaries layer does not include the coastlines by default. I added them through mapbox studio. but had to make a couple of code changes.
See rationale at: https://github.com/NASA-IMPACT/veda-ui/pull/625

**Comment by hanbyul-here** [comment]
Oh I misinterpreted the issue in a way that the ocean layer needs to mask the dataset layer (like the carbonplan one: https://maps.demo.carbonplan.org/ ) -_-; Thanks for getting it right @danielfdsilva
