### ISSUE TITLE
Google Tag Manager not properly tracking the data

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#622]
@aboydnw reported that our gtm stopped tracking the data around April. 

To check if there was anything wrong in gtm set up (I will update as I try more things.)
- I checked with https://tagassistant.google.com/, which shows the tracking of the events.

**Comment by aboydnw** [comment]
Okay I did some cleanup in tag manager in the hopes of finding the issue, and that didn't seem to fix the issue. Looking at some tutorials online, they say that in the network tab of developer tools you should see a gtm line and a couple collect lines for google analytics. When loading the dashboard, I don't see any of those, which makes me think the dashboard isn't even firing off data to google analytics.

So I decided to check our original configuration of tag manager. I'm way out of my depth here, but should this be in quotes?
![image](https://github.com/NASA-IMPACT/veda-ui/assets/92742765/9ea295b8-2045-4283-b100-385ded15d5d9)

**Comment by aboydnw** [comment]
Wait...nevermind, I think it was just a delay in data coming through. I am going to keep playing around with it and let you know if it works as expected, but I am hopeful now.

**Comment by aboydnw** [comment]
Okay I feel better now. I think it was something with how we had GTM configured, but I'm not sure what. I deleted a lot of extra stuff like environments, versions, workspaces, etc and configured it back from scratch and now it looks like it might be working 🤷 

Let's let it soak for a day or two though to confirm that data shows up in GA like we expect. Then, I'll configure GHG's GTM space for the same

**Comment by aboydnw** [comment]
Data seems to be flowing in again.
