### ISSUE TITLE
Configured projection does not load on first Exploration load?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#640]
I [changed](https://github.com/NASA-IMPACT/veda-config-ghg/pull/55/commits/851f566f6443aa56bad2071e5612e41ca6516ef4) the default `projection` on a GHG dataset (to Equirectangular). However, the projection does not seem to get selected when I first enter Exploration for that dataset, only when I click on the different layers (and back on the first, for example).

https://deploy-preview-55--ghg-demo.netlify.app/data-catalog/casagfed-carbonflux-monthgrid-v3-ghgc

Is that because the GHG instance does not have a sufficiently recent version of VEDA UI or is maybe something not working as it should?

**Comment by danielfdsilva** [comment]
Fixed by https://github.com/NASA-IMPACT/veda-ui/pull/641
