### ISSUE TITLE
Remove "topo" basemap - not actually topography

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#653]
The "topo" basemap does not actually have topography (shaded relief).

We should probably just remove it from the list of available basemaps.

## Acceptance criteria

- [ ] Removed "topo" basemap option

**Comment by jerikac** [comment]
Slesa and I found that the user needs to zoom in more to see the topographic features -- looks like the map is still good?: 
![image](https://github.com/NASA-IMPACT/veda-ui/assets/98853455/a68b7e01-7454-4350-8281-a2bf592925f9)

**Comment by j08lue** [comment]
Ahh. In that case, let us just keep it for now.

**Comment by jerikac** [comment]
After R1: Several datasets pair well with the "Blue Ocean + Beige Land" that is featured in the topo basemap. action is to disable current "Topo" and add a custom map with the Blue Ocean and Beige Land
