### ISSUE TITLE
[Exploration page] Add custom style that has blue water and beige land like topo but is no shaded relief

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#659]
The shaded relief is not useful for most datasets shown in our apps, because the shaded relief only comes on at very high zoom levels, which do not make sense for the coarse-resolution datasets we usually have.

However, the color combination of it is good as a basemap for some datasets.

Can we add a custom style that has blue ocean and beige land like the "topography" layer but not the shaded relief?

Once we have that, we may want to remove the "topography" layer (to be discussed, though).
- https://github.com/NASA-IMPACT/veda-ui/issues/653

## Acceptance criteria

- [ ] Added custom basemap with blue ocean and beige land

**Comment by aboydnw** [comment]
@j08lue the linked issue is closed, should this also be closed as not planned?

**Comment by j08lue** [comment]
Yeah, good call @aboydnw.

We do want to give data providers quite a lot of say in how "their" should be displayed, because they have the domain expertise about what features in the data are most relevant (e.g. is it the high or the low values, etc.) - which was why we considered adding a custom basemap here.

I think this request here was more a general one, though ("this topo is wrong"). So let us close this unless it comes up again for a particular dataset.

**Comment by faustoperez** [comment]
We should also discuss whether satellite is the best basemap default option for E&A.

**Comment by j08lue** [comment]
> We should also discuss whether satellite is the best basemap default option for E&A.

Yes! Would you open a ticket for that, @faustoperez? I think we could review the datasets we currently have (e.g. in GHGC but could also be EarthData) and make recommendations to data providers that we change it. If we find that satellite does not work well for almost any of them, we could consider changing the default.
