### ISSUE TITLE
[Stories page] Stories need same filtering functionality as data catalog

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#663]
The data catalog has fully configurable filters, where configurators can extend the taxonomy and available options freely.

Is the same possible in the Stories ("Data Insights" in GHG instance) page yet?

## Acceptance criteria

- [ ] Implemented fully configurable taxonomy for Stories, if not already present

**Comment by nerik** [comment]
Yes, it is possible. Closing this, unless there's something specific to do.

**Comment by j08lue** [comment]
Cool, thanks. I added a new ticket to actually add that content.
