### ISSUE TITLE
Review Lighthouse Score and consider optimization potential

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#688]
A check of the Lighthouse score showed low performance and high SEO scores. We would probably expect the opposite to be true...

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/9e39b087-a566-403f-9be5-de2708de872f)

We should look into this and make a good analysis of the status and optimization potential

## Acceptance criteria

- [ ] Reviewed different scores and identified high-effect * low-complexity improvements

**Comment by hanbyul-here** [comment]
### About SEO 

Lighthouse parses out the rendered page to see if DOM is structured well enough for SEO engine, and I am glad we are following a good practice on it. However, this is when the search engine already reached the page. Dashboard is currently set up as a single-page application, meaning there is no page for search engine to crawl without extra setup. 
I wrote about this issue a while ago : https://github.com/NASA-IMPACT/veda-ui/issues/11 

👉 In short, we don't have a lot of options to optimize SEO without shifting the foundational framework. But this might be a good time to think about how we can gradually change the framework, combining it with other issues (ex. submodule structure not being able to solve the problem of 'forking' the repo.) that we have observed so far. 

### About Performance score

AAt least I am seeing a better score from the cache policy that Abdelhak put on the staging. But there are some items that we can do more, such as:
- serve images as webp - https://github.com/NASA-IMPACT/veda-ui/issues/336: Ideally, we will have a pipeline that we can trigger without manually converting the images, but also, we can manually do it at least for the landing page.

**Comment by aboydnw** [comment]
Did we ever get more information on why performance was so low here? or has that score changed?

**Comment by jerikac** [comment]
Also checking in on this ticket... the report can be found **[here](https://nasa-impact.github.io/ghg-lighthouse-performance/)**. Looks like the width and height of  images could be made explicit to help improve the score.
![image](https://github.com/NASA-IMPACT/veda-ui/assets/98853455/042b2ad2-20a2-4ae0-b350-28036b87ce15)

**Comment by jerikac** [comment]
Yep - I think the goal for GHGC is to improve the report to =<85

**Comment by aboydnw** [comment]
@jerikac @Jeanne-le-Roux @siddharth0248  looking at the lighthouse report again, two low hanging fruit I can see are:
1. Making sure all images are only as large as necessary, compressing or replacing where it makes sense
2. Adding descriptive text to nav links

I think we could take a quick look at #2, could you all take a look at the first one?

**Comment by aboydnw** [comment]
Closing as not planned for now. can reopen if continues to be an issue
