### ISSUE TITLE
Replace duplicated map component

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#712]
When starting to work on the new Analysis+Exploration page, the team decided to build the map component from scratch to improve the layer management process (given that now the map needed to support multiple simultaneous layers), and the overall code. 

The different blocks (and other app sections) that use the [old map](https://github.com/NASA-IMPACT/veda-ui/tree/1c5bf02cd5ff6246844b9d43a7f6dce05fc8a28c/app/scripts/components/common/mapbox) should be refactored to use the [new map](https://github.com/NASA-IMPACT/veda-ui/tree/main/app/scripts/components/common/map) and the old code should be removed from the app.

When doing this some consideration should go into the [map block](https://github.com/NASA-IMPACT/veda-ui/blob/1c5bf02cd5ff6246844b9d43a7f6dce05fc8a28c/app/scripts/components/common/blocks/block-map.tsx) and consider whether its behavior should change a little, since the new map:
- supports multiple layers rather than just one
    - should this be in the block?
    - how many layers are reasonable given the need for legends (which btw are not a feature of the new map)
    - should layer configuration (like opacity) be allowed?
- Layer comparison is now manually defined instead of through the dataset configuration
    - Compare date was a property, but compare layer wasn't

These are just some topics to consider when doing this, but some more discussion should go into this.

**Comment by sandrahoang686** [comment]
**Notes:**
* Maps embedded in stores use old map component
* New map component -> app/scripts/components/common/map
* Old map component -> app/scripts/components/common/mapbox

**Plan:**
* Identify where the old map components and where in the codebase replace
* Replace old with new and just get it works with no new functionality
* And then be able to support multiple layers

**Comment by sandrahoang686** [comment]
1/23/24 Checkin: Focus on story blocks only
