### ISSUE TITLE
Rethink the approaches for front-end instances

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#718]
Some work is going into this issue, and this ticket is the main reference to those efforts. 

- RFC (closed): https://docs.google.com/document/d/1jI8d3FtX06w1-cdHlvDxtwDRQk8nOkDr5iTR5S1ThTA/edit#heading=h.gkrwk06m61hp

Decision section is not complete, but the comments are closed for now. I think as the next step, we should grasp the resource the team has, makes a decision, and breaks down the decision into actionable items. 

- VEDA deployment lesson slide: https://docs.google.com/presentation/d/11eYypymE5FeNwE_NVGO_k8pzx_4H615JQ3EdPZw1RMY/edit?usp=sharing (The slide is not public)

**Comment by hanbyul-here** [comment]
@j08lue summed up a strategic approach well in the ticket. This ticket is to complement, and layout the options and processes that front-end team can take. 

Related: https://github.com/NASA-IMPACT/veda-ui/issues/537

From the comments of RFC and the registry ticket, the team generally agrees on modularizing UI, and making it as a core dependency of the instances. To recap the pros that we can expect
- Breaking the coupling between UI components and instances: more freedom for framework choice for instances - Ex. the instance can be statically generated (better SEO).
- Better onboarding process: Current VEDA structure is accustomed to the specific need that the dashboard team assumed at the very beginning of the project. A more 'generalized' structure setup (such as UI as a npm dependency of instances) will ease the onboarding process and possibly require less involvement from the DevSeed side for a new instance setup.

The ideal state will be
- A proficient developer can incorporate the part of VEDA UI into an existing app.
- A person who wants to set up an instance quickly will be able to fork the 'template' instance (which has VEDA UI as a dependency) and make the changes they need in the template instance. 

The main challenge will be developing the VEDA instances, which should parallel this restructuring of VEDA UI. At this stage, let's leave how instances work with VEDA UI until we have a clear path to componentize/modularize the components with a successful example of another instance (or example template) that uses the VEDA UI components. I would like to discuss further with @sandrahoang686 about what to do as a next step. If my opinion helps, we can start with making veda-ui installable and making the parts of it comsumable. (I just tried it briefly and it fails because of `link:` we are using for some modules.) So let's say I just want to use the `Card` component from UI; I can do that from a plain next app (or whichever app). In this way, there will be two ways of consuming veda-ui: one is having it as a submodule, and the other is having it as a dependency for a while.

**Comment by sandrahoang686** [comment]
Brainstorming sessions: https://miro.com/app/board/uXjVN6lkBnc=/
Tickets: https://github.com/orgs/NASA-IMPACT/projects/17/views/6?filterQuery=-status%3ADone+-status%3AIdea+label%3A%22veda+v2%22
