### ISSUE TITLE
[E & A] Change play head and range selector look and behavior

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#721]
- [ ] Show range selectors (currently labelled L and R) only when a geometry has been selected, to avoid confusion about their (lack of) purpose outside of analysis and guide users to their purpose once they start analysis
- [ ] Replace labels on range selectors (currently L and R) by either just icons or From/To
- [ ] Show playhead label (current A) only when there are more than one
- [ ] Change default playhead position to be at the most recent data across the loaded datasets (currently the oldest)

**Comment by danielfdsilva** [comment]
Implemented in https://github.com/NASA-IMPACT/veda-ui/pull/598
