### ISSUE TITLE
NetCDF visualization on VEDA

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#725]
@abarciauskas-bgse created a prototype for visualizing NetCDF directly from CMR: https://github.com/NASA-IMPACT/veda-ui/compare/feat/trmm-demo?expand=1

Make this PR production ready by reviewing the code change and finding the spots to improve, if there are any.

* Titiler instance for this change is not released yet.

**Comment by abarciauskas-bgse** [comment]
Thank you @hanbyul-here !

**Comment by j08lue** [comment]
Linked PRs are closed, so I'll close this ticket for now.
