### ISSUE TITLE
Bring back route redirection from /discoveries to /stories

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#729]
There are apparently still links to old "Discoveries" of the VEDA NASA/EIS instance out there, which are broken since we renamed `/discoveries` to `/stories`.

Like https://www.earthdata.nasa.gov/dashboard/discoveries/wq-models

Did we have a redirect from these legacy links in place at some point? If so, perhaps we removed it while fixing https://github.com/NASA-IMPACT/veda-ui/issues/682?

If it is not much trouble, we should bring this redirect back.

## Acceptance criteria

- [ ] Assessed the effort / consequences of (re-)introducing redirect from discoveries to stories and implemented, if sensible.

**Comment by hanbyul-here** [comment]
There is a change that reintroduces the discovery redirection. At least, based on the assessment of my local profilers, it seems to be working ok. I would rather deprecate this, especially if we are launching EIC page (where this page is linked.) 

https://github.com/NASA-IMPACT/veda-ui/tree/fix/back-redirection
