### ISSUE TITLE
[E & A] Conduct exploration and Analysis feedback sessions

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#740]
User testing sessions for the new Exploration and Analysis interface for the VEDA Dashboard.

Nov 13 week. Focus on most common tasks for both Exploration and Analysis: add multiple datasets, change their parameters, work with the timeline interface, start and exit an analysis. There's a limit of 30min per interview.

- [x] Write discussion guide
- [x] Conduct sessions
- [ ] Research synthesis

**Comment by faustoperez** [comment]
## Discussion guide
This is a general structure to guide the conversations for the user testing sessions for the new E&A interface.

**⚠️  Important: There's a limit of 30min per interview.**

### Introduction
- Introduce who you are, your role in the interview, and the value these feedback sessions bring to NASA and the VEDA platform.
- Introduce the need for the new interface in the context of the project: more powerful exploration and analysis features, ability to visualize multiple datasets at the same time, perform quick analyses over those datasets.
- Ask permission to record.
- Share test URL (TBD)

### Exploration
- Add a dataset to the app
- Change the date of the current view on the map
- Ask to share more about the dataset's temporal resolution, from what they see on the interface
- Add a second dataset
- Change their layering order
- Ask to change dataset parameters (visibility, opacity, etc.)
- Remove a dataset

### Analysis
- Ask to trigger an analysis over a map area (no help, if possible).
- Ask about the analysis time period from what they see on the timeline.
- Change time period
- Explain the analysis results
- Exit the analysis

### Closing thoughts
- What stood out in our conversation today as surprising or important? What haven’t I asked that you feel I should know to get the benefit of your experience?
- Thank the participant

**Comment by j08lue** [comment]
For the record, we ended up asking the users to answer realistic-ish questions using the UI:

## Exploration & Analysis Tester Interview Instructions


### URL for testing

[https://deploy-preview-220--ghg-demo.netlify.app/exploration](https://deploy-preview-220--ghg-demo.netlify.app/exploration)



1. Please open it in a private window / clean browser
2. Password: partnership
3. Please close the Netlify bar at the bottom of the screen \
(unrelated to the purpose of this test)


### Assignment 1: Seasonal patterns of primary production 🌳


#### Question

How do global patterns of Net Primary Production (from the CASA-GFED3 Land Carbon Flux dataset) differ between summer and winter in a given year?


### Assignment 2: Origins of Canadian fire emissions 🔥


#### Question

In past years with high average CO<sub>2</sub> emissions from forest fires in Canada (Fire Emissions (FIRE) from the CASA-GFED3 Land Carbon Flux dataset), did they occur in the same parts of the country?


### Assignment 3: Hot streams 🌊


#### Question

At what times of year is there net negative Air-Sea CO<sub>2</sub> Flux in the Gulf Stream (North Atlantic, off U.S. East Coast) or the Kuroshio Current (North Pacific, off Japan)? Does the flux over such an area have the same magnitude between years?

**Comment by j08lue** [comment]
Complete! Followed up by

- https://github.com/NASA-IMPACT/veda-ui/issues/761
- https://github.com/NASA-IMPACT/veda-ui/issues/762
