### ISSUE TITLE
[E&A] Review analysis messages

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#741]
This is a job for pro designers. 🙇  If any are available, please chime in or take over. If not, please consider my proposal below.

## Proposal

1. When user made a selection:
   
   <img height="25px" src="https://github.com/NASA-IMPACT/veda-ui/assets/3404817/2375a068-8104-4edb-8567-4c7092135f85">

2. When the selection changed while there is an active analysis:

   <img height="25px" src="https://github.com/NASA-IMPACT/veda-ui/assets/3404817/f8b56025-a8e1-492c-af04-30b5a639ac83">

3. When the user reset the selection but there is still a time series on the bottom drawer:

   <img height="25px" src="https://github.com/NASA-IMPACT/veda-ui/assets/3404817/18c4b91f-d43c-42d4-8d76-d94a41671561">

## Changes with respect to current implementation

1. No "warning"-level alert to users - changed analysis parameters that are not yet applied is not a problem they need to be alerted to, IMO.
2. Use the same "timeseries" icon on the message head to indicate at that the message relates to the zonal statistics / analysis
3. Spell out button functions not only for initial "Analyze" but also the other options ("Apply Changes" and perhaps also "Exit") for more consistency and clarity
4. Updated message texts for the two cases of (1) changed selection and (2) no active selection

_Originally posted by @j08lue in https://github.com/NASA-IMPACT/veda-ui/issues/733#issuecomment-1803482867_

**Comment by danielfdsilva** [comment]
1. If a user selects a different feature and gets distracted, they may think that what's on the chart refers to that area. Perhaps we should err on the side of caution.
3. Using full text buttons makes the bar pretty long, which is already long to start with. Personally I also don't think we should be spelling out everything. Could be a matter of choosing better icons, but will defer to designers.

cc @faustoperez and @ricardoduplos for some input

**Comment by j08lue** [comment]
Ok, please ignore my concrete suggestions regarding buttons and icons

The important thing for me was the wording ("Selection changed" instead of "Outdated"). I just spelled out the call to action ("Apply Changes" and "Exit") for our own clarity. How you design this is totally up to you of course.

**Comment by j08lue** [comment]
Closing this so nobody gets angry at me for playing with Figma. 😈

**Comment by faustoperez** [comment]
These are the updated analysis messages, without changing the current analysis flow functionality. This is the general approach:

- Make actions explicit by having a primary button attached to them
- Review the labels on the analysis banners
- Move the area editing actions to their own space at the bottom center of the map

Link to Figma file 👉 https://www.figma.com/file/Tie1qnq4uZ9DS5IVjhgUGI/Dashboard-V2-Mockups?type=design&node-id=1899%3A7371&mode=design&t=cZQ1N9krCO90sxHU-1


<img width="1226" alt="Analysis banners" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/b9fd75a9-c367-42ac-bd1d-e6fec3ac3ff6">
