### ISSUE TITLE
[E & A] Respect dataset default projection and basemap

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#755]
In the old Exploration view, we added the option that datasets configure a default map production to get shown in, like this one in our mock data:

https://github.com/NASA-IMPACT/veda-ui/blob/44dbd82f0d62828bf1585cce64dfb4a3cf537a5c/mock/datasets/no2.data.mdx#L54-L55

It does not seem like this property is used in the new E&A interface. Is that something to fix? It was a valuable feature for the GHG Center interface, where the data providers wanted to have a more accurate default depiction of the data, e.g. with Equal Earth.

## Acceptance criteria

- [x] Dataset layer projection and basemap can be configured in E&A

**Comment by danielfdsilva** [comment]
It is still possible to change the projection, but it won't do it by default.
Now that multiple datasets can be added it is tricky to know which projection to use. Which dataset defines the projection? The user flow here can result in unexpected changes for the user, so we need to be careful

**Comment by j08lue** [comment]
> Now that multiple datasets can be added it is tricky to know which projection to use

That makes sense. Let us think some more about that. 

GHG scientists were really not happy about Web Mercator, so perhaps a configurable global default could help. Or some logic which one of the per-dataset config we pick...

We can discuss that soon.

**Comment by j08lue** [comment]
Latest idea: 

1. Projection and basemap are initialized to that of the **first** layer added to the map, to optimize for the most common (?) single-layer explore case, where we want users to view the data in the best possible way.
2. Projection and basemap do **not** change when user adds/removes/re-orders layers, to avoid the unexpected changes for the user @danielfdsilva warned about.

**Comment by danielfdsilva** [comment]
@j08lue That's an interesting approach.
What happens if, when starting, the user adds 2 datasets that have different projections? Default to mercator, or pick one "at random" from those 2?

**Comment by j08lue** [comment]
> Default to mercator, or pick one "at random" from those 2?

In which order are the layers currently added to the interface, actually, when a user selected multiple?

I'd use the properties from what ever ends up being the top-most layer. I am really optimizing for the case where the user adds a single layer / looks at a single layer (first) and make sure they get the intended / optimized view in that case. We can leave any more automagic solutions for maybe later. 😄
