### ISSUE TITLE
Discoveries single: table of contents navigation

### ISSUE THREAD

**Issue by ricardoduplos** [NASA-IMPACT/veda-ui#76]
Implement a collapsible table of contents, displayed as a column, floating on the left side of a discovery. This UI piece will be useful to expose the structure of the content, and to easily link to any section (denoted by a heading).

### From the wireframes
https://www.figma.com/proto/SA0u0sVdw5vM7g9ulV5Xgw/Wireframes?page-id=0%3A1&node-id=469%3A2005&viewport=264%2C48%2C0.5&scaling=min-zoom

<img width="895" alt="Screen Shot 2022-03-28 at 14 17 03" src="https://user-images.githubusercontent.com/1016701/160406140-921dd95b-a60d-4692-a464-bc9716d649d1.png">

---

#### Dropbox Paper
https://paper.dropbox.com/

##### Collapsed
<img width="663" alt="Screen Shot 2022-03-28 at 14 01 46" src="https://user-images.githubusercontent.com/1016701/160404618-f199bbc4-a873-4b70-8101-32a272caa9dc.png">

##### Expanded (on hover)
<img width="659" alt="Screen Shot 2022-03-28 at 14 01 57" src="https://user-images.githubusercontent.com/1016701/160404918-b9b560f9-e275-422c-8e3f-2dcc31c11d99.png">

---

#### Almanac
https://almanac.io/

##### Collapsed
<img width="393" alt="Screen Shot 2022-03-28 at 14 04 03" src="https://user-images.githubusercontent.com/1016701/160405019-1e77ff3c-1905-44e0-a2d5-6f8b60409cc1.png">

##### Expanded (on hover)
<img width="379" alt="Screen Shot 2022-03-28 at 14 04 18" src="https://user-images.githubusercontent.com/1016701/160405072-711ad63e-c9b8-4446-b1a2-0fa890a15bf5.png">

**Comment by aboydnw** [comment]
Closing as stale, can reopen if needed
