### ISSUE TITLE
[E & A] First pass of improvements based on user testing

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#761]
This is to scope out a **first pass of fixes** for issues with the E&A interface, discovered during the user testing sessions last week, which we would like to fix before a first release

## The issues to address:

1. Users were unable to find out how to **start a zonal statistics ("analysis") workflow**
2. Users did not know whether there was a **side-by-side comparison** option and, even when they knew, were unable to find it
3. Users found it hard to see, which datasets were selected in the **dataset catalog** (modal)
4. Some users were lacking +/- **zoom buttons on the map**
5. Some users were challenged to **pan and zoom the master timeline** or did not know that this was possible
6. Most users did not get key insights from the **guided tour** - we could instead focus on pointing out the existence of hard to find features

## Acceptance criteria

- [x] Designed / named quick solutions to the above issues
- [x] Implemented the changes

**Comment by faustoperez** [comment]
Speaking with Jonas today, we also considered reviewing the walkthrough to highlight 3 features, and maybe include some little graphics on the tooltips:

- Zonal statistics (analysis)
- Comparison tool
- Timeline panning
