### ISSUE TITLE
Set maximum memory on analysis jobs

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#765]
The zonal statistics calculations for the Analysis feature (`/statistics` on TiTiler) can require a lot of memory on the processor side when large areas of a higher-resolution dataset are requested. This has in some cases caused failures of the Lambda-based processors, which surface as 500 errors for the client.

- https://github.com/NASA-IMPACT/veda-config-ghg/issues/232#issuecomment-1822898191

This issue can be avoided by passing the `max_size` flag to the `/statistics` jobs.

Now we could configure this for every dataset, since we added front matter configurable analysis parameters in

- https://github.com/NASA-IMPACT/veda-ui/pull/757

But perhaps this could also be an application-wide setting for VEDA UI or so?

## Acceptance criteria

- [ ] Decided whether to implement an application-wide setting for `max_size`
- [ ] If so, did it, if not, opened a ticket to configure this on all GHG datasets

**Comment by aboydnw** [comment]
@j08lue do we have any way of understand how often this error happens?

**Comment by j08lue** [comment]
> do we have any way of understand how often this error happens?

I am not sure how far the backend is wrt gathering API failure metrics (https://github.com/NASA-IMPACT/veda-architecture/issues/409) - I'll ask (on that ticket).

I would suspect that this error currently does not happen often. Most of the GHG Center datasets have rather low resolution, so you could even run global analysis on them without running into memory issues. I am not sure we even should support continental-scale analysis of higher-res datasets - but it would be nice to tell users about this limitation when they encounter it, not just throw a server error (500).

It would be great if we did not have to set `max_size` on requests but the backend would know and handle its own limitations nicely.

I'll note this on our objective to design a new zonal statistics API (https://github.com/NASA-IMPACT/veda-architecture/issues/419) and close this ticket for now.
