### ISSUE TITLE
Welcome page: featured content carousel

### ISSUE THREAD

**Issue by ricardoduplos** [NASA-IMPACT/veda-ui#77]
Implement a responsive, touch-friendly carousel to be used on _Featured Discoveries_ and _Featured Datasets_.

Note that featured list and respective items (cards) are already implemented. We just need to wrap these in a carousel.

### From the wireframes
https://www.figma.com/proto/SA0u0sVdw5vM7g9ulV5Xgw/Wireframes?page-id=0%3A1&node-id=303%3A1088&viewport=264%2C48%2C0.5&scaling=min-zoom

<img width="1439" alt="Screen Shot 2022-03-28 at 14 31 33" src="https://user-images.githubusercontent.com/1016701/160408855-391300eb-7505-419e-850c-d075a9b45387.png">

---

#### Flickity
https://css-tricks.com/creating-responsive-touch-friendly-carousels-with-flickity/

## Acceptance Criteria

- [x] Given multiple discoveries have been identified as featured for a specific thematic area, when a user visits that thematic area they have a way of viewing all the featured discoveries

**Comment by aboydnw** [comment]
@danielfdsilva @hanbyul-here @ricardoduplos I added an AC here
