### ISSUE TITLE
[E & A] Simplify the feature tour to give visual cues about key features

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#770]
Picking up from #761 

## True (user) story

1. As a user, I am not interested in stepping through a user manual of the user interface before I start interacting with it.
2. As a user, I would like to know about key features of an application I may not be aware of, so I can consider using them.
3. As a user, I would like to see visual cues instead of reading text about a feature, so I can quickly gauge the value the feature may have to me.

## Suggestion

- [x] Highlight only (1) the side-by-side comparison and (2) time series analysis
- [x] Add a visual cue to each step that quickly illustrates the outcome the user can expect from using the feature

## Acceptance criteria

- [ ] Designed and implemented

**Comment by faustoperez** [comment]
> Make the tour mandatory to step through, showing that there are only two steps

I know you mention are only two steps but I wouldn't make the tour mandatory just in case someone is a recurring visitor, refreshing the page or opening in incognito mode

> Add a visual cue to each step

I was thinking about this, I'll try to create a couple of interface animations that work for every instance

**Comment by faustoperez** [comment]
Here's the two animated gifs we came up with (for now). Could try different colors or styles to better match the "brand".

![analysis2](https://github.com/NASA-IMPACT/veda-ui/assets/12268629/def3a59f-7927-4069-8c79-911cbe5adf83)
![comparison2](https://github.com/NASA-IMPACT/veda-ui/assets/12268629/6f2fddcb-e572-43e8-9951-5eb9be8d6cfe)
