### ISSUE TITLE
Revisit layer groups / datasets

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#774]
We currently have a concept of datasets (loosely corresponding to STAC collections), which can have multiple layers (corresponding to STAC assets - similar to variables in NetCDF etc.).

We need to look into how we represent this grouping consistently throughout the app - the Exploration & Analysis layer selection currently does not represent any groupings - and ideally keep it close to STAC.

## Acceptance criteria

- [ ] Described the current and target data model with reference examples

**Comment by faustoperez** [comment]
Assigning it to myself to think of a design solution for this 👍

**Comment by faustoperez** [comment]
Speaking with Jonas earlier today, here are the design action points:

- [ ] Identify examples from the current catalog that match the use case @j08lue 
- [ ] E&A layer selection modal. Add collection/groupings support, show/communicate non-available datasets
- [ ] E&A data panel on the timeline to support nested components, communicate the number of available layers but not display all of them at once (performance issues)

**Comment by j08lue** [comment]
## Examples for multi-layer datasets from the current GHG Center catalog

1. [CASA-GFED3 Land Carbon Flux](https://earth.gov/ghgcenter/data-catalog/casagfed-carbonflux-monthgrid-v3)
   ![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/0dfda8fe-3541-4047-89e8-704ab733545d)
2. [OCO-2 MIP Top-down CO₂ Budgets](https://earth.gov/ghgcenter/data-catalog/oco2-mip-co2budget-yeargrid-v1)
   ![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/7455469d-73fa-4be8-b603-2a886475f7bf)

## User flows

### Switching between dataset and layer information

This is a hypothetical use case that illustrates the need for simultaneous access to dataset and layer information

1. User looks for data for CO₂ fluxes between land and atmosphere (carbon stored in land being released to the atmosphere e.g. via fires, or atmospheric carbon consumed by land, e.g. by vegetation growth). Research questions:
   1.  Where in the world do the largest fluxes occur?
   2. How do uptake and release compare across the year e.g. over a region of tropical rainforest?
3. User goes to catalog and looks through dataset titles
4. Finds the CASA-GFED3 or OCO-2 dataset
5. Wants to see which parameters the datasets include - LIMITATION: no information on layers on the Dataset Overview page
6. Clicks Explore to open the E&A interface
7. In E&A, sees the filtered list of layers for the dataset
8. It is not immediately apparent that this filter is applied via the search box
9. Adds a layer to the E&A interface
10. User is looking for information about the dataset again (e.g. temporal and spatial coverage to know what they can select) - LIMITATION: dataset information not available from E&A
11. Goes back to the catalog or dataset overview page to look for that information
12. Leaving E&A means they lose the state of the interface (layers, time, analysis, etc.)

### Enter through E&A

1. User learned that they can explore GHG datasets on the U.S. GHG Center website. Enters the website for the first time.
2. User sees the menu item "Exploration" and opens it
3. User sees list of layers (has not encountered the concept of Datasets yet)
4. User is looking for more information about the data layers - provenance, longer description, temporal and spatial coverage
5. Layer cards include title of the dataset but are otherwise not linked to dataset-level information
6. E&A interface has a layer info button, but clicking that takes the user out of the interface, loosing its state.

**Comment by j08lue** [comment]
## Our current data model / access mechanisms - mostly static / locally configured, single catalog

1. `Datasets` and `Layers` belonging to the datasets, configured in MDX that combines front matter with dataset overview page content. I.e. datasets and layers relation is hard-coded in config
2. All information on datasets and layers is contained in these MDX files, except for information about temporal and spatial coverage, which is loaded from STAC when user accesses the layer in the Exploration/Analysis interface
3. Requires information from STAC about temporal and spatial extent and data periodicity

## Microsoft Planetary Computer data model / access mechanisms - largely dynamic, single catalog

Relies largely on STAC, plus additional "storage" datasets - see [PlanetaryComputerDataCatalog](https://github.com/microsoft/PlanetaryComputerDataCatalog) repo

1. Groups of `Datasets` - encoded in custom field in STAC + additional descriptions etc. in [datasetGroups config](https://github.com/microsoft/PlanetaryComputerDataCatalog/blob/6a3d61811b0c069e21fbaa1212fbef5aee2c7f27/src/config/datasetGroups.yml)
2. `Datasets` corresponding to STAC collections - including rich-text descriptions
3. Assets (aka variables, bands, layers)
4. Rendering information - probably stored in auxiliary config somewhere (not part of public repos)?

## Our target data model - mostly dynamic, multi catalog

TBD

1. Dataset groups (optional)
2. Datasets
3. Layers / assets / variables / bands

**Comment by faustoperez** [comment]
Thank you Jonas!

**Comment by faustoperez** [comment]
Here are the designs for the layer groups / collections on the E&A interface. 

Link to Figma file 👉 https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=706%3A1518&mode=design&t=XPpNJKF2Hguv85nW-1

The work is done around 2 main areas:

### Dataset panel

- We treat every layer as part of a collection, even collections with 1 layer only.
- The collection name is displayed on the layer card using the primary color, with a new collection icon
- We have simplified the layer action icons, displaying the `info` only, and the rest of the actions under a `more` icon. Related to #811 

<img width="1728" alt="US GHG Center - Timeline + data panel - options" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/e72b0521-60b5-4ef7-baf3-22117f1c14b7">


### Data layers selection modal

- Group every layer under its parent collection.
- Add a short description of the collection, from the Data Catalog
- Add Source, Spatial Extent and Temporal Resolution to the description
- Change the style of the cards to the Discoveries cards, to make the card selection clearer.
- Each layer should have its own thumbnail. As a fallback, they use the collection thumbnail. Design work to be done in [#831](https://github.com/NASA-IMPACT/veda-ui/issues/831)
- Nice to have: layer count on the number of layers selected inside of a collection.

<img width="1728" alt="US GHG Center - Timeline + data panel - collection" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/13ac3a9a-806d-41a8-b9ef-6bdf7df0fa7b">

<img width="1037" alt="Pattern 1 - full scroll" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/55f36233-7d92-4366-b7c3-7c2367f7373d">

<img width="1037" alt="Pattern 1 - full scroll - search" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/5251e0ae-313c-46b6-888d-f6a104d88cd3">

**Comment by faustoperez** [comment]
Drag and drop design work in ticket #836
