### ISSUE TITLE
Can site analytics be set up to pick up rendered titles?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#775]
Site analytics (for GHG Center) indicate that many pages have the same title. The second biggest bucket of page names is “U.S. Greenhouse Gas Center”

Is it easy enough to find all the pages with this name and add more detail to the name? that would help make these analytics more useful.

NB: Could be instance-specific pages (check across GHG Center, EIC, and VEDA Dashboard).

cc @aboydnw 

## Related

- https://github.com/NASA-IMPACT/veda-config-ghg/issues/262
- https://github.com/NASA-IMPACT/veda-config-ghg/issues/202#issuecomment-1757744919
- #688

## Acceptance criteria

- [ ] Reviewed how many pages have the same title and expanded it where possible

**Comment by j08lue** [comment]
Related:

- https://github.com/NASA-IMPACT/veda-config-ghg/issues/262
- https://github.com/NASA-IMPACT/veda-config-ghg/issues/202#issuecomment-1757744919
- #688

**Comment by aboydnw** [comment]
I poked around a bit more on this. I had set up google analytics and google tag manager to best handle single page apps, and it is properly sending page views when it should be based on this configuration. Here is a screenshot of the information sent during one of those page views when testing. You can see it sends the correct URL but still has the generic title. 

![image](https://github.com/NASA-IMPACT/veda-ui/assets/92742765/af5c1851-2be6-4423-a74e-fad1642f6825)

When I look at this page in the browser, I see the corresponding title in the dev tools. Which makes me think it's not anything to do with the Google Analytics configuration.

When I look at the most visited pages, I see this table.

![image](https://github.com/NASA-IMPACT/veda-ui/assets/92742765/570e75c7-f732-47c4-898c-c5e681cabfc7)

But when I change it to show the URL, the results are much different.

![image](https://github.com/NASA-IMPACT/veda-ui/assets/92742765/9ed0d71c-85c6-4992-b5b0-75ad63a2feb8)

All of this makes me wonder if we just need to go through each page and update the title? Can we confirm that we've set titles for each page to be something unique?

**Comment by j08lue** [comment]
Thanks for investigating this, @aboydnw.

> Can we confirm that we've set titles for each page to be something unique?

Passing this on to @hanbyul-here and @sandrahoang686 🙏

**Comment by aboydnw** [comment]
Closing, we have found some workarounds on the analytics side
