### ISSUE TITLE
Critical error page should offer a way out

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#777]
Critical errors sometimes occur due to data issues, invalid cache, or perhaps reasons we do not know.

- https://github.com/NASA-IMPACT/veda-config-ghg/issues/249

In such cases, the users see an app crash page, but do not necessarily know what is best to do from there. Sometimes, reload will help see the page they wanted, sometimes the best is to go back to where they came from.

Can we somehow improve the app crash page to offer a way out for users?

## Acceptance criteria

- [x] Decided what action to offer to users
- [ ] Implemented it

**Comment by hanbyul-here** [comment]
We are going to offer a link to the main page at the bottom of critical error page.

**Comment by j08lue** [comment]
A bit late revelation here, but I think we should also revise the title of that error page. "Critical Error", "That's a fatal error" is very alarming, while often a reload actually get the user what they were looking for, so the error was not fatal and the situation is probably not that critical for users either.

Examples:
1. "Aw, Snap!" - very informal, Google Chrome
2. "Oops, something went wrong." - a bit more specific, somewhat informal, Spotify, I think
3. "We’re sorry, we couldn’t load your content." - quite specific, more formal

Considering that we have a title and subtitle, I'd recommend that we just move the first sentence of the paragraph into those:

Title: "Something went wrong"

Subtitle: "We couldn't to load your content."

Paragraph: "This is on our side and we'll fix it. In the meantime ..."

Any other thoughts?

**Comment by faustoperez** [comment]
I second Jonas's changes 👍
