### ISSUE TITLE
[Design] Accessibility - Implement focus states and keyboard navigation features

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#789]
Following https://github.com/NASA-IMPACT/veda-config-ghg/issues/197

We have adapted some of the [USWDS](https://designsystem.digital.gov/) recommendations and best practices on accessibility, and we have created the focus states for the link styles and main form elements.

Link to Figma file 👉 https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=489%3A1155&mode=design&t=ZGRXc9iqK1Ixl8oH-1

- [ ] Create skip navigation link for keyboard browsing
- [ ] In all pages, implement `tabindex` order coordinated with the structure of the webpage
- [x] Update links `focus` and `active` states
- [ ] Add icon to external links
- [ ] Update header text link styles (`font-weight` to semibold for better contrast)
- [ ] Update footer text link styles (`font-weight` to semibold for better contrast)
- [x] Update buttons text styles (`font-weight` to semibold for better contrast)
- [ ] Update buttons to have `hover`, `focus` and `active` states.
- [ ] Update form elements to have focus states and be accessible through keyboard navigation

<img width="2117" alt="Link states" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/12268629/f946cebd-c8c6-46d7-a076-c3167cf680df">

<img width="2335" alt="Form states" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/12268629/561f00e4-2dc4-4d76-ab9d-50886272baa1">

**Comment by sandrahoang686** [comment]
Decision: Accessibility styles will be applied to all instances so this should be done at the veda-ui level
