### ISSUE TITLE
[E & A] Give users an option to invoke the guided tour again

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#793]
During testing, users found the guided tour relevant and helpful.

Some wished to invoke it again later, because they wanted a refresher on the instructions or regretted clicking it away too fast.

## Acceptance criteria

- [x] Designed a way for users to bring up the guided tour again after closing it
- [ ] Implemented it

**Comment by faustoperez** [comment]
Self-assigning this 👍

**Comment by faustoperez** [comment]
Here's a design proposal for bringing back the guided tour:

- Include an icon in the map options group.
- It should behave as the rest of the icons (have an associated tooltip on hover). 
- The tooltip should read "Open guided tour"

Link to Figma 👉 https://www.figma.com/file/Tie1qnq4uZ9DS5IVjhgUGI/Dashboard-V2-Mockups?type=design&node-id=2065%3A6954&mode=design&t=gCPfc7nJ41oZWzw5-1

<img width="1440" alt="E A with guided tour" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/d5b66342-102e-4057-96a4-d1a1120f9e28">

<img width="283" alt="Guided tour tooltip" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/305ddf28-c26a-47a6-90fc-25ec1bbddd48">

**Comment by j08lue** [comment]
Could we imagine a hint for the users, when they close the tour, that its re-invocation lives under that icon? I've seen these tours or helpers close with a note like "I'll be over here if you need me".

Just a thought, nvm if it's overthinking...

**Comment by faustoperez** [comment]
> Could we imagine a hint for the users, when they close the tour, that its re-invocation lives under that icon? I've seen these tours or helpers close with a note like "I'll be over here if you need me".

We could try, another idea is to include an animation so the window closes towards the icon button. Maybe overkill since this is not a key feature of the app

**Comment by j08lue** [comment]
> another idea is to include an animation so the window closes towards the icon button

Yeah, that was exactly what I thought about. Overkill yes, probably, but if it is simple enough to do... 😄

**Comment by hanbyul-here** [comment]
I have a related question. Is the 'guide' supposed to appear every time a user lands? Or should we save it on local storage so it doesn't pop up the next time a user lands?

**Comment by j08lue** [comment]
Only once (local storage), please.

**Comment by hanbyul-here** [comment]
Not sure if this is a question or more like a comment. So when there is no layer, the tour doesn't really make sense. (Also there is no element to attach the tour.) I am going to disable the button when there is no layer, but lmk if there is any better solution.

**Comment by j08lue** [comment]
Good catch. Disabling sounds good to me.

**Comment by faustoperez** [comment]
Sounds good to me too, thanks for catching this up 👍
