### ISSUE TITLE
[E & A] Make sure Explore option does not show up for datasets that are omitted from E&A

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#796]
The current Exploration & Analysis interface [tests](https://github.com/NASA-IMPACT/veda-config-ghg/pull/217) revealed that some datasets have an Explore button in the Data Catalog / Dataset page but should in fact be omitted from exploration in that interface because it is not well suited for that particular dataset. Main case is `epa-ch4emission-yeargrid-v2express`, but there may be more datasets that are either technically not suited for E&A-style browsing or the data providers expressed that this interface is not adequate.

Clicking that Explore button now (e.g. in [this feature preview](https://deploy-preview-217--ghg-demo.netlify.app/data-catalog/epa-ch4emission-yeargrid-v2express)) shows up the pre-filtered data layer selection, but no layers are available (since they are omitted):

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/ad46fc63-a408-4673-98ba-c5e8fca14731)

We need to ultimately figure out how to offer users adequate ways to browse these datasets. In the meantime, we should make sure this Explore option does not show up on the Dataset page if the dataset is configured to be omitted from E&A.

## Acceptance criteria

- [ ] Make sure Explore option does not show up for datasets that are omitted from E&A

**Comment by hanbyul-here** [comment]
For our information,
When dataset analysis is disabled from mdx configuration (analysis.exclude), it won't show up at all on the list. If the dataset doesn't have a flag, but is not in the shape that can offer analysis (ex. I was just testing CMR data) the timeline will says we cannot offer analysis on this dataset.

**Comment by hanbyul-here** [comment]
I just checked the latest E&A, and I believe this problem is already fixed 👍
