### ISSUE TITLE
[VEDA2 Refactor] Implementation - Create layer / build pipeline to access core ui library 

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#800]
**Description:**
As part of the refactor work for veda-ui v2, we need to figure out how to access components from the instance level to consume as a library. This will likely require us to wrap the current ui logic with a layer to easily access components by importing through npm registry (to be determined).

**This ticket is the implementation ticket of the findings from [#799](https://github.com/NASA-IMPACT/veda-ui/issues/799)**

**Acceptance Criteria:**

- [ ] Cleanly wrap the current veda-ui code with a layer to be able to easily access components as a library
- [ ] We should be able to easily import components at the instance level for consumption
- [ ] It shouldn't have to worry about the loader dependencies which is how the current veda-ui is rendered

for example... at the instance level, we can regularly import any component that has been broken out in veda-ui library

```
import { Card } from 'veda-ui/components/card';

function Content() {
   return (
      <Card/>
   )
}
```

**Resources:**
https://miro.com/app/board/uXjVN6lkBnc=/

**Comment by hanbyul-here** [comment]
A very rudimentary level of the experiment is going on the `test-dependency` branch now. (Also, on this codepen which uses this branch as a dependency: https://codesandbox.io/p/sandbox/using-veda-ui-nsz24n?file=%2Fsrc%2FApp.js)

**Comment by aboydnw** [comment]
@hanbyul-here @sandrahoang686 this seems like a pretty critical step. I'm wondering if there are any dependencies that must come first before we can do this?
