### ISSUE TITLE
[VEDA2 Refactor] Exploration - Core features to modularize

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#801]
**Description:**
As part of the refactor work for veda-ui v2, we should migrate from "page" components at the core ui library level to "feature" components. Then at the instance level, we can define our page views here instead (pages will now be controlled at the instance level) and consume these new "feature" components exposed by the new core ui library. We need to define all our core features as part of this exploration work so we can incrementally break these components out.

**Acceptance Criteria:**

- [ ] Work with Design, @faustoperez, and Product, @j08lue or Alex Gurvich to define core features within the VEDA dashboard (for example, `Exploration & Analysis` feature)
- [x] Document the core features here that will need to be broken down 
- [ ] ⭐ Create new tickets as a result of exploration for each core feature to be modularized and attach to this issue 🌟 ⭐ 🌟 
   - [ ] It is very important that we have a clear distinction of new vs legacy code. We should decide new naming and in-code documentation standards so that it is clear what are new components as part of `veda-ui` v2. This should be decided and noted in new tickets for each core feature
> Note 1: We might not be able to define all the core features right away and might discover more along the way but this is needed as a starting point to start modularizing
> Note 2: Core features are product features that any instance should be able to readily use, these are different from layout components, aka the header or nav bar which should now be dictated at the instance level. The core ui library shouldn't worry about layout anymore

UPDATE: Decided to start creating core feature tickets for features we already know we want to breakout and modularize. (ex. E&A). This way we can start working on modularzing without having to define ALL components.

**Resources:**
https://miro.com/app/board/uXjVN6lkBnc=/

**Comment by faustoperez** [comment]
Self-assigning this and starting gathering a list to be discussed with the team.

**Comment by sandrahoang686** [comment]
Work with @faustoperez on defining presentation components to be specced out in figma as part of this ticket

**Comment by sandrahoang686** [comment]
https://miro.com/app/board/uXjVNlIZVJI=/?share_link_id=691531418055

**Comment by sandrahoang686** [comment]
Data Catalog breakout ticket: https://github.com/NASA-IMPACT/veda-ui/issues/892
