### ISSUE TITLE
[VEDA2 Refactor] Exploration - New Design System Integration

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#804]
**Description:** 
As part of the refactor work for veda-ui v2, we are hoping to remove custom global design dependencies (devseed ui library) and replace with a new design library that is well maintained, documented, and adopted by communities to remove maintenance support on our end. We need to explore new design systems and how to integrate into this new architecture.

**Acceptance Critieria:**

- [ ] Decide on new design system library
- [ ] Understand how we can start integrating it as part of veda-ui v2
- [ ] Maybe hold a brainstorming session so design and engineering are in sync here

**Resources:**
https://miro.com/app/board/uXjVN6lkBnc=/

**Comment by hanbyul-here** [comment]
Shouldn't this be a separate epic?  Refactoring the current architecture doesn't require a new design system, and we aim to introduce as little new code as possible.  (Also a new design system seems to be a big enough topic to be an independent epic.)

**Comment by sandrahoang686** [comment]
> Shouldn't this be a separate epic? Refactoring the current architecture doesn't require a new design system, and we aim to introduce as little new code as possible. (Also a new design system seems to be a big enough topic to be an independent epic.)

This is just an exploration ticket to start discussing the topic as part of the refactor. It's supposed to lead to other work which I guess could be a separate epic down the road. This doesn't mean we have to work on it in parallel but I think we can start discussing the topic earlier rather than later.

**Comment by faustoperez** [comment]
Thanks Sandra! Linking here some related tickets:

https://github.com/NASA-IMPACT/veda-ui/issues/766
https://github.com/NASA-IMPACT/veda-config-ghg/issues/197

**Comment by sandrahoang686** [comment]
Discuss thoughts of when to start integrating the new design system*

I know there were conversations on when it is ideal to start integrating the new design system. I believe we all agreed that it makes sense to separate integrating the new design system while we are doing the refactor to reduce the amount of moving pieces which I agree makes sense. One piece I didn't factor in though and now am having second thoughts on is when building new features / components. I would like to get your thoughts here @oliverroick and @hanbyul-here. Currently working on a ticket to build a new floating filters side bar component for the data catalog page (ticket [here](https://github.com/NASA-IMPACT/veda-ui/issues/915)) which spurred these thoughts since the design used a different ds system (fausto is flexible here though, we can just use the old DS to make it close enough) and i'm also using this ticket to also start modularizing this feature component more. 

My thoughts are, I think it actually makes sense to decide which design system we would like to move forward with and if it isn't too much overhead, then to add the new DS much sooner rather than later. This is because I think it makes more sense to build out these new features with the new DS rather than building out the new features with the old DS and then going back to update them  along with slowly migrating all the other pre-existing components over to the new DS. This just seemed like more unnecessary work which doesn't make sense to me. 

I propose working with @faustoperez  on deciding the new DS system, Designer now has a DS system to work with when designing new features in figma. We build out **new** features with the DS system. All currently existing components that use the old DS system remains using that to reduce to moving parts when it comes to refactoring existing components. This way in the future, we only need to port over the currently existing components over to the new DS and the new features that are currently being developed will already be at its ideal state. I dont see much risk here as the new features and existing components will be pretty segregated. But are there any risks i'm missing? What are your thoughts here, open to feedback and suggestions 🙏🏼

**Comment by j08lue** [comment]
> I think it actually makes sense to decide which design system we would like to move forward with and if it isn't too much overhead, then to add the new DS much sooner rather than later. 

> We build out new features with the DS system. All currently existing components that use the old DS system remains using that to reduce moving parts when it comes to refactoring existing components.

Makes sense to me. I'd suggest to address this question first thing in our next dedicated refactor sprint.

**Comment by faustoperez** [comment]
Thanks @sandrahoang686 . I think I can prioritize the work on this, after most of the E&A v2 design work is cleared.

**Comment by aboydnw** [comment]
@sandrahoang686 @hanbyul-here @dzole0311 

This ticket also seems old and very high level. Should we close in favor of our recent trajectory or maybe just narrow the scope a bit?

**Comment by faustoperez** [comment]
> Should we close in favor of our recent trajectory

That makes sense to me unless Sandra thinks otherwise!

**Comment by dzole0311** [comment]
Looking at the acceptance criteria, it appears they have been met now that we have decided to use USWDS, did the [spike](https://github.com/NASA-IMPACT/veda-ui/issues/959) and are working on using the design for the Announcement feature and the E&A date picker. So I'm also in favor of closing it as completed.

**Comment by sandrahoang686** [comment]
Yeah lets close
