### ISSUE TITLE
[E & A] Implement redesigned timeline handles and labels

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#822]
Implementation ticket of 
- #774

> [!WARNING]  
>  Hold for now until the design is finished

## Refinement required

- Clarification on the timeline needed
- The details of the design can be changed. Check the Figma link to see the latest design.

![Image](https://github.com/NASA-IMPACT/veda-ui/assets/4583806/91bbe67a-8f2b-4104-a084-f8d31ab0f003)

Figma Link: https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=703%3A926&mode=design&t=Jc1CpvnWiVIwmbr8-1

## Acceptance criteria

- [ ] Style change of timeline handles
- [ ] Implementation of the new side handles that allow users to adjust the start and end dates

![Image](https://github.com/NASA-IMPACT/veda-ui/assets/4583806/60f4c096-0829-463e-ab98-15a1d24bc4f7)

**Comment by faustoperez** [comment]
Design ticket here 👉 #833

**Comment by sandrahoang686** [comment]
Looked into code to help gauge effort here. This looks to be mostly css / stylistic changes. I estimate effort to be ~ 1-2 days likely. Changes would happen in `/exploration/components/timeline/timeline-head.tsx` file.

**Comment by faustoperez** [comment]
> This looks to be mostly css / stylistic changes
This is still WIP but I'll try to keep it that way.

**Comment by aboydnw** [comment]
I didn't catch this one before making #979 
I'm going to close this on as a duplicate
