### ISSUE TITLE
[E & A] Implement layer info modal

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#823]
Implementation ticket of 
- https://github.com/NASA-IMPACT/veda-ui/issues/811

## Refinement needed

- Clarification on the timeline needed
- The details of the design can be changed. Check the Figma link to see the latest design.

![Image](https://github.com/NASA-IMPACT/veda-ui/assets/4583806/079eb5ba-2452-4c42-b671-12e3f8ba312e)
![Image](https://github.com/NASA-IMPACT/veda-ui/assets/4583806/e1c6bf95-d9b2-42ea-a59a-b2b4006c626d)

## Acceptance Criteria

- [ ] Offer a way for editors to add a layer info through MDX file
- [ ] Add layer info icon to trigger layer info modal
- [ ] Display of layer info modal

**Comment by faustoperez** [comment]
Edited the comment above to make it link to #811 

<img width="1728" alt="US GHG Center - Timeline + data panel - options" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/b093ca7e-ee46-4478-9316-9a95f136e03e">
<img width="900" alt="Info modal - single dataset - text" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/57977e47-c352-423a-a12e-289703f629bc">

**Comment by hanbyul-here** [comment]
One more question: Where would 'Learn more' take a user to? Should this be another attribute? or is this a link to the dataset catalog page?

**Comment by j08lue** [comment]
> or is this a link to the dataset catalog page?

That, yes.

**Comment by faustoperez** [comment]
@hanbyul-here 

> Can the description under the title be templated from the data below? or is it something editorial that a human needs to write?
> The design includes a link for the Data Latency section. So the expectation for these strings is HTML?

The sample content for this design is taken from the layer overview page here 👉 https://earth.gov/ghgcenter/data-catalog/odiac-ffco2-monthgrid-v2022

This includes the header description, and the bullet list for the dataset attributes (including the external link). We should standardize this info to it doesn't have to be manually entered in two different places. Hope this helps!

**Comment by hanbyul-here** [comment]
Closed via https://github.com/NASA-IMPACT/veda-ui/commit/24a06b30d9b04097493ffebceb2138194d04a1dd
