### ISSUE TITLE
[E & A] [Design] Review the main navigation header on E & A page

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#832]
### Issue:
User research sessions show that some users went to the data catalog main navigation item when trying to add data to the map, effectively leaving the app.

### Acceptance criteria:

- [x] Investigate ways to make the data selection more evident from the app
- [x] Review the main header navigation in the E&A context
- [x] Make the timeline drawer collapsable (https://github.com/US-GHG-Center/ghgc-architecture/issues/224)

**Comment by j08lue** [comment]
We got some feedback from a data provider confirming the need to free up vertical space in Exploration & Environment.

- https://github.com/US-GHG-Center/ghgc-architecture/issues/224

Btw, they also asked for the bottom drawer to be fully collapsible.

**Comment by faustoperez** [comment]
> Btw, they also asked for the bottom drawer to be fully collapsible.

I added that item.

**Comment by faustoperez** [comment]
After reviewing with the dev team and considering multiple options, this is the proposed design solution:

### E&A Default view
- Remove header completely from E&A page
- Add logo block to the top left, aligned with the area tools
- The logo block acts as a button that opens the menu.
- It has a white background and can accommodate any instance logo no matter the aspect ratio.

### Header overlay

- For simplicity, we overlay the standard header without changing the logo so we don’t have to create an additional version for this, and can reuse the header component without modifications.
- Users cannot interact with the app when the navigation is present.
- Clicking outside the header closes the overlay.

### Collapsable timeline

- For the 3rd item on the ticket (collapse the timeline) we propose a conservative approach as the available space will increase if we remove the header. If more user feedback is available and another approach is needed, we can review later.
- Keep the current slide-down resizing behavior.
- Add 16px border-radius for the timeline top borders for user affordance.

![Desktop Flow](https://github.com/NASA-IMPACT/veda-ui/assets/12268629/4003cbcb-b2b7-4000-814a-3e465d1b73d5)


Link to Figma file 👉 https://www.figma.com/design/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?node-id=1658-2239&t=UqtkAD4bPR33rNlP-1
