### ISSUE TITLE
[E & A] Design -  Assess accessibility of controls on option panels

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#838]
### Issue
During a front-end meeting, there were concerns about accessibility and best practices regarding controls on options panels like the opacity slider on the layer options panel.

<img width="1070" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/adb23428-d1be-48e2-8ca8-efbf27fbb4fa">

This ticket is to investigate the issue @sandrahoang686 

### Acceptance criteria

- [x] Investigate the issue
- [ ] Communicate the results to the team

**Comment by aboydnw** [comment]
@faustoperez @sandrahoang686 was this ever investigated? I'm not as familiar with accessibility best practices, so I'm not sure what is actually wrong here

**Comment by faustoperez** [comment]
> @faustoperez @sandrahoang686 was this ever investigated? I'm not as familiar with accessibility best practices, so I'm not sure what is actually wrong here

For context: this was a comment in one of our front-end checkins. Specifically it was about the layer opacity range control being in a floating sub-menu.

I did check but couldn't find any specific reference or article about this specific case on the usual sites https://www.w3.org/WAI/standards-guidelines/wcag/ and https://www.nngroup.com/articles/

I'll report back to the team today and close this issue for now.

**Comment by aboydnw** [comment]
@faustoperez assuming we can close this, but let me know if you think it should be reopened

**Comment by faustoperez** [comment]
I think we can safely close this, thanks Anthony!
