### ISSUE TITLE
[Data Catalog] Overview page redesign to accommodate many data types and interactions

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#840]
### Issue
To make it more flexible and future proof, the data catalog overview page should accommodate different data types and link to different tools in the platform + incorporate more advanced functionality.

#### User story
A researcher wants to get authoritative information about how greenhouse gas emissions from land evolved over the last decade, to get a first indication for a hypothesis they have.

They find a relevant dataset (or concept page / story).

They can see that there are 7 different options to browse, study, or analyze the dataset(s):

- A quick browser for the specific layer (e.g. current Exploration interface, integrated with catalog or so)
- A raster and zonal statistics time series explorer (E&A)
- A link into viewing this data in QGIS
- A link into loading this data in Python/R in JupyterHub
- A link to an external tool from EPA (or other agency) that presents the same or similar data
- An interface for downloading specific files directly
- API docs for loading the data from somewhere else

The user can see that the tools differ in complexity and kind of study they support. After a quick browse in the Exploration interface, they decide to open the E&A interface.

They take note that there are many other options and the GHG Center promotes access to the data directly in the cloud and web browser, which may become relevant as they deepen their research.

### Acceptance criteria

- [x] List the different data types it should support (i.e. raster time series, plume-type, 3D, tabular, etc)
- [x] Gather feature requirements

**Comment by aboydnw** [comment]
There are a few different things to consider for this redesign. Some of this is already in the original comment, just jotting down my thoughts here.

### Data Types
There will be lots of different types of data, that might require different tools for visualization and analysis. These include:
- L3 (and below) raster and time-series-based data
- L2 (and up) raw imagery and swaths of images
- Sub-daily model outputs, such as weather or fire data
- "Instances" or "events" such as methane plumes, earthquakes, or volcanic eruptions

### Connected Tools
- Map visualization and zonal statistics
- QGIS or ArcGIS 
- VEDA's connected JupyterHub environment
- Dataset specific tools already created by the data providers
- Related data stories in VEDA

### Additional Information/Resources for Consideration
- API documentation
- Downloadable files
- Simple visualization for that specific dataset
- Description of the dataset, including examples and references
- Dataset metadata

**Comment by aboydnw** [comment]
@j08lue when you get the chance, could you review the list above and double check if we are missing anything?

Also @faustoperez @j08lue I'm wondering if this satisfies the criteria on this [PI objective](https://github.com/orgs/NASA-IMPACT/projects/39/views/8?pane=issue&itemId=61960776) for "Designed source-agnostic data model and dataset discovery UI"?

**Comment by j08lue** [comment]
I took the liberty to add a few lines and details to your list above, @aboydnw.

> I'm wondering if this satisfies the criteria on this PI objective for "Designed source-agnostic data model and dataset discovery UI"

Getting the requirements down is an important first step. I'll add that as success criteria on the objective, so this progress becomes visible. I guess having actual UI designs / wireframes was quite a stretch.

And we do not need this new UI to integrate the first set of ArcGIS layers - those can also be usual Datasets with overview pages.

**Comment by j08lue** [comment]
@faustoperez and I talked a bit about this today. I think an important question is how to bring together

1. Dataset context that the VEDA instance adds - prose, links to related stories, etc.
2. Structured information (ideally from STAC)

To illustrate: Planetary Computer basically just renders the [STAC collection metadata](https://radiantearth.github.io/stac-browser/#/external/planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2), consisting of a tiny bit of prose (description, providers, DOIs) and the technical metadata about coverage, assets etc.

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/b6f94373-a3c6-4e50-86b5-6e896cb99bf4)

We probably want to give users access to all the structured technical information, too, but the prose part might be expanded in VEDA to add instance-specific context.

Should we combine the two - VEDA prose and STAC metadata? Or keep them in separate tabs? Or link to STAC Browser for the STAC part? What if the data in STAC is not very rich or we want to keep the overhead of featuring the dataset in VEDA low?

**Comment by faustoperez** [comment]
Related: https://github.com/NASA-IMPACT/veda-ui/issues/839

**Comment by faustoperez** [comment]
Here are the designs for the Overview page. Please browse on Figma as the PNGs are too big to be all featured here.

Link to Figma file 👉 https://www.figma.com/design/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?node-id=1862-1985&t=m5WnKRQapqbJ12JD-1

<img width="1728" alt="US GHG Center - Data Catalog - Overview" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/76356e20-6ae1-4235-b818-b486bfc7c1e5">

### Summary of changes:

- The map block is sticky and features the first layer of the collection.
- We propose to organize the content in three tabs: Overview, Access data, and Notebooks
- We use accordions and tables to structure content, ideally all the info will come already structured from STAC.
- The map can be browsed full width by clicking the the middle left icon.
- The “Launch in Analysis tool” only appears when applicable (time series layers)
- In the case of "Instances" or "events" such as methane plumes, earthquakes, volcanic eruptions, etc, the app shows the appropriate map. Note the absence of “Launch in...” button.
- On the Access data tab, we show links to open the layer in external services.
- The actual list would depend on the services available.
- There’s also an optional block to download the data from the source.
- Multiple notebooks are shown as accordions.
- Mobile styles also included
