### ISSUE TITLE
[E & A] Review analysis on new E&A interface

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#857]
### Issue
We are missing the previous selector to enable Max, Min, Avg. etc. metrics on the analysis results due to the new design / implementation. Also, the previous analysis results page included more than one chart.

### Acceptance criteria

- [x] Review and propose a design solution to toggle chart metrics
- [x] Review expanded dataset panel styles
- [x] Review how to show multiple charts from a single dataset analysis
- [x] After triggering an analysis: fly and zoom the map to AOI; zoom the timeline to focus on the selected analysis period
<img width="326" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/23f0ceac-a62d-4211-bf27-4fb153713373">

### Implementation (design [linked below](https://github.com/NASA-IMPACT/veda-ui/issues/857#issuecomment-1985810963))
- [ ] ~Add timeline chart widgets~
- [ ] ~The chart widget should open up the analysis chart menu~
- [x] When starting an analysis, both map and timeline zoom to selected area
- [x] Analysis chart lines are updated to design
- [x] Analysis chart tooltip is updated to design
- [ ] ~Edgecase behaviors~

**Comment by faustoperez** [comment]
Review and propose a design solution to toggle chart metrics addressed in #860

**Comment by faustoperez** [comment]
Related: Review date selection on the timeline #833

**Comment by faustoperez** [comment]
Hi, I have updated the Figma file for this ticket.

Link to Figma file 👉 https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=1127%3A2201&mode=design&t=fGtGK3DblwdZpUGr-1

I am experimenting with a new format for design communication and organization to ensure that each design element is linked to its corresponding issue and the reasoning behind the design is documented. Let me know if this works 👍 

<img width="1394" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/78dea1fc-9008-4de9-b4de-55b035de6c9f">

**Comment by sandrahoang686** [comment]
Note:
* Download feature available from old analysis view
* The analysis options including collapser should appear for each layer chart
* When layer chart is zoomed out and there is no space for the analysis options, hide them

**Comment by aboydnw** [comment]
@hanbyul-here This looks partially complete, am I interpreting that correctly? Should we break off a new ticket to represent whatever work is incomplete? Might be easier to follow that way.

**Comment by hanbyul-here** [comment]
If I remember correctly, we decided to make some changes for R2 and keep the other changes (ex. timeline indicator look & function change) for the next phase. I agree that it might be better to close this ticket and open a new ticket with the leftover items. @faustoperez Do you know if we made a separate ticket for the items that we couldn't tackle for R2?

**Comment by aboydnw** [comment]
I created #986 and I believe the others remaining are covered by #979 
Let me know if we are missing an important chunk of work
