### ISSUE TITLE
[E & A] Add analysis presets for US states

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#872]
The current Analysis interface has area presets:

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/132c9b70-8c54-4c6b-9549-0d2310e25333)

We need the same for E&A, most importantly featuring U.S. federal states, for example from the [U.S. Census TIGER dataset](https://www.census.gov/programs-surveys/geography/guidance/tiger-data-products-guide.html).

## Acceptance criteria

- [x] Designed area preset selection
- [x] Implemented in E&A interface

**Comment by faustoperez** [comment]
For better UX, I suggest we use the map to select geographies depending on the map zoom level. Not just the US states but any admin area?

**Comment by j08lue** [comment]
Could we still envision that there is some kind of switch to turn on these boundaries when you start the Analysis workflow? E.g. instead of the "pen", you would choose "boundaries" and zoom to the highest level from where you pan and zoom until you selected one? 

So boundaries would only be present as a possible first step in an Analysis workflow, not otherwise?

**Comment by faustoperez** [comment]
Assigning this to myself, let's plan some design work for this :)

**Comment by faustoperez** [comment]
Here are the designs for this ticket @hanbyul-here.

Link to Figma file 👉 https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=1390%3A3471&mode=design&t=Bb7c993Uj5nExTLS-1



<img width="1728" alt="Frame 2514" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/38c0a80c-e051-4ef1-95f1-9c58df9984df">

- Add a dropdown to the Analysis tools block on the E&A map
- The default state is “Select area to analyze”

<img width="1728" alt="Frame 2518" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/360c9bad-3535-45f1-b936-ce17ae87ff98">

- The dropdown shows the list of US states.
- The fist item is the whole country, then the list of states ordered alphabetically.
- Feel free to use the native component and the `<optgroup>` element if it makes the implementation easier: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup


<img width="1728" alt="Frame 2517" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/bbf0a295-986b-4bfd-9bc5-4131adc94247">

- Then the behavior is the same as drawing and analyzing a shape.
- The only difference is that the name of the geography is written on the analysis label at the top of the map.

**Comment by hanbyul-here** [comment]
I wanted to check in about what the expectation is for the 'United States' preset. Should it include all the state-equivalent territory like the screenshot below? 

<img width="420" alt="Screen Shot 2024-04-18 at 2 13 05 PM" src="https://github.com/NASA-IMPACT/veda-ui/assets/4583806/098e97cc-c037-4143-99a0-f6d97a4e04e6">
