### ISSUE TITLE
[E & A] y-axis label overlaps long tick labels

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#881]
When the tick labels are long, the y-axis label overlaps with them, like in [this preview](https://deploy-preview-319--ghg-demo.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22total-methane%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Avg%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&date=2019-12-31T23%3A00%3A00.000Z&aois=%5B%22t%7Bm%7DQefraE%7Cz%7B%40zzra%40uxpn%40eqlB_bqCgtug%40%22%2C%22d75ea7%22%2Ctrue%5D&dateRange=2019-10-31T23%3A00%3A00.000Z%7C2020-02-29T23%3A00%3A00.000Z).

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/5bd91f5a-5527-4bc6-96d6-4fa1d350564f)

## Acceptance criteria

- [ ] Y-axis label has enough space even for long tick labels

**Comment by hanbyul-here** [comment]
There is really no scalable solution for this problem (unless we want to put a lot of effort into it.) I will put more space for label now.
