### ISSUE TITLE
[E & A] Some datasets cannot be selectable together with others

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#882]
We have a dataset that should be shown exclusively on the E&A interface, without the possibility to add others.

This is a complex ask, but let us see whether we can find a simple solution.

## Acceptance criteria

- [ ] Found and designed a solution
- [ ] Added the option
- [ ] Configured it for the relevant GHG dataset

**Comment by faustoperez** [comment]
Could you please elaborate a bit on what this dataset is and the reasons behind this ask @j08lue ? Thank you!

**Comment by j08lue** [comment]
As we discussed, this is basically the response to

- https://github.com/US-GHG-Center/veda-config-ghg/issues/314

In essence, users looking at the EPA inventory dataset layers should not view these layers together with other products **without context about the different datasets**. We will learn soon about what context is required.

We have basically three options:
1. Certain layers cannot be selected together with others -> change in the layer selection modal
2. When certain layer combinations are added to the map, contextual information is provided
3. Certain datasets allow single-layer view only (the old Exploration interface)

In a recent discussion among stakeholders, there was a preference for the first option - hence this ticket here. But I think if we can solve the second once nicely, that could also be a possibility.

**Comment by j08lue** [comment]
Here is a preview of these layers in E&A:

https://deploy-preview-319--ghg-demo.netlify.app/exploration?datasets=%5B%5D&taxonomy=%7B%22Source%22%3A%22epa%22%7D

And this is what we should prevent - EPA totals viewed on top of other totals without context:

https://deploy-preview-319--ghg-demo.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22total-methane%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Avg%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%2C%7B%22id%22%3A%22prior-total-id%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Avg%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%2C%7B%22id%22%3A%22post-total-id%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Avg%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%2C%7B%22id%22%3A%22total-ch4%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Avg%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&date=2016-04-16T22%3A00%3A00.000Z&taxonomy=%7B%22Source%22%3A%22epa%22%7D

**Comment by sandrahoang686** [comment]
Update: Moving forward with Option 1 but this still awaits final confirmation
Check thread here => https://developmentseed.slack.com/archives/C054MDFFCKV/p1711147809110499?thread_ts=1710943676.648259&cid=C054MDFFCKV

**Comment by faustoperez** [comment]
This is a summary of what we discussed @sandrahoang686.

Link to Figma file 👉 https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=1367%3A1527&mode=design&t=odnjyl4RFN0QxrKX-1

- Move the text after the data catalog modal to the empty state text, like so:

<img width="1037" alt="Data layer selection - filters - empty state" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/52bf3e71-8e60-42f0-9480-e9b26daab74b">

- Remove hide filters button, and sort by dropdown. Make all filters fit in one row. Play with the search bar with to make sure the filters stay in one row even when a long text option has been selected.
- Lower the padding on both the footer and the header to match the designs and make everything a bit more compact.
- Add red pill next to EPA collection. Text on pill: "Can only be analyzed with layers from the same source"

<img width="1037" alt="Data layer selection - filters - EPA" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/ec1245f2-5e61-4645-9d1d-fa5cb7f815cd">
