### ISSUE TITLE
Migrate necessary components and logic from old map dir to new map dir

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#888]
We need to migrate necessary components from the old map directory `/common/mapbox/` to the new map directory `/common/map/` so we can get ready to deprecate the old map component.

This task is a follow up after this PR [here](https://github.com/NASA-IMPACT/veda-ui/pull/827#issuecomment-1996626033)

Things to consider:
* Clean up by deleting files and components no longer in use
* Think about rearranging the files and components to be more re-useable

**Comment by aboydnw** [comment]
@sandrahoang686 can you help me understand how important this is? Should be part of the VEDA refactor work?

**Comment by sandrahoang686** [comment]
@aboydnw this is tied to https://github.com/NASA-IMPACT/veda-ui/pull/827#issuecomment-1996626033. Which actually would be a blocker for https://github.com/NASA-IMPACT/veda-ui/issues/899. this ticket specifically is really just clean up and moving logic that currently sits with the old map component over to the new so it could be a part of the refactor work. We are gonna have to finish up and close that PR though because it would be very intertwined.

**Comment by aboydnw** [comment]
@dzole0311 I see those linked tickets above are closed, does that mean we can close this ticket?
