### ISSUE TITLE
Sort featured stories based on publication date

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#894]
Our featured stories are not sorted by publication dates now. It will make the most sense to sort them by the dates. 

![image (1)](https://github.com/NASA-IMPACT/veda-ui/assets/4583806/8b9e14d0-ba2b-4059-9343-5e6a7a29db4d)

**Comment by sandesh-sp** [comment]
Hi @hanbyul-here, just to confirm, should newer stories appear first (ordered from most recent to oldest)?

**Comment by hanbyul-here** [comment]
@sandesh-sp Yes, more recent one should come first!
