### ISSUE TITLE
[Refactor] VEDA Core Features - Data Stories Catalog

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#901]
### Context

This ticket is to create a core feature within veda-ui. Composite features are the core of VEDA and often combine different components to make a specialized tool for the dashboard. 

These are view containers that deliver a core part of the VEDA dashboard product and these containers are composed of resuseable components - so when breaking this out, think about pieces that can be reuseable and start to modularize the stateless/presentational components as well. 

**Notes:**
* Mark new files for VEDA2 refactor with `@VEDA2-REFACTOR-WORK`

**Acceptance Criteria:**
**General**
- [ ] Reusability => modularize stateless/presentational features to be as reuseable as possible within the core feature view containers
- [ ] Feature should be entirely data agnostic => Separate out the data logic from this feature component into the data layer. _Note: Data will now have to be passed in as props so we will need to update the page views to supply this_
   - [ ] Composite Features should have stricter typed interfaces
- [ ] This feature should still support current instances and be backwards compatible

**Specific**
_{TO BE UPDATED}_

**Related to:** https://github.com/NASA-IMPACT/veda-ui/issues/801

**Resources:**
* ADR: https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/adr/002-application-architecture-for-configurability.md#decision-outcome
* [Miro Board outline Core Features](https://miro.com/app/board/uXjVNlIZVJI=/)

**Comment by sandrahoang686** [comment]
@faustoperez @j08lue @aboydnw For this feature component, are we looking to migrate this view over to match the new Data Catalog view? 

Spoke with @hanbyul-here because between the Data Catalog View and the Data Stories view, they are similar in terms of what they are both rendering - a list of cards with a controls component, the only difference is the type of content list (stories vs datasets). We are debating whether or not it makes sense to create a feature component that would just satisfy both of these.

**Comment by faustoperez** [comment]
> @faustoperez @j08lue @aboydnw For this feature component, are we looking to migrate this view over to match the new Data Catalog view?

yes, captured here 👉 https://github.com/NASA-IMPACT/veda-ui/issues/932

**Comment by sandrahoang686** [comment]
Checkin Update: 
Instead of creating a Data Stories Hub FC - We should think of it as creating exportable views the user can choose from to render a list of content types. Because the Data Stories hub and Data Catalog are very similar in terms of what types of components they render.
