### ISSUE TITLE
[Refactor] VEDA Core Features - Time-Series Analysis Tool (E&A) Discovery

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#902]
Expose E&A component and document all tech-debt we run into into separate issues to break this out. Try to get it working with NextJs instance if possible.

Link tech-debt issues here

**Comment by aboydnw** [comment]
@sandrahoang686 I wonder if this should be a component/feature. My main doubt is that people will use this independent of the rest of the E&A page. Maybe we should just have E&A as a "composite feature" based on the different categories in #1076 

But maybe I'm splitting hairs and, even if we tell stakeholders the E&A page is a composite feature, this ticket still makes sense defined as is. What do you think?

cc @hanbyul-here @dzole0311 @faustoperez

**Comment by sandrahoang686** [comment]
This is the composite E&A component as we discussed during checkin 👍🏼

**Comment by sandrahoang686** [comment]
**Summary:** Feature Branches created and tech-debt identified which will require more time to work on to bring E&A to next instance
**PRs/Feature Branches:**
**veda-ui**: https://github.com/NASA-IMPACT/veda-ui/pull/1154
**next-veda-ui**:https://github.com/developmentseed/next-veda-ui/pull/4

**Following tech-debt tickets created from discovery:**
* https://github.com/NASA-IMPACT/veda-ui/issues/1155
* https://github.com/NASA-IMPACT/veda-ui/issues/1156
