### ISSUE TITLE
Blank time-series chart with some datasets + selected AOI

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-ui#904]
# Description
With some of the datasets, a specific example being the Air Sea CO2 flux in the GHG center, the time series chart values are null even tho the `/search` returns results. See the attached screenshots.

This happens when the user draws a polygon on land where the data values don't exist. In such cases, the time-series chart should display a message instead of displaying a blank chart.

All the `/statistics` responses look like this:

```json
 "properties": {
        "statistics": {
            "b1": {
                "min": null,
                "max": null,
                "mean": null,
                "count": 2274.60009765625,
                "sum": null,
                "std": null,
                "median": null,
                "majority": null,
                "minority": null,
                "unique": 0.0,
                "histogram": [
                    [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0
                    ],
                    [
                        0.0,
                        0.1,
                        0.2,
                        0.30000000000000004,
                        0.4,
                        0.5,
                        0.6000000000000001,
                        0.7000000000000001,
                        0.8,
                        0.9,
                        1.0
                    ]
                ],
                "valid_percent": 0.0,
                "masked_pixels": 4551.0,
                "valid_pixels": 0.0,
                "percentile_2": null,
                "percentile_98": null
            }
        }
```

See an example here: https://earth.gov/ghgcenter/analysis/results?start=2018-01-01T00%3A00%3A00.000Z&end=2022-12-31T00%3A00%3A00.000Z&datasetsLayers=air-sea-co2&aoi=%7C~%60eTwcvbGftcAli%7B%7D%40%7DnohDuhab%40

It will be less of a problem once E&A is out because users can see where data values exist. However, it should still be handled.

# Screenshots
![image](https://github.com/NASA-IMPACT/veda-ui/assets/7830949/6792750e-1597-4559-a59f-cab7165315bc)
![image](https://github.com/NASA-IMPACT/veda-ui/assets/7830949/eb619258-a04f-4766-a7ac-c2d656718cdf)

**Comment by aboydnw** [comment]
@hanbyul-here is this ticket actually complete? I see the merged PR linked above, not sure if it was intentionally left open

**Comment by j08lue** [comment]
Hmm, in the current production GHG Center, the `/statistics` API actually throws a 500 error for analyzing the air-sea flux on land (all-NaN, I assume).

https://earth.gov/ghgcenter/exploration?datasets=%5B%7B%22id%22%3A%22air-sea-co2%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&date=2022-11-30T23%3A00%3A00.000Z&selectedForEditing=true&aois=%5B%22j%7Br%7EaA%7B%60%7ElBgroaAssmTiivItgf%7D%40%22%2C%22665a97%22%2Ctrue%5D&dateRange=2022-09-30T22%3A00%3A00.000Z%7C2022-12-31T23%3A00%3A00.000Z

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/0725d1ab-f69d-464e-a619-6379a89d41a7)

This layer with no data outside the US shows the expected response: "No data for the selected time range and area of interest." - which @hanbyul-here implemented in the PR above.

https://earth.gov/ghgcenter/exploration?datasets=%5B%7B%22id%22%3A%22total-methane%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&date=2019-12-31T23%3A00%3A00.000Z&selectedForEditing=true&aois=%5B%22j%7Br%7EaA%7B%60%7ElBgroaAssmTiivItgf%7D%40%22%2C%22665a97%22%2Ctrue%5D&dateRange=2015-12-25T23%3A00%3A00.000Z%7C2020-12-31T23%3A00%3A00.000Z&taxonomy=%7B%22Source%22%3A%22epa%22%7D

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/40de1f94-dae6-4a45-9bb3-d5c98199081b)

Perhaps we should have a fresh ticket, in https://github.com/US-GHG-Center/ghgc-backend or so, for the API / data issue we are seeing, and close this one here.

**Comment by hanbyul-here** [comment]
@j08lue The team has noticed the problem with air-sea co2 data. The ticket is : https://github.com/US-GHG-Center/veda-config-ghg/issues/388

The original ticket is meant for 'empty statistics' - which we show the correct error message now (No data for the selected time range..), at least for the new exploration page. And we decided not to put any more efforts on old analysis page, so I will say this ticket be closed.

**Comment by aboydnw** [comment]
Sounds good, I'll close this and @j08lue or @smohiudd you can move the linked ticket to whatever board makes the most sense.
