### ISSUE TITLE
[E & A] Add layer description to layer info modal

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#912]
- https://github.com/US-GHG-Center/veda-config-ghg/pull/317#issuecomment-2035073971

https://github.com/US-GHG-Center/veda-config-ghg/blob/077c3e8fd5ec7af99287106c58afa16dad7d1593/datasets/casagfed-carbonflux-monthgrid-v3.data.mdx?plain=1#L41

We would probably want to put that right underneath the layer title or underneath the short info pills (units etc). We can try both in a PR and decide on what looks best, or @faustoperez can advise.

## Acceptance criteria

- [ ] Layer info modal in E&A shows the layer description

**Comment by Jeanne-le-Roux** [comment]
Just a note (from GHG Center perspective) that of the E&A improvements, I think this should be first priority - one of our data providers from the EPA noticed that the layer descriptions were missing during testing & requested they be added

**Comment by faustoperez** [comment]
@hanbyul-here @sandrahoang686 please advise if this is possible, design wise is a simple task.

**Comment by hanbyul-here** [comment]
@faustoperez Yes, I don't see any challenges in the implementation of this feature. I will make a change following @j08lue 's first description and we can take it from there if any revision is necessary.

**Comment by faustoperez** [comment]
@hanbyul-here Designs updated in Figma 👉 https://www.figma.com/design/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?node-id=1588%3A3695&t=k7cuWpeIIwhyoKMV-1


![Layermodal](https://github.com/NASA-IMPACT/veda-ui/assets/12268629/0c1f9ac9-7a43-4707-8e14-92ea9e4d32d0)
