### ISSUE TITLE
[Data Catalog] Implement catalog enhancement with floating filter sidebar

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#915]
Upon stakeholder feedback, we reviewed the design of the data catalog filter and dataset listing layout.

- https://github.com/US-GHG-Center/ghgc-architecture/issues/133

This has now been approved as a significant improvement and is ready for implementation

Figma Link here https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=1179%3A5867&mode=design&t=bXYpdYKR3ZMvi9bU-1

## Acceptance criteria

- [x] Implemented layout update with floating filters in data catalog

**Comment by sandrahoang686** [comment]
@j08lue @faustoperez did we want to feature flag this feature? Or a way to switch between, original and new view based on some config var?

**Comment by j08lue** [comment]
> did we want to feature flag this feature? Or a way to switch between original vs new view based on some config var?

Good you are asking. No, this would be a core update for all instances.

**Comment by j08lue** [comment]
Let us consider this closed - the feature is implemented, although some details may still be missing. We can track those here:

- https://github.com/NASA-IMPACT/veda-ui/issues/926
