### ISSUE TITLE
[E & A] Filter text overflows

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#924]
When selecting long filter values in the new E&A layer selection modal, the text overflows like this:

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/e8858695-ed59-425f-907d-92035995b3b7)

See e.g. https://deploy-preview-319--ghg-demo.netlify.app/exploration?datasets=%5B%5D&date=&aois=%5B%5D&dateRange=&taxonomy=%7B%22Product%20Type%22%3A%22ground-measurements%22%7D to reproduce.

I guess what I would expect is that the text is clipped.

## Acceptance criteria

- [ ] Along long filter names / values are handled nicely

**Comment by j08lue** [comment]
Mostly fixed, but the filter name still overflows:

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/1308b872-4328-407c-a024-e156606404af)

**Comment by hanbyul-here** [comment]
It was improved but still overflowing : https://github.com/NASA-IMPACT/veda-ui/pull/927#pullrequestreview-2024276415

**Comment by aboydnw** [comment]
This was inherently fixed by changing the layer selection to better match the updated data catalog UI
