### ISSUE TITLE
[Design] Bring new data catalog layout also to the Exploration layer selection

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#932]
We recently implemented a new data catalog layout with rows and a (floating) filter sidebar:

- [#918 ](https://github.com/US-GHG-Center/ghgc-architecture/issues/133#issuecomment-2009192700)

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/d0a2811e-3781-40a9-8a73-15af9ced5194)

The same layout would also help in the Exploration layer selection, so that users can better browse the available layers:

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/41b834dc-d92b-44bc-8e16-bf41e9876c7c)

It will probably need some adaptation?

## Acceptance criteria

- [ ] Adapt row/sidebar data catalog layout for Exploration layer selection

**Comment by faustoperez** [comment]
Self-assigning this 👍

**Comment by j08lue** [comment]
Once the design change is implemented, we can also close these two issues:

- https://github.com/NASA-IMPACT/veda-config/issues/355
- https://github.com/US-GHG-Center/veda-config-ghg/issues/59

**Comment by faustoperez** [comment]
Designs ready for revision on Figma 👉 https://www.figma.com/design/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?node-id=1593%3A4526&t=awwUsQrQgc9qB1Fr-1

![Desktop Flow](https://github.com/NASA-IMPACT/veda-ui/assets/12268629/2bc40dce-484c-4c7c-87a1-b2f95c6f7185)
