### ISSUE TITLE
Turn development / configuration docs into rendered pages?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#933]
Our docs are currently just Markdown files in the repo. 

https://github.com/NASA-IMPACT/veda-ui/tree/main/docs

While that is super lightweight and as portable as can be, they are not very accessible to people who are new to contributing to VEDA UI powered projects, like the GHG Center. 

We want that configurators do not need to be developers, so making the docs more findable and accessible for them would be good.

We could turn them into rendered pages (e.g. Quarto) that either get deployed with the instance (something like `/contribute` or so) or as a separate GitHub Pages site. Could also somehow integrate them with https://nasa-impact.github.io/veda-docs/ - those are mostly for science users of the data and services, but these users could also be contributors in the spirit of the Open Science lifecycle VEDA is aiming to complete.

## Acceptance criteria

- [ ] Described the options of making the VEDA config contributing docs more findable and accessible and decided on one -> documented in an ADR

**Comment by aboydnw** [comment]
Superseded by CMS integration work with Strappi and others
