### ISSUE TITLE
Change GTM Tracking ID

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#935]
I tried finding the ID in the code myself but didn't have any luck. We are doing some re-organizing of google tag manager properties and just need to switch the ID to a new one. 

Old ID: GTM-KHK5WJQ
New ID: GTM-N59QGDJ9

**Comment by aboydnw** [comment]
@hanbyul-here @sandrahoang686 is this a quick switch?

**Comment by dzole0311** [comment]
I might be wrong but this seems to be set on a per instance basis, [during deployment here](https://github.com/US-GHG-Center/veda-config-ghg/blob/develop/.github/workflows/deploy.yml#L79). I'm not sure that we have the GTM ID in the UI library due to it being "sensitive" info but also each instance should require a separate GTM id I guess 🤔 @aboydnw If you're an owner of the veda-config repo, you could try looking Settings > Secrets and variables > Actions for it? (I would've tried but I'm not an owner).

**Comment by aboydnw** [comment]
Ah okay, this is good practice for me! Something new to learn.

I only need to update it for the Earthdata Dashboard. I assume GHG Center and EIC would be secrets managed in other repos, correct?

I updated the google tag manager ID. Not sure if the other two GTM secrets here need to be updated...
![image](https://github.com/NASA-IMPACT/veda-ui/assets/92742765/4d95cf33-3d9e-4a01-a862-20f2e71c7eba)

**Comment by hanbyul-here** [comment]
tag_auth and tag_preview seem to be used to set an environment, So as long as we are not changing an environment, it seems we don't need to change them. Here is where you can find auth and preview id in case: https://www.npmjs.com/package/react-gtm-module#how-can-i-find-auth-and-preview

**Comment by aboydnw** [comment]
So it seems like auth and preview are mainly used if you have setup different environments. We haven't set that up in GTM, so the code here wouldn't make any use of it. 

I could try setting it up, but that might be opening up a can of worms that we don't need. We could just leave it as is, or we could remove those variables entirely?

**Comment by aboydnw** [comment]
hm I'm still not seeing the new GTM id in prod...is there anything else I needed to do besides just change the secret in admin?

**Comment by j08lue** [comment]
I guess the secret is injected during deployment, so we would need to re-deploy for it to take effect.

**Comment by hanbyul-here** [comment]
I think it will be better to separate the issues and run the deployment on production for new gtm id.

**Comment by aboydnw** [comment]
How do we run the deployment? Or is there a deployment coming up soon that this could join?

**Comment by hanbyul-here** [comment]
We can retrigger action to deploy new google tag manager ID through GitHub. I will do it on Monday.

**Comment by hanbyul-here** [comment]
Closed via https://github.com/NASA-IMPACT/veda-config/pull/394

**Comment by aboydnw** [comment]
@hanbyul-here I don't think this is working...could it have something to do with the auth & preview variables?

When I look at the default tag from GTM, I don't see anything with auth or preview:
'''

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-N59QGDJ9');</script>

'''

But when I look at what's showing up in the dashboard, I see both mentioned:
![image](https://github.com/NASA-IMPACT/veda-ui/assets/92742765/b1bdc409-25cf-4b51-8891-4f9043c8ee0d)

To my knowledge, I haven't been using either in the config on the GTM side, so I'm not sure what to do with them.

**Comment by aboydnw** [comment]
When I try to access it in preview mode in GTM, it tells me that it wasn't found, which makes me think it's something wrong with these tokens.
![Uploading image.png…]()

**Comment by aboydnw** [comment]
I updated the auth secret to match the new container. We aren't using environments at the moment so really the right solution would either be to add environments for us to use on our staging site or to remove these variables altogether. But if we want quick fix then I think another push to prod with the new secrets should do the job. I guess it's something for us to learn for future uses of GTM

@hanbyul-here could you do another quick push tomorrow? Right now we aren't tracking any data at all because of this.

**Comment by aboydnw** [comment]
Everything seems to be working now!
