### ISSUE TITLE
[VEDA2 Refactor] Build NextJs Instance Prototype

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#947]
**Description:**
Build a NextJs Instance prototype to see how it would parse and transform static content and then consume the veda-ui library. 

It would be a good idea to just build this prototype with for a single page / route. The **_Data Catalog page_** is a good option as it looks at our static content and relies on this dataset as a prop and is already being broken out.

This should just be a _sandbox prototype_ and not the official template instance. 

**Dependencies / Blockers:**
* [Build Pipeline Implementation](https://github.com/NASA-IMPACT/veda-ui/issues/800)
* Core feature breakouts (doesn't have to be all, can import these along the way once they are broken out and ready)

**Questions to answer:**
* How will we support parsing of JSX in the mdx files?
* Is any interference from the parcel resolver needed to support how our current content?
* Is nextJs ideal?

**Comment by hanbyul-here** [comment]
I briefly played with NextJS's default blog template, which supports JSX, could think of more broken-down steps as below. Each item can be better defined but am leaving notes for now as I wrap my day.

- Update Node : We might not need to update Node if we mark the Node version more flexibly (like >=16) but I think it is time to update Node anyway as 16 reaches its end of life. We would need to update instances' Nodes versions as well.
- Parse frontmatter in a way that VEDA UI expects (This is what Parcel resolver does now. I believe a lot of snippets from the resolver directly used)
- Make a linkage between VEDA-UI and the test instance: As https://github.com/NASA-IMPACT/veda-ui/issues/799 is not resolved but this test instance needs VEDA UI as a dependency, the instance needs a way of using VEDA-UI. I think the fast way is just to use GitHub branch (and use `yarn link` if any local dev is needed) until #799 is resolved.

**Comment by hanbyul-here** [comment]
This is the repo that I set up: https://github.com/developmentseed/next-veda-ui
I copied one dataset.mdx and one stories.mdx to the test repo, to see if we can use them in NextJS environment.

**Comment by hanbyul-here** [comment]
Notes on findings:
1. There are some MDX components that make sense for users to opt out. 2x.Next offers some components such as Image (can be server side-renered), Link component. 
2. Parcel-specific file urls (`new URL(...).href`) should be replaced
3. Components are not getting exported as expected: We strictly check what the children components are for `Block`, allowing only specific combinations so the layout can be styled as expected. We do this by checking displayName of the components. displayName

**Comment by hanbyul-here** [comment]
We found the blockers and lessons from this test instance which you can find in: https://app.excalidraw.com/s/2QcqyAR2HKf/5sfKxQIPZNh 



![Image](https://github.com/NASA-IMPACT/veda-ui/assets/4583806/ffc27f24-1e42-4748-9e6f-92dbdfbf58c3)


 I couldn't achieve the two goals that initially set up, which use actual components from UI library. This experiment gave lessons that there should be some dedicated LOE to make the styles of the components work on the instance side. So I will suggest we separate out these two goals as an issue (it will be something like 'make the component style from UI work with instance).
- Replicate DataCatalog component with parsed data
-  Replicate one Story with parsed data. Identify which components are already usable and which are not.
