### ISSUE TITLE
Cookie Consent Alert

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#953]
## Context

We use cookies to track usage with google analytics. Instances that use google analytics should have a cookie banner to give users the option to reject cookies.

## Acceptance Criteria

- [ ] Given that an instance has turned on the cookie banner, when a user visits that dashboard and has not previously provided an explicit response to the cookie alert, then they are presented with a cookie alert
- [ ] Given a user visits an instance with the cookie alert who has not previously accepted the use of cookies when they ACCEPT cookies then we continue to track using google analytics 
- [ ] Given a user visits and instance with the cookie alert who has not previously accepted the use of cookies when they REJECT the use of cookies then we don't track their usage with google analytics
- [ ] Any links in the alert content open in new tabs
- [ ] If the user elects to close the alert without making an explicit selection, we assume that as a yes and continue collecting GA data, but ask the user again the next time they visit the site

## Related Tickets

- https://github.com/US-GHG-Center/veda-config-ghg/issues/162

**Comment by aboydnw** [comment]
@snmln I made some tweaks to the AC based on the convo in the PR, let me know if anything looks out of place

**Comment by snmln** [comment]
Linking PR: https://github.com/NASA-IMPACT/veda-ui/pull/1127
