### ISSUE TITLE
USWDS Experiment with New and Existing Component Spike

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#959]
This spike/experiment ticket is the result of issue #889.

We should implement a new component as part of a sandbox experiment and convert an existing component (dumb/granular) to  understand if USWDS will serve our design needs and if the technical implementation wont produce any unforeseen risks to support current architecture and the new refactor. 

**Acceptance Criteria:**
- [ ] Create the design scaffolds (@faustoperez )
- [ ] [Potentially] Decide on and implement a new feature request / component with USWDS (possibly https://github.com/US-GHG-Center/veda-config-ghg/issues/288 ?)
- [ ]  Decide on and convert a smaller granular component over to USWDS (card, accordion, or input form, etc)
- [ ]  Document outcome if we are moving forward in ADR
- [ ] Decide and document what to do with existing (DevSeed UI) library
- [ ] Impact of new design system on VEDA-UI as a registry (https://github.com/NASA-IMPACT/veda-ui/pull/976)

**Comment by aboydnw** [comment]
Time boxed to 1 day

**Comment by sandrahoang686** [comment]
Time boxed to 1 day for an existing component *

**Comment by dzole0311** [comment]
Spike documented here: https://docs.google.com/document/d/10gc3Ss1azqvq5q1EAvEFATwlEXKAtDNAcujOL_cxkOI/edit?usp=drive_link
