### ISSUE TITLE
Replace Mapbox component to the new Map component in Exploration page

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#969]
## Context
This is a part of https://github.com/NASA-IMPACT/veda-ui/issues/712 , continued work of https://github.com/NASA-IMPACT/veda-ui/pull/827

As we move forward to allowing multiple 'views' for datasets, we decided not to deprecate the current explore view. Therefore this page needs to re-writen to use the new map component so we don't have to keep two map components. 

Relates to the original exploration view that can be seen in earthdata.nasa.gov/dashboard

## Acceptance Criteria

- [ ] #987

## Related Tickets

https://github.com/NASA-IMPACT/veda-ui/issues/712

**Comment by hanbyul-here** [comment]
We are trying to use new E&A-specific Types and structures for other parts of the application, which results in unnecessary overhead and typecasting. This is the daigram that we came up with to have new Type and data fetching process.

<img width="919" alt="Screen Shot 2024-05-31 at 9 30 14 AM" src="https://github.com/NASA-IMPACT/veda-ui/assets/4583806/ac17cad7-e102-4713-a562-5b40ea707e18">

**Comment by sandrahoang686** [comment]
@hanbyul-here thanks for the update and diagram, so is the goal to eventually migrate what is currently using these old timeline related datatypes to the new ones to be created where we aiming for them be more extensible and better defined for more usecases?

**Comment by hanbyul-here** [comment]
The diagram is to express the need for an explicit data type  when the data does not require analysis capacity (Basically all the map-related components not on the E&A page) : like this one: https://github.com/NASA-IMPACT/veda-ui/pull/988/files#diff-a84645a045108f129bae11ffbb6d29f9b1c8744ae7a4f63b4db872211394889bR122 and use timeline datasets only for the Exploration page.

**Comment by sandrahoang686** [comment]
@hanbyul-here yep, that makes sense

**Comment by hanbyul-here** [comment]
I am closing this issue since #840 will totally deprecate the current Explore page, and it is not worth putting more effort into it. 

I tried to decrease the duplicated efforts in https://github.com/NASA-IMPACT/veda-ui/pull/991 , by only focusing on the new E&A page for the ArcGIS layers. 
Unless it is a change that needs to go out immediately, I think other layers can follow the same pattern to decrease the duplicated work - make them work only with the new E&A page, which uses our new map component.
