### ISSUE TITLE
Document the journey of refactoring

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#974]
## Context
VEDA refactoring is moving on. We are getting a lot of findings, lessons, and dependencies of each task from multiple Spikes. We ticketed out spikes, and recordings of these findings are scattered over these issues and PRs. It will be helpful for the team to have one place to document the learnings for record purposes and also to communicate with other members of the project to understand the progress of the refactoring. 

## Acceptance Criteria

- [ ] Have a central point of documenting the journey, findings of each spike for refactoring

## Related Tickets
There are many tickets related to refactoring, mainly listing the epic/spike tickets that have recordings of findings. 

- https://github.com/NASA-IMPACT/veda-ui/issues/799
- https://github.com/NASA-IMPACT/veda-ui/issues/896
- https://github.com/NASA-IMPACT/veda-ui/issues/947

- Next test repo: https://github.com/developmentseed/next-veda-ui/
- Branch to publish library: https://github.com/NASA-IMPACT/veda-ui/tree/publish-lib

**Comment by aboydnw** [comment]
@dzole0311 mentioned today that we could make better use of google docs, this might be a good place for it.

I would also like to drop a short version/explanation of the refactoring into our roadmap ticket here: https://github.com/orgs/NASA-IMPACT/projects/117/views/1?pane=issue&itemId=65880804

**Comment by sandrahoang686** [comment]
Agreed with moving this to a google doc and this should be a team effort, we should create a skeleton template and expand on it. If that hasn't been created yet, I'll take the liberty to do that.

**Comment by sandrahoang686** [comment]
Document here https://docs.google.com/document/d/14NdC_9l_N5JQ8bID1gk0vcnzOA-G1ubRzfP5HHTeCOY/edit?usp=sharing
