### ISSUE TITLE
[E & A] Date picker aligns with temporal density

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#990]
## Context

Deborah received some feedback from scientists while they were playing with the new exploration and analysis page. One comment they had was, when they are viewing an annual dataset, the date shouldn't be specific to the day. "We're not viewing October 8th, we're viewing 2021." This is potentially confusing.

My assumption is the data picker should default to the lowest common denominator, since we can show datasets of multiple temporal densities on the page. So, I wrote the AC below to match that. I intentionally left out sub-daily temporal densities, we can adress that in a different ticket.

## Acceptance Criteria
- [ ] Given I am only viewing an annual dataset, then the date picker only allows for selecting of years
- [ ] Given I am viewing layers with temporal densities no finer than monthly, then the date picker only allows for selecting of months
- [ ] Given I am viewing layers with daily temporal densities, then the date picker allows for selecting of days
- [ ] I can only select dates in the date picker that are included in the temporal range(s) of the dataset(s) selected

**Comment by aboydnw** [comment]
Potentially relates to #979 if we are assessing the new design system, could check for feasibility of this ticket

**Comment by faustoperez** [comment]
> My assumption is the data picker should default to the lowest common denominator, since we can show datasets of multiple temporal densities on the page

Agree. Self-assigning this.

**Comment by j08lue** [comment]
You cannot avoid that the "master playhead" sits at an arbitrary point of a **period** (year, month, day), instead of in the center, when there is another layer with lower time resolution.

But maybe we can get a better indication, **which period is currently active**, even if the playhead sits somewhere in between?

Maybe something like highlighting the active period or so? Just an idea...

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/83902a02-27c6-400b-8584-0c0395166765)

**Comment by faustoperez** [comment]
> But maybe we can get a better indication, which period is currently active, even if the playhead sits somewhere in between?

I like that idea Jonas!

**Comment by j08lue** [comment]
I see this ticket was about the date picker and not the playhead or the boxes on the timeline.

Did you consider, though, also implementing some visual cue for the user to see which period is active, as I suggested above? Or did you drop / postpone that? Just curious...
